/**
 * Generate a chapter's formula-axis module from its hand-classified tags.
 *
 *   npm run formula:generate                      # all chapters
 *   npm run formula:generate -- matrices-determinants
 *
 * PURE: reads `scripts/formula/tags/<chapter>.json` (one entry per question,
 * produced by reading every solution) plus `scripts/formula/meta/<chapter>.ts`
 * (authored names, LaTeX, statements) and writes
 * `src/lib/formula/<chapter>.ts`. No database, so the output is deterministic
 * and the command is safe to re-run in CI.
 *
 * Generated rather than hand-maintained because a chapter's entries carry over
 * a thousand uuids between them, and a mistyped uuid fails SILENTLY — the
 * question simply vanishes from its page with no error anywhere.
 *
 * Adding the next chapter is a data job, not a code one. See README.md.
 */
import fs from "fs";
import path from "path";

/**
 * Publishing floor. An identity used by fewer questions than this is withheld
 * rather than shipped: a page with four questions on it is not a drill, and the
 * index page states this number to the reader. Changing it here changes the
 * page copy too — `src/app/formula/page.tsx` reads the published count.
 */
const MIN_QUESTIONS = 12;

type TopicMeta = {
  name: string;
  kind: "formula" | "property" | "technique";
  latex: string;
  statement: string;
  symbols: { symbol: string; meaning: string }[];
};

type TagFile = {
  chapter: string;
  chapterName: string;
  scope: { exams: string[]; visibility: string; format: string };
  classifiedOn: string;
  questions: number;
  tags: Record<string, string[]>;
};

const ROOT = process.cwd();
const TAGS_DIR = path.join(ROOT, "scripts", "formula", "tags");
const META_DIR = path.join(ROOT, "scripts", "formula", "meta");
const OUT_DIR = path.join(ROOT, "src", "lib", "formula");

function chaptersToBuild(): string[] {
  const arg = process.argv[2];
  if (arg) return [arg];
  return fs
    .readdirSync(TAGS_DIR)
    .filter((f) => f.endsWith(".json"))
    .map((f) => f.replace(/\.json$/, ""));
}

async function build(chapter: string) {
  const tagPath = path.join(TAGS_DIR, `${chapter}.json`);
  if (!fs.existsSync(tagPath)) throw new Error(`no tags file: ${tagPath}`);
  const file: TagFile = JSON.parse(fs.readFileSync(tagPath, "utf8"));

  const metaPath = path.join(META_DIR, `${chapter}.ts`);
  if (!fs.existsSync(metaPath)) throw new Error(`no meta file: ${metaPath}`);
  const { META } = (await import(`file://${metaPath.replace(/\\/g, "/")}`)) as {
    META: Record<string, TopicMeta>;
  };

  // Invert question -> slugs into slug -> questions, preserving the tag file's
  // (sorted) question order so the generated module is stable across runs.
  const bySlug = new Map<string, string[]>();
  for (const [qid, slugs] of Object.entries(file.tags)) {
    for (const s of slugs) {
      const arr = bySlug.get(s) ?? [];
      arr.push(qid);
      bySlug.set(s, arr);
    }
  }

  const unknown = Object.keys(META).filter((s) => !bySlug.has(s));
  if (unknown.length)
    throw new Error(
      `META names slugs absent from the tags — a rename or a typo: ${unknown.join(", ")}`
    );

  const published = [...bySlug.entries()]
    .filter(([slug, ids]) => META[slug] && ids.length >= MIN_QUESTIONS)
    .sort((a, b) => b[1].length - a[1].length);

  const withheldButAuthored = [...bySlug.entries()]
    .filter(([slug, ids]) => META[slug] && ids.length < MIN_QUESTIONS)
    .map(([slug, ids]) => `${slug} (${ids.length})`);
  const overFloorNoMeta = [...bySlug.entries()]
    .filter(([slug, ids]) => !META[slug] && ids.length >= MIN_QUESTIONS)
    .map(([slug, ids]) => `${slug} (${ids.length})`);

  const body = published
    .map(([slug, ids]) => {
      const m = META[slug];
      const syms = m.symbols
        .map(
          (s) =>
            `      { symbol: ${JSON.stringify(s.symbol)}, meaning: ${JSON.stringify(s.meaning)} },`
        )
        .join("\n");
      const idLines = ids.map((id) => `      ${JSON.stringify(id)},`).join("\n");
      return `  {
    slug: ${JSON.stringify(slug)},
    kind: ${JSON.stringify(m.kind)},
    name: ${JSON.stringify(m.name)},
    latex: ${JSON.stringify(m.latex)},
    statement: ${JSON.stringify(m.statement)},
    symbols: [
${syms}
    ],
    questionIds: [
${idLines}
    ],
  },`;
    })
    .join("\n");

  const covered = new Set(published.flatMap(([, ids]) => ids)).size;
  const constName = chapter.toUpperCase().replace(/-/g, "_");

  const out = `/**
 * ${file.chapterName} — the formulas, properties and techniques the bank's
 * SOLUTIONS actually use, with the questions that use each one.
 *
 * GENERATED by \`npm run formula:generate\`. Do not hand-edit: change
 * scripts/formula/tags/${chapter}.json (membership) or
 * scripts/formula/meta/${chapter}.ts (wording) and re-run.
 *
 * Provenance: all ${file.questions} MCQs in this chapter (${file.scope.exams.join(", ")};
 * ${file.scope.visibility}; ${file.scope.format.toUpperCase()} only) were READ ONE BY ONE on ${file.classifiedOn} and
 * tagged with the identities their solution invokes. That was not a preference
 * for manual work: a signature classifier scored against these same labels
 * reached 59.2% precision and 45.0% recall, and just one of ${bySlug.size} slugs cleared a
 * 90%/85% bar. Naming an operator is not using an identity, and an identity is
 * routinely used without being written down.
 *
 * ${published.length} of ${bySlug.size} identities are published; the rest fall below the
 * ${MIN_QUESTIONS}-question floor and are withheld rather than shipped as thin pages.
 */
import type { FormulaTopic } from "./types";

export const ${constName}: readonly FormulaTopic[] = [
${body}
];
`;

  fs.writeFileSync(path.join(OUT_DIR, `${chapter}.ts`), out);
  console.log(`${chapter}: ${published.length} topics, ${covered} of ${file.questions} questions`);
  if (overFloorNoMeta.length)
    console.log(`  NOT published (>= floor but no authored metadata): ${overFloorNoMeta.join(", ")}`);
  if (withheldButAuthored.length)
    console.log(`  authored but below the floor: ${withheldButAuthored.join(", ")}`);
}

async function main() {
  for (const c of chaptersToBuild()) await build(c);
  console.log(`\nremember: a NEW chapter also needs an entry in src/lib/formula/index.ts`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
