/**
 * Content for /guide/cds-maths/strategy. GENERATED by generated-papers/_cds_strategy_gen.py from the
 * bank's own subtopic lists; every hand-named subtopic was checked against the bank before writing.
 *
 * THE ONE FACT THAT SHAPES THIS FILE: CDS deducts ONE THIRD of a mark for a wrong answer. So the axis
 * is ATTEMPT versus LEAVE, as in every NDA guide and unlike MHT-CET. A blind guess on four options is
 * worth exactly 0 on average (1/4 x 1 - 3/4 x 1/3); remove one option and it is worth +1/9; remove
 * two and it is worth +1/3. That is the whole guessing rule — see GUESS_RULE.
 *
 * Tiers use LIFETIME weight (21 papers) and %HARD. The four strands plus the tail reconcile to 2,096
 * exactly (969 + 460 + 585 + 82). `mustDrill` / `skipSubtopics` / `targetHard` hold canonical DB
 * subtopic names, resolved to UUIDs at request time for /browse drill links; a typo produces an empty
 * drill and no error, which is why they are generated, and tests/guide-cds-maths-playbooks.test.ts
 * resolves every one against the live taxonomy.
 */

import type { Difficulty } from "@/lib/questions/filters";

/** How to attack a chapter on a paper that deducts a third of a mark for a wrong answer. */
export type DrillPosture =
  /** Cheap: every question is one to attempt, and a guess after removing one option is worth making. */
  | "attempt-all"
  /** HARD spread across the subtopics: own the whole chapter in prep, attempt what you can solve. */
  | "own-outright"
  /** HARD pooled in one or two pages: bank the cheap pages first; attempt the pool only on a clean solve. */
  | "split-pass";

export type StrandChapter = {
  chapter: string;
  qCount: number;
  pctHard: number;
  posture: DrillPosture;
  /** Subtopics to drill, in prep order (cheapest first where the chapter cherry-picks). */
  mustDrill: string[];
  /** The HARD pool: last in prep, and on the paper attempted only on a clean solve. */
  skipSubtopics?: string[];
  /** Subtopics whose HARD load deserves extra timed reps. */
  targetHard?: string[];
  expectedYieldPerPaper: string;
  studyHours: number;
  summary: string;
};

export type StrandId = "cornerstone" | "quickwin" | "selective";

export type StrategyStrand = {
  id: StrandId;
  label: string;
  qCount: number;
  pctOfBank: number;
  pitch: string;
  approach: string[];
  chapters: StrandChapter[];
};

/**
 * 100 q x 1 mark = 100 marks in 120 minutes, a third of a mark lost per wrong answer.
 * Target: 90 attempts at 80% accuracy is 72 right and 18 wrong, 72 - 6 = 66 marks.
 */
export const STRATEGY_HEADLINE = {
  paperQ: 100,
  totalMarks: 100,
  marksPerCorrect: 1,
  penaltyPerWrong: 0.333,
  targetMarks: 66,
  targetAttempts: 90,
  targetAccuracyPct: 80,
  durationMin: 120,
  minutesPerQuestion: 1.2,
};

/** Expected marks from one guess, by how many options are still in play (penalty 1/3). */
export const GUESS_RULE: { optionsLeft: number; expected: string; verdict: string }[] = [
  { optionsLeft: 4, expected: "0", verdict: "A blind guess gains nothing on average and adds risk. Leave it." },
  { optionsLeft: 3, expected: "+1/9 of a mark", verdict: "Worth it: one option ruled out makes the guess pay." },
  { optionsLeft: 2, expected: "+1/3 of a mark", verdict: "Clearly worth it." },
];

export const CORNERSTONE_STRAND: StrategyStrand = {
  id: "cornerstone",
  label: "Cornerstone — Trigonometric Ratios and Identities · Number System · Mensuration 2D · Mensuration 3D · Triangles (969 q · 46% of bank)",
  qCount: 969,
  pctOfBank: 46,
  pitch:
    "Five chapters carry 46.1 questions a paper — nearly half of a 100-question paper. Trigonometry and Number System have each risen to 13 a paper on 2024-2026 papers. No score is possible without these five, and four of them cherry-pick: the HARD sits in one or two pages you can leave for last.",
  approach: ["Do these five first in prep, and in this order of return: Trigonometry and Number System (13 a paper each recently), then the two mensurations, then Triangles.", "All five have teaching notes at /notes/cds-maths. Read a chapter's notes once, then drill subtopic by subtopic.", "Four of the five cherry-pick. In Trigonometry, maximum/minimum and eliminating θ hold 29 of 46 HARD questions; in Mensuration 2D, touching circles and shaded regions are where wrong answers come from. Bank the cheap pages before the pools.", "Number System does not cherry-pick: its HARD is spread across remainders, factorisation and HCF laws. Own the whole chapter."],
  chapters: [
    {
      chapter: "Trigonometric Ratios and Identities",
      qCount: 227,
      pctHard: 20,
      posture: "split-pass",
      mustDrill: ["Power Identities and Given Sums", "Degree, Radian and Standard Values", "Reciprocal Pairs — sec ± tan and cosec ± cot", "Complementary and Allied Angles", "Simplifying and Proving Identities", "Compound and Multiple Angles", "Trigonometric Equations", "Ratios in a Right Triangle", "Maximum, Minimum and Impossible Values", "Eliminating θ and Substitution Chains"],
      skipSubtopics: ["Maximum, Minimum and Impossible Values", "Eliminating θ and Substitution Chains"],
      targetHard: ["Maximum, Minimum and Impossible Values"],
      expectedYieldPerPaper: "10.81 q/paper · about 11 marks",
      studyHours: 16,
      summary:
        "227 q · 20% HARD · 13 a paper on 2024-2026 papers, up from 8.8. Eight of its ten subtopics are cheap; maximum/minimum (37 q, 35% HARD) and eliminating θ (34 q, 47%) hold 29 of its 46 HARD questions. Bank the eight first, then take the two pools with timed reps.",
    },
    {
      chapter: "Number System",
      qCount: 223,
      pctHard: 16,
      posture: "own-outright",
      mustDrill: ["Division, Parity and Consecutive Integers", "Place Value and Digit Problems", "Divisibility Rules and Missing Digits", "Unit Digit and Cyclicity", "Prime Numbers and Primality", "Factors, Divisor Counting and Trailing Zeros", "HCF and LCM Laws and Fractions", "HCF and LCM Applications and Remainder Recipes", "Remainders by Congruence and Cyclicity", "Divisibility by Factorisation", "Perfect Squares, Cubes and Difference of Squares", "Rational and Irrational Numbers"],
      targetHard: ["Divisibility by Factorisation", "Remainders by Congruence and Cyclicity"],
      expectedYieldPerPaper: "10.62 q/paper · about 11 marks",
      studyHours: 16,
      summary:
        "223 q · 16% HARD · 13 a paper recently, up from 9.8. The HARD is spread across remainders, factorisation, HCF laws and division rather than pooled, so there is no page to leave out; primes, HCF/LCM applications and irrationals have never set a HARD question.",
    },
    {
      chapter: "Mensuration 2D",
      qCount: 197,
      pctHard: 23,
      posture: "split-pass",
      mustDrill: ["Arcs, Sectors and Segments", "Circumference, Wheels and Rings", "Equal Perimeters and Re-bent Wires", "Areas of Triangles", "Rectangles, Squares and Other Quadrilaterals", "Inscribed and Circumscribed Figures", "Combined and Shaded Regions", "Touching Circles"],
      skipSubtopics: ["Touching Circles", "Combined and Shaded Regions"],
      targetHard: ["Inscribed and Circumscribed Figures"],
      expectedYieldPerPaper: "9.38 q/paper · about 9 marks",
      studyHours: 14,
      summary:
        "197 q · 23% HARD · about 9.4 a paper. Wheels, arcs and re-bent wires are nearly free; touching circles (62% HARD) and shaded regions (40%) are where the wrong answers come from. Attempt those two only on a clean solve.",
    },
    {
      chapter: "Mensuration 3D",
      qCount: 171,
      pctHard: 17,
      posture: "split-pass",
      mustDrill: ["Cubes and Cuboids", "Water — Immersion, Flow and Rainfall", "Frustums and Combined Solids", "Spheres, Hemispheres and Shells", "Melting and Recasting", "Cylinders", "Cones", "Diagonals and Cuboid Identities", "Scaling and Comparing Solids", "Solids Inside Solids"],
      skipSubtopics: ["Solids Inside Solids"],
      targetHard: ["Scaling and Comparing Solids"],
      expectedYieldPerPaper: "8.14 q/paper · about 8 marks",
      studyHours: 12,
      summary:
        "171 q · 17% HARD · falling from 8.1 to 6.7 a paper. Eight of ten subtopics are under 20% HARD; solids inside solids (53%) is the one page to attempt only when the set-up is clear.",
    },
    {
      chapter: "Triangles",
      qCount: 151,
      pctHard: 20,
      posture: "split-pass",
      mustDrill: ["The Altitude to the Hypotenuse", "Parallels, Midpoints and the Bisector Theorem", "Angles of a Triangle", "Ratio of Areas of Triangles", "Pythagoras Theorem and its Converse", "Congruence and Similarity", "Centres of a Triangle", "Medians and Apollonius Theorem", "Triangle Inequalities", "Sine and Cosine Rules"],
      skipSubtopics: ["Triangle Inequalities", "Sine and Cosine Rules"],
      targetHard: ["Medians and Apollonius Theorem", "Centres of a Triangle"],
      expectedYieldPerPaper: "7.19 q/paper · about 7 marks",
      studyHours: 12,
      summary:
        "151 q · 20% HARD · about seven a paper. The altitude to the hypotenuse is 27 questions with no HARD at all; triangle inequalities and the sine and cosine rules are half HARD but only 16 questions between them.",
    },
  ],
};

export const QUICKWIN_STRAND: StrategyStrand = {
  id: "quickwin",
  label: "Quick-Win — Statistics · Ratio, Proportion and Variation · Time, Speed and Distance · Percentage, Profit and Loss · Data Interpretation · Averages · Time and Work · Simple and Compound Interest (460 q · 22% of bank)",
  qCount: 460,
  pctOfBank: 22,
  pitch:
    "Eight arithmetic and data chapters carry 21.9 questions a paper at 2-15% HARD. This is where a steady candidate makes the difference: almost every question here is one you should attempt and get right.",
  approach: ["Drill these for speed as much as accuracy — at 1.2 minutes a question, the time you save here pays for the cornerstone pools.", "Every chapter here has at least one subtopic that has never set a HARD question. The only real risk is a careless base: the percentage of the wrong number, the average of the averages.", "Statistics is rising (3.8 to 5.0 a paper); Data Interpretation and Time and Work are falling. Weight your hours accordingly, but do not skip any of the eight."],
  chapters: [
    {
      chapter: "Statistics",
      qCount: 80,
      pctHard: 8,
      posture: "attempt-all",
      mustDrill: ["Data, Scales and Presentation", "Frequency Tables and Cumulative Frequency", "Properties of the Arithmetic Mean", "Median of Ungrouped Data", "Mean, Median and Mode of Grouped Data", "Choosing a Measure of Central Tendency"],
      expectedYieldPerPaper: "3.81 q/paper · about 4 marks",
      studyHours: 5,
      summary:
        "80 q · 8% HARD · rising from 3.8 to 5.0 a paper. The cheapest chapter of any size: four of its six subtopics have never set a HARD question. Every question here is one to attempt.",
    },
    {
      chapter: "Ratio, Proportion and Variation",
      qCount: 76,
      pctHard: 9,
      posture: "attempt-all",
      mustDrill: ["Ratio and Proportion", "Ratios in Income, Savings and Ages", "Equal Ratios and Proportion Algebra", "Direct and Inverse Variation", "Partnership", "Mixtures and Alligation"],
      expectedYieldPerPaper: "3.62 q/paper · about 4 marks",
      studyHours: 5,
      summary:
        "76 q · 9% HARD · about 3.6 a paper. Ratio and proportion and variation have no HARD at all; partnership and mixtures carry the little there is.",
    },
    {
      chapter: "Time, Speed and Distance",
      qCount: 75,
      pctHard: 13,
      posture: "attempt-all",
      mustDrill: ["Average Speed and Speed–Time Ratios", "Speed Changes and Equations", "Relative Speed: Chasing and Meeting", "Trains and Relative Speed", "Boats and Streams", "Races", "Clocks and Angles"],
      expectedYieldPerPaper: "3.57 q/paper · about 4 marks",
      studyHours: 5,
      summary:
        "75 q · 13% HARD · about 3.5 a paper. Average speed is 22 questions at 5%; races and speed changes are the only pages with any real cost.",
    },
    {
      chapter: "Percentage, Profit and Loss",
      qCount: 50,
      pctHard: 6,
      posture: "attempt-all",
      mustDrill: ["Percentage", "Successive Percentage Change", "Profit and Loss", "Successive Discount and Marked Price"],
      expectedYieldPerPaper: "2.38 q/paper · about 2 marks",
      studyHours: 3,
      summary:
        "50 q · 6% HARD · about 2.4 a paper — three HARD questions in the whole chapter. The only way to lose a mark is the wrong base.",
    },
    {
      chapter: "Data Interpretation",
      qCount: 52,
      pctHard: 2,
      posture: "attempt-all",
      mustDrill: ["Tables", "Pie Charts", "Bar and Line Graphs", "Caselet Data Interpretation"],
      expectedYieldPerPaper: "2.48 q/paper · about 2 marks",
      studyHours: 3,
      summary:
        "52 q · 2% HARD · falling from 2.6 to 1.7 a paper. One HARD question in 52: the work is reading a table or chart carefully and dividing by the right total.",
    },
    {
      chapter: "Averages",
      qCount: 47,
      pctHard: 9,
      posture: "attempt-all",
      mustDrill: ["Sum and Mean", "Weighted and Combined Averages", "Averages of Consecutive Numbers"],
      expectedYieldPerPaper: "2.24 q/paper · about 2 marks",
      studyHours: 3,
      summary:
        "47 q · 9% HARD · about two a paper. Every question is a total divided by a count, or a weighted mean.",
    },
    {
      chapter: "Time and Work",
      qCount: 46,
      pctHard: 7,
      posture: "attempt-all",
      mustDrill: ["Work Rates", "Man-Days and Man-Hours", "Men, Women and Equivalent Workers", "Pipes and Cisterns"],
      expectedYieldPerPaper: "2.19 q/paper · about 2 marks",
      studyHours: 3,
      summary:
        "46 q · 7% HARD · falling from 2.7 to 1.3 a paper. Work in rates or man-days, never in days directly, and the chapter is free marks.",
    },
    {
      chapter: "Simple and Compound Interest",
      qCount: 34,
      pctHard: 15,
      posture: "attempt-all",
      mustDrill: ["Simple Interest", "Compound Interest", "Instalments and Difference of SI and CI"],
      expectedYieldPerPaper: "1.62 q/paper · about 2 marks",
      studyHours: 3,
      summary:
        "34 q · 15% HARD · about two a paper recently. Simple interest is nearly free; compound interest holds most of the HARD.",
    },
  ],
};

export const SELECTIVE_STRAND: StrategyStrand = {
  id: "selective",
  label: "Selective — Algebraic Identities and Simplification · Quadratic Equations · Surds, Indices and Simplification · Polynomials · Circles · Quadrilaterals · Heights and Distances · Logarithms · Linear Equations (585 q · 28% of bank)",
  qCount: 585,
  pctOfBank: 28,
  pitch:
    "Nine chapters of algebra and the remaining geometry carry 27.9 questions a paper at 19-39% HARD. Here the one-third penalty decides the score: attempt what you can solve cleanly, and leave the rest rather than guess blind.",
  approach: ["Algebraic Identities is the hardest chapter in the bank (39% HARD) but cherry-picks: its conditional and symmetric pages are the pool.", "Heights and Distances (34%) and Logarithms (24%) each have one expensive page and one or two cheap ones — bank the cheap ones.", "Linear Equations has faded to one question in six papers; keep it for the word-problem fluency the arithmetic chapters use, not for its own weight."],
  chapters: [
    {
      chapter: "Algebraic Identities and Simplification",
      qCount: 98,
      pctHard: 39,
      posture: "split-pass",
      mustDrill: ["Sums and Products of Three Variables", "The Cube Identity and a + b + c = 0", "Squares and Cubes of a Binomial", "Reciprocal Sums x ± 1/x", "Rational Algebraic Expressions", "Sums of Squares and Least Values", "Conditional Identities", "Symmetric and Cyclic Expressions"],
      skipSubtopics: ["Conditional Identities", "Symmetric and Cyclic Expressions"],
      targetHard: ["Rational Algebraic Expressions"],
      expectedYieldPerPaper: "4.67 q/paper · about 5 marks",
      studyHours: 8,
      summary:
        "98 q · 39% HARD · the hardest chapter in the bank, about 4.7 a paper. It cherry-picks: conditional identities (69% HARD) and symmetric expressions (6 of 6 HARD) are the pool; three-variable sums and the cube identity are cheap.",
    },
    {
      chapter: "Quadratic Equations",
      qCount: 89,
      pctHard: 24,
      posture: "own-outright",
      mustDrill: ["Solving and Forming Quadratic Equations", "Symmetric Functions of the Roots", "Roots in a Given Relation", "Nature of Roots and Discriminant", "Perfect Squares, Signs and Location of Roots", "Common Roots", "Maximum and Minimum of Quadratic Expressions", "Equations Reducible to Quadratics", "Word Problems and Applications"],
      targetHard: ["Perfect Squares, Signs and Location of Roots"],
      expectedYieldPerPaper: "4.24 q/paper · about 4 marks",
      studyHours: 6,
      summary:
        "89 q · 24% HARD · about 4.2 a paper, the HARD spread thinly across nine subtopics. Common roots, maximum/minimum and word problems have never set a HARD question.",
    },
    {
      chapter: "Surds, Indices and Simplification",
      qCount: 82,
      pctHard: 22,
      posture: "split-pass",
      mustDrill: ["Fractions and Decimals", "Exponential Equations", "Square Roots of Surds", "Continued Fractions and Nested Radicals", "Laws of Indices", "Surds and Rationalisation", "Simplification of Expressions", "Equations with Surds"],
      skipSubtopics: ["Equations with Surds"],
      expectedYieldPerPaper: "3.90 q/paper · about 4 marks",
      studyHours: 5,
      summary:
        "82 q · 22% HARD · falling from 4.6 to 3.0 a paper. Equations with surds are 71% HARD; fractions, exponential equations and square roots of surds are almost free.",
    },
    {
      chapter: "Polynomials",
      qCount: 79,
      pctHard: 19,
      posture: "own-outright",
      mustDrill: ["Degree, Zeros and Coefficients", "The Remainder Theorem", "The Factor Theorem", "Factorisation of Polynomials", "HCF and LCM of Polynomials"],
      targetHard: ["HCF and LCM of Polynomials"],
      expectedYieldPerPaper: "3.76 q/paper · about 4 marks",
      studyHours: 5,
      summary:
        "79 q · 19% HARD · about 3.8 a paper. The factor theorem has never set a HARD question; HCF and LCM of polynomials is the largest page and holds the most HARD.",
    },
    {
      chapter: "Circles",
      qCount: 69,
      pctHard: 26,
      posture: "own-outright",
      mustDrill: ["Chords and Perpendiculars", "Angles in a Circle", "Circumcircle and Locus", "Tangents from an External Point", "Intersecting Chords and Power of a Point", "Common Tangents and Common Chords", "Touching Circles"],
      targetHard: ["Circumcircle and Locus", "Chords and Perpendiculars"],
      expectedYieldPerPaper: "3.29 q/paper · about 3 marks",
      studyHours: 5,
      summary:
        "69 q · 26% HARD · about 3.3 a paper. Tangents from an external point have never set a HARD question; the HARD is spread over the chord, circumcircle and touching-circle pages.",
    },
    {
      chapter: "Quadrilaterals",
      qCount: 54,
      pctHard: 20,
      posture: "own-outright",
      mustDrill: ["General Quadrilaterals and their Diagonals", "Parallelograms", "Rhombus and Kite", "Trapeziums", "Cyclic Quadrilaterals"],
      targetHard: ["General Quadrilaterals and their Diagonals"],
      expectedYieldPerPaper: "2.57 q/paper · about 3 marks",
      studyHours: 4,
      summary:
        "54 q · 20% HARD · rising from 2.4 to 3.7 a paper. Rhombus and kite has no HARD; the general-quadrilateral page is the expensive one at 36%.",
    },
    {
      chapter: "Heights and Distances",
      qCount: 41,
      pctHard: 34,
      posture: "split-pass",
      mustDrill: ["One Line of Sight", "Two Points of Observation", "Observer Above the Ground", "Towers on Plane Figures and Bearings"],
      skipSubtopics: ["Towers on Plane Figures and Bearings"],
      targetHard: ["Observer Above the Ground"],
      expectedYieldPerPaper: "1.95 q/paper · about 2 marks",
      studyHours: 4,
      summary:
        "41 q · 34% HARD · about two a paper. Towers on plane figures is 5 of 7 HARD; one line of sight and two points of observation are the pages to bank.",
    },
    {
      chapter: "Logarithms",
      qCount: 33,
      pctHard: 24,
      posture: "split-pass",
      mustDrill: ["Number of Digits and Characteristic", "Logarithm Identities and Change of Base", "Solving Logarithmic Equations"],
      skipSubtopics: ["Solving Logarithmic Equations"],
      expectedYieldPerPaper: "1.57 q/paper · about 2 marks",
      studyHours: 3,
      summary:
        "33 q · 24% HARD · about 1.6 a paper. The equations page holds 5 of the 8 HARD; the laws and digit counting are cheap.",
    },
    {
      chapter: "Linear Equations",
      qCount: 40,
      pctHard: 20,
      posture: "own-outright",
      mustDrill: ["Solving Linear Systems", "Word Problems and Applications", "Age Problems", "Integral Solutions and Diophantine Equations"],
      expectedYieldPerPaper: "1.90 q/paper · about 2 marks",
      studyHours: 3,
      summary:
        "40 q · 20% HARD · fading: 2.7 a paper in 2016-2020, one question in the six 2024-2026 papers. Learn it for word-problem fluency, which the arithmetic chapters use, not for its own weight.",
    },
  ],
};

export const STRATEGY_STRANDS: StrategyStrand[] = [CORNERSTONE_STRAND, QUICKWIN_STRAND, SELECTIVE_STRAND];

export type TailChapter = { chapter: string; qCount: number; qPerPaper: number; pctHard: number; note: string };

/** The four chapters below 1.5 q/paper: no playbook, listed so the 26-chapter bank is accounted for. */
export const TAIL_CHAPTERS: TailChapter[] = [
  { chapter: "Sets", qCount: 28, qPerPaper: 1.33, pctHard: 14, note: "1.3 a paper, falling from 1.9 to 0.8. Mostly Venn-diagram counting at 14% HARD — worth a short drill with the quick-wins." },
  { chapter: "Lines, Angles and Polygons", qCount: 22, qPerPaper: 1.05, pctHard: 0, note: "1.05 a paper, falling from 1.8 to 0.8, and the only chapter with no HARD question. Revise the angle-sum rules once; they are free when they appear." },
  { chapter: "Sequence and Series", qCount: 19, qPerPaper: 0.9, pctHard: 11, note: "19 questions in 21 papers at 11% HARD. Know the AP and GP sums and the three means so a question is recognisable." },
  { chapter: "Inequalities", qCount: 13, qPerPaper: 0.62, pctHard: 15, note: "13 questions in 21 papers, mostly data-sufficiency items on signs. Read the notes once." },
];

export const DIFFICULTIES_EASY_MOD: Difficulty[] = ["EASY", "MODERATE"];
