import type { SubtopicNote } from "@/app/notes/_types";

export const STRAIGHT_LINE_3D_NOTE: SubtopicNote = {
  subtopicName: "The Straight Line in 3D",
  title: "The Straight Line in Space",
  oneLineDefinition:
    "A line is a point plus a direction; everything — points on it, where it pierces a plane, whether it's parallel to one — follows from its parametric form.",
  whyItMatters:
    "Eleven PYQs, almost all EASY or MODERATE — the most reliably scorable subtopic in the " +
    "chapter once you commit to parametrising. The bank repeats four moves: write the line, " +
    "generate a point on it, find where it meets a coordinate plane or a given plane, and test " +
    "whether it is parallel to (or lies in) a plane. Master the parametric form and the rest are " +
    "substitutions.",
  concepts: [
    // C1 — line equation forms
    {
      kind: "formula" as const,
      slug: "line-equation-forms",
      name: "Equation of a line — symmetric and two-point forms",
      intuition:
        "A line is pinned down by one point on it and one direction. Symmetric form stacks the three " +
        "coordinate equations into one chain; two-point form builds the direction from the difference " +
        "of the points. A line in space is also the intersection of two planes — which is why a single " +
        "symmetric line can be written as a pair of plane equations.",
      definition:
        "Through point \\((x_0,y_0,z_0)\\) with direction ratios \\(\\langle a,b,c\\rangle\\), the " +
        "**symmetric form** is \\(\\frac{x-x_0}{a} = \\frac{y-y_0}{b} = \\frac{z-z_0}{c}\\). Through two " +
        "points \\(A, B\\), the direction ratios are \\(\\langle x_2-x_1, y_2-y_1, z_2-z_1\\rangle\\). " +
        "Setting the chain equal to a parameter \\(t\\) gives the **parametric form** " +
        "\\((x_0+at,\\ y_0+bt,\\ z_0+ct)\\). Splitting the chain into two equalities expresses the line " +
        "as the **intersection of two planes**.",
      formula: {
        label: "Symmetric form of a line",
        latex: "\\frac{x - x_0}{a} = \\frac{y - y_0}{b} = \\frac{z - z_0}{c} = t",
      },
      authoredExample: {
        prompt: "Write the line through \\(A(1, 2, -1)\\) and \\(B(3, -1, 2)\\) in symmetric form.",
        steps: [
          "Direction ratios \\(= B - A = \\langle 3-1,\\ -1-2,\\ 2-(-1)\\rangle = \\langle 2, -3, 3\\rangle\\).",
          "Use point \\(A(1,2,-1)\\) and these ratios.",
          "Symmetric form: \\(\\frac{x-1}{2} = \\frac{y-2}{-3} = \\frac{z+1}{3}\\).",
        ],
        answer: "\\(\\dfrac{x-1}{2} = \\dfrac{y-2}{-3} = \\dfrac{z+1}{3}\\).",
      },
      selfCheckExample: {
        prompt:
          "Express the line \\(\\frac{x-1}{2} = \\frac{y-2}{3} = \\frac{z-3}{4}\\) as the intersection of two planes.",
        steps: [
          "Take two of the three equalities.",
          "First pair: \\(\\frac{x-1}{2} = \\frac{y-2}{3} \\Rightarrow 3(x-1) = 2(y-2) \\Rightarrow 3x - 2y + 1 = 0\\).",
          "Second pair: \\(\\frac{y-2}{3} = \\frac{z-3}{4} \\Rightarrow 4(y-2) = 3(z-3) \\Rightarrow 4y - 3z + 1 = 0\\).",
        ],
        answer: "\\(3x - 2y + 1 = 0\\) and \\(4y - 3z + 1 = 0\\) (any valid pair works).",
      },
      practiceSet: [
        { prompt: "DRs of the line through \\((0,0,0)\\) and \\((2,3,4)\\)?", answer: "\\(\\langle 2,3,4\\rangle\\)" },
        { prompt: "Parametric point of \\(\\frac{x-1}{2}=\\frac{y}{3}=\\frac{z+1}{4}=t\\)?", answer: "\\((1+2t, 3t, -1+4t)\\)" },
        { prompt: "A line in space is the intersection of how many planes?", answer: "Two" },
        { prompt: "Symmetric form needs how many things to be fixed?", answer: "A point and a direction" },
      ],
      pyqExampleId: "35ad3726-324a-4889-bffa-585d76c0aa5a", // 2018 — line given as intersection of planes
    },

    // C2 — point on a line
    {
      kind: "formula" as const,
      slug: "point-on-a-line",
      name: "Points on a line",
      intuition:
        "Every point on a line is the base point pushed along the direction by some amount \\(t\\). " +
        "Plug a value of \\(t\\) and you get a point; or set the parametric coordinates equal to a " +
        "candidate point and check they share a single \\(t\\).",
      definition:
        "Points on \\((x_0+at,\\ y_0+bt,\\ z_0+ct)\\) are generated by choosing \\(t\\). To test whether " +
        "\\((p,q,r)\\) lies on the line, solve \\(p = x_0+at\\) for \\(t\\) and confirm the SAME \\(t\\) " +
        "reproduces \\(q\\) and \\(r\\).",
      authoredExample: {
        prompt:
          "Find a point on the line \\(\\frac{x-1}{1} = \\frac{y-3}{2} = \\frac{z+2}{7}\\) other than \\((1,3,-2)\\).",
        steps: [
          "Set the chain equal to \\(t\\): point \\(= (1+t,\\ 3+2t,\\ -2+7t)\\).",
          "Take \\(t = 1\\): \\((2, 5, 5)\\).",
          "Check: \\(\\frac{2-1}{1} = 1,\\ \\frac{5-3}{2} = 1,\\ \\frac{5+2}{7} = 1\\) — all equal. ✓",
        ],
        answer: "\\((2, 5, 5)\\) (any \\(t \\neq 0\\) works).",
      },
      selfCheckExample: {
        prompt:
          "A point \\(P\\) lies on the line joining \\(A(1,2,3)\\) and \\(B(2,10,1)\\). If \\(P\\)'s z-coordinate is 7, find the sum of its other two coordinates.",
        steps: [
          "Direction \\(= B - A = \\langle 1, 8, -2\\rangle\\). Point \\(= (1+t,\\ 2+8t,\\ 3-2t)\\).",
          "Set \\(z = 7\\): \\(3 - 2t = 7 \\Rightarrow t = -2\\).",
          "Then \\(x = 1 + (-2) = -1\\) and \\(y = 2 + 8(-2) = -14\\).",
          "Sum of x and y: \\(-1 + (-14) = -15\\).",
        ],
        answer: "\\(-15\\).",
      },
      practiceSet: [
        { prompt: "Point on \\((2+t, 1-t, 3t)\\) at \\(t=2\\)?", answer: "\\((4, -1, 6)\\)" },
        { prompt: "At what t does \\((1+2t, 3t, t)\\) hit \\(x=5\\)?", answer: "\\(t=2\\)" },
        { prompt: "Does \\((1,3,-2)\\) lie on \\(\\frac{x-1}{1}=\\frac{y-3}{2}=\\frac{z+2}{7}\\)?", answer: "Yes", method: "it's the base point, t=0" },
        { prompt: "How many points does a line have for varying t?", answer: "Infinitely many" },
      ],
      pyqExampleId: "b91d71b7-59ec-46c0-8de6-d02e0cb1d313", // 2019 — point on the line
    },

    // C3 — line meets coordinate plane
    {
      kind: "formula" as const,
      slug: "line-meets-coordinate-plane",
      name: "Where a line meets a coordinate plane",
      intuition:
        "To find where a line crosses the XY-plane, ask: at what \\(t\\) is \\(z = 0\\)? Solve for that " +
        "\\(t\\), substitute back, and read off the point. Same idea for the YZ-plane (\\(x=0\\)) and " +
        "ZX-plane (\\(y=0\\)).",
      definition:
        "A line meets the **XY-plane** where its \\(z\\)-coordinate is 0, the **YZ-plane** where \\(x=0\\), " +
        "and the **ZX-plane** where \\(y=0\\). Parametrise the line, set the relevant coordinate to 0, " +
        "solve for \\(t\\), and back-substitute.",
      visualizationSlug: "line-plane-intersection",
      authoredExample: {
        prompt:
          "Find where the line joining \\((-3, 4, -8)\\) and \\((5, -6, 4)\\) meets the XY-plane.",
        steps: [
          "Direction \\(= \\langle 8, -10, 12\\rangle\\). Point \\(= (-3+8t,\\ 4-10t,\\ -8+12t)\\).",
          "XY-plane: \\(z = 0 \\Rightarrow -8 + 12t = 0 \\Rightarrow t = \\tfrac{2}{3}\\).",
          "Then \\(x = -3 + 8(\\tfrac23) = -3 + \\tfrac{16}{3} = \\tfrac{7}{3}\\) and \\(y = 4 - 10(\\tfrac23) = 4 - \\tfrac{20}{3} = -\\tfrac{8}{3}\\).",
        ],
        answer: "\\(\\left( \\tfrac{7}{3}, -\\tfrac{8}{3}, 0 \\right)\\).",
      },
      selfCheckExample: {
        prompt:
          "Where does the line through \\((1, 2, -1)\\) and \\((3, -1, 2)\\) meet the YZ-plane?",
        steps: [
          "Direction \\(= \\langle 2, -3, 3\\rangle\\). Point \\(= (1+2t,\\ 2-3t,\\ -1+3t)\\).",
          "YZ-plane: \\(x = 0 \\Rightarrow 1 + 2t = 0 \\Rightarrow t = -\\tfrac12\\).",
          "Then \\(y = 2 - 3(-\\tfrac12) = \\tfrac72\\) and \\(z = -1 + 3(-\\tfrac12) = -\\tfrac52\\).",
        ],
        answer: "\\(\\left( 0, \\tfrac72, -\\tfrac52 \\right)\\).",
      },
      practiceSet: [
        { prompt: "Which coordinate is 0 on the XY-plane?", answer: "\\(z\\)" },
        { prompt: "Which coordinate is 0 on the YZ-plane?", answer: "\\(x\\)" },
        { prompt: "Line \\((t, 2t, t-3)\\) meets XY-plane at which t?", answer: "\\(t=3\\)", method: "set \\(z = t-3 = 0\\)" },
        { prompt: "Point where \\((t,2t,t-3)\\) meets XY-plane?", answer: "\\((3,6,0)\\)" },
      ],
      pyqExampleId: "bd259375-a6b0-48fa-936f-e99a3a23c211", // 2017 — line meets XY-plane
    },

    // C4 — line-plane intersection
    {
      kind: "formula" as const,
      slug: "line-plane-intersection",
      name: "Intersection of a line and a plane",
      intuition:
        "A line generally pierces a plane at one point. Plug the line's parametric coordinates into the " +
        "plane equation — that collapses to one equation in \\(t\\). Solve it, then feed \\(t\\) back to " +
        "get the pierce point.",
      definition:
        "For a line \\((x_0+at,\\ y_0+bt,\\ z_0+ct)\\) and plane \\(Ax+By+Cz = D\\), substitute to get a " +
        "linear equation in \\(t\\). One solution → a single pierce point. No solution (the \\(t\\) terms " +
        "cancel but the constants disagree) → the line is parallel and misses. Identity (all \\(t\\) work) " +
        "→ the line lies in the plane.",
      visualizationSlug: "line-plane-intersection",
      authoredExample: {
        prompt:
          "A line through \\((1, 0, -1)\\) with direction ratios \\(\\langle 1, 2, 1\\rangle\\) meets the plane \\(x + y + z = 8\\). Find the point of intersection.",
        steps: [
          "Parametrise: \\((1+t,\\ 2t,\\ -1+t)\\).",
          "Substitute into the plane: \\((1+t) + 2t + (-1+t) = 8\\).",
          "\\(4t = 8 \\Rightarrow t = 2\\).",
          "Back-substitute \\(t = 2\\): \\((3, 4, 1)\\).",
        ],
        answer: "\\((3, 4, 1)\\).",
      },
      selfCheckExample: {
        prompt:
          "Where does the line \\((2t,\\ 1+t,\\ -t)\\) meet the plane \\(x + y + z = 6\\)?",
        steps: [
          "Substitute: \\(2t + (1+t) + (-t) = 6\\).",
          "\\(2t + 1 = 6 \\Rightarrow t = \\tfrac52\\).",
          "Point: \\((5,\\ 1+\\tfrac52,\\ -\\tfrac52) = (5, \\tfrac72, -\\tfrac52)\\).",
        ],
        answer: "\\(\\left(5, \\tfrac72, -\\tfrac52\\right)\\).",
      },
      practiceSet: [
        { prompt: "After substituting a line into a plane, the unknown left is?", answer: "the parameter \\(t\\)" },
        { prompt: "No valid t (constants clash) means the line is?", answer: "Parallel to the plane (misses it)" },
        { prompt: "Every t works means the line?", answer: "Lies in the plane" },
        { prompt: "Line \\((t,t,t)\\) meets \\(x+y+z=9\\) at which t?", answer: "\\(t=3\\)" },
      ],
      pyqExampleId: "7677bdc9-a50a-4223-a196-1818f24787d3", // 2024 — line meets plane
    },

    // C5 — line parallel to / lying in a plane
    {
      kind: "formula" as const,
      slug: "line-parallel-or-lying-in-plane",
      name: "Line parallel to, or lying in, a plane",
      intuition:
        "A line is parallel to a plane when its direction is perpendicular to the plane's normal — their " +
        "dot product is zero, so the line never tilts toward the plane. If, in addition, one point of the " +
        "line satisfies the plane equation, the whole line LIES in the plane.",
      definition:
        "For a line with direction \\(\\langle a,b,c\\rangle\\) and a plane with normal \\(\\langle A,B,C\\rangle\\):\n" +
        "- **Parallel** iff \\(Aa + Bb + Cc = 0\\) (direction ⟂ normal) AND a point of the line is NOT on the plane.\n" +
        "- **Lies in the plane** iff \\(Aa+Bb+Cc = 0\\) AND a point of the line satisfies the plane equation.",
      formula: {
        label: "Parallel/contained condition (direction ⟂ normal)",
        latex: "A a + B b + C c = 0",
      },
      authoredExample: {
        prompt:
          "If the line \\(\\frac{x-4}{1} = \\frac{y-2}{1} = \\frac{z-k}{2}\\) lies in the plane \\(2x - 4y + z = 7\\), find \\(k\\).",
        steps: [
          "Direction \\(\\langle 1,1,2\\rangle\\), normal \\(\\langle 2,-4,1\\rangle\\): dot \\(= 2 - 4 + 2 = 0\\) ✓ (so it can lie in the plane).",
          "Now the point \\((4, 2, k)\\) must satisfy the plane: \\(2(4) - 4(2) + k = 7\\).",
          "\\(8 - 8 + k = 7 \\Rightarrow k = 7\\).",
        ],
        answer: "\\(k = 7\\).",
      },
      selfCheckExample: {
        prompt:
          "Is the line with direction \\(\\langle 3, 4, 5\\rangle\\) parallel to the plane \\(2x - y - 2z + 1 = 0\\)?",
        steps: [
          "Plane normal: \\(\\langle 2, -1, -2\\rangle\\).",
          "Dot with direction: \\(3(2) + 4(-1) + 5(-2) = 6 - 4 - 10 = -8 \\neq 0\\).",
          "Non-zero → the line is NOT parallel; it pierces the plane.",
        ],
        answer: "No — the dot product is \\(-8 \\neq 0\\), so the line cuts the plane.",
      },
      practiceSet: [
        { prompt: "Line ∥ plane needs direction · normal = ?", answer: "\\(0\\)" },
        { prompt: "Direction \\(\\langle1,1,1\\rangle\\), normal \\(\\langle1,1,-2\\rangle\\): parallel?", answer: "Yes (dot 0)", method: "\\(1+1-2=0\\)" },
        { prompt: "Lies-in-plane needs the dot zero AND what else?", answer: "a point of the line on the plane" },
        { prompt: "Direction \\(\\langle2,0,1\\rangle\\), normal \\(\\langle1,5,-2\\rangle\\): parallel?", answer: "Yes (dot 0)", method: "\\(2+0-2=0\\)" },
      ],
      pyqExampleId: "d2c5dccb-f14e-480e-aa0e-0fb636f0a27b", // 2019 — line lies on plane, find k
      traps: [
        {
          title: "Parallel vs lying-in needs the second check",
          body:
            "Direction ⟂ normal (dot = 0) only means the line doesn't tilt toward the plane — it could be " +
            "strictly parallel (misses) OR contained (lies in). You MUST then test a point: on the plane → contained; off → parallel.",
        },
      ],
    },
  ],
};
