/**
 * NDA Maths · Matrices & Determinants · trap MCQs ("spot the common mistake").
 *   npm run quiz:verify nda-maths__matrices-determinants-traps
 */
import type { VerifiedEntry } from "./nda-maths__probability";

const t = (atomKey: string, stem: string, correct: string, distractors: string[]): VerifiedEntry => ({
  atomKey, stem, correct, distractors, theme: "trap",
});

export const VERIFIED: VerifiedEntry[] = [
  t("binomial-coefficient-determinants:trap:0",
    "What is the smartest first step on a determinant whose entries are binomial coefficients?",
    "Use Pascal's identity as a single column operation",
    ["Evaluate every binomial coefficient, then expand", "Take the transpose first", "Differentiate the determinant"]),
  t("det-products-scalar-powers:trap:0",
    "For a \\(3\\times3\\) matrix \\(A\\), \\(\\det(3A)\\) equals:",
    "\\(27\\det A\\)", ["\\(3\\det A\\)", "\\(9\\det A\\)", "\\(81\\det A\\)"]),
  t("det-products-scalar-powers:trap:1",
    "For the column vector \\(A = (1,2,3)^T\\), \\(\\det(I + AA^T)\\) equals:",
    "\\(15\\)", ["\\(14\\)", "\\(1\\)", "\\(36\\)"]),
  t("differentiating-a-determinant:trap:0",
    "Differentiating a \\(3\\times3\\) determinant whose entries are functions of \\(x\\) gives:",
    "A sum of 3 determinants, each with ONE row differentiated",
    ["One determinant with all three rows differentiated", "The determinant of the differentiated matrix", "Three times the original determinant"]),
  t("matrix-algebra-caveats:trap:0",
    "Which identity holds for ALL square matrices \\(A, B\\) of the same order?",
    "\\((A+B)^T = A^T + B^T\\)",
    ["\\((A+B)(A-B) = A^2 - B^2\\)", "\\((AB)^2 = A^2 B^2\\)", "\\((A+B)^2 = A^2 + 2AB + B^2\\)"]),
  t("matrix-algebra-caveats:trap:1",
    "For square matrices \\(A, B\\), the product \\(AB = O\\) (the zero matrix). Which conclusion is valid?",
    "Neither \\(A\\) nor \\(B\\) need be the zero matrix",
    ["\\(A = O\\) or \\(B = O\\)", "Both \\(A = O\\) and \\(B = O\\)", "\\(A = B\\)"]),
  t("matrix-multiplication:trap:0",
    "If \\(A = \\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}\\) and \\(B = \\begin{pmatrix}1&0\\\\1&1\\end{pmatrix}\\), find \\(AB\\).",
    "\\(\\begin{pmatrix}2&1\\\\1&1\\end{pmatrix}\\)",
    ["\\(\\begin{pmatrix}1&1\\\\1&2\\end{pmatrix}\\)", "\\(\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}\\)", "\\(\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}\\)"]),
  t("transpose-rules:trap:0",
    "If \\(A = \\begin{pmatrix}1&2\\\\3&4\\end{pmatrix}\\) and \\(B = \\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}\\), find \\((AB)^T\\).",
    "\\(\\begin{pmatrix}2&4\\\\1&3\\end{pmatrix}\\)",
    ["\\(\\begin{pmatrix}3&1\\\\4&2\\end{pmatrix}\\)", "\\(\\begin{pmatrix}2&1\\\\4&3\\end{pmatrix}\\)", "\\(\\begin{pmatrix}1&3\\\\2&4\\end{pmatrix}\\)"]),
  t("det-products-scalar-powers:trap:2",
    "Given \\(A = \\begin{pmatrix}1&2\\\\3&4\\end{pmatrix}\\) (with \\(\\det A = -2\\)) and \\(B = \\begin{pmatrix}2&0\\\\1&3\\end{pmatrix}\\) (with \\(\\det B = 6\\)), find \\(\\det(A+B)\\).",
    "\\(13\\)", ["\\(4\\)", "\\(-12\\)", "\\(8\\)"]),
  t("symmetric-and-skew-symmetric:trap:0",
    "\\(A\\) is a skew-symmetric matrix of order 3. What is \\(\\det A\\)?",
    "\\(0\\)", ["It cannot be determined without the entries", "\\(1\\)", "\\(\\pm 1\\)"]),
  t("adjoint-properties:trap:0",
    "For a \\(3\\times3\\) matrix \\(A\\) with \\(\\det A = 2\\), what is \\(|\\operatorname{adj}A|\\)?",
    "\\(4\\)", ["\\(2\\)", "\\(8\\)", "\\(16\\)"]),
  t("adjoint-properties:trap:1",
    "For non-singular matrices \\(A, B\\) of the same order, \\(\\operatorname{adj}(AB)\\) equals:",
    "\\(\\operatorname{adj}B\\,\\operatorname{adj}A\\)",
    ["\\(\\operatorname{adj}A\\,\\operatorname{adj}B\\)", "\\(\\operatorname{adj}A + \\operatorname{adj}B\\)", "\\(|A||B|\\,(AB)^{-1}\\)"]),
  t("inverse-properties:trap:0",
    "If \\(A = \\begin{pmatrix}1&2\\\\0&1\\end{pmatrix}\\) and \\(B = \\begin{pmatrix}1&0\\\\3&1\\end{pmatrix}\\), find \\((AB)^{-1}\\).",
    "\\(\\begin{pmatrix}1&-2\\\\-3&7\\end{pmatrix}\\)",
    ["\\(\\begin{pmatrix}7&-2\\\\-3&1\\end{pmatrix}\\)", "\\(\\begin{pmatrix}7&2\\\\3&1\\end{pmatrix}\\)", "\\(\\begin{pmatrix}1&2\\\\3&7\\end{pmatrix}\\)"]),
  t("inverse-properties:trap:1",
    "If \\(A = \\begin{pmatrix}1&2\\\\0&1\\end{pmatrix}\\), find \\((A^T)^{-1}\\).",
    "\\(\\begin{pmatrix}1&0\\\\-2&1\\end{pmatrix}\\)",
    ["\\(\\begin{pmatrix}1&-2\\\\0&1\\end{pmatrix}\\)", "\\(\\begin{pmatrix}1&2\\\\0&1\\end{pmatrix}\\)", "\\(\\begin{pmatrix}1&0\\\\2&1\\end{pmatrix}\\)"]),
];
