/**
 * NDA Maths · Vectors · trap MCQs ("spot the common mistake"). theme=trap.
 *   npm run quiz:verify nda-maths__vectors-traps
 */
import type { VerifiedEntry } from "./nda-maths__probability";

const t = (atomKey: string, stem: string, correct: string, distractors: string[]): VerifiedEntry => ({
  atomKey, stem, correct, distractors, theme: "trap",
});

export const VERIFIED: VerifiedEntry[] = [
  t("angle-via-dot-product-formula:trap:0", "The angle between two non-zero vectors is obtuse if and only if:",
    "their dot product is negative", ["their dot product is positive", "their dot product is zero", "their cross product is zero"]),
  t("angle-via-dot-product-formula:trap:1", "The angle between \\(\\vec{a}\\) and \\(\\vec{b}\\) is \\(60^\\circ\\). The angle between \\(\\vec{a}\\) and \\(-\\vec{b}\\) is:",
    "\\(120^\\circ\\)", ["\\(60^\\circ\\)", "\\(30^\\circ\\)", "\\(240^\\circ\\)"]),
  t("angles-and-vertices-from-position-vectors:trap:0", "To find the interior angle at vertex \\(C\\) of triangle \\(ABC\\), use the dot product of:",
    "\\(\\vec{CA}\\) and \\(\\vec{CB}\\) (both from \\(C\\))", ["\\(\\vec{AC}\\) and \\(\\vec{CB}\\)", "\\(\\vec{AB}\\) and \\(\\vec{BC}\\)", "\\(\\vec{CA}\\) and \\(\\vec{BC}\\)"]),
  t("angles-and-vertices-from-position-vectors:trap:1", "\\(ABCD\\) is a parallelogram. The position vector of the fourth vertex \\(D\\) is:",
    "\\(\\vec{a} + \\vec{c} - \\vec{b}\\)", ["\\(\\tfrac{\\vec{a}+\\vec{c}}{2}\\)", "\\(\\vec{a} + \\vec{b} - \\vec{c}\\)", "\\(\\vec{b} + \\vec{c} - \\vec{a}\\)"]),
  t("collinearity-and-vector-relations-in-figures:trap:0", "Three points are collinear if \\(\\alpha\\vec{a}+\\beta\\vec{b}+\\gamma\\vec{c}=\\vec{0}\\) (not all zero) AND:",
    "\\(\\alpha+\\beta+\\gamma=0\\)", ["\\(\\alpha+\\beta+\\gamma=1\\)", "\\(\\alpha=\\beta=\\gamma\\)", "\\(\\alpha\\beta\\gamma=0\\)"]),
  t("collinearity-and-vector-relations-in-figures:trap:1", "If \\((\\vec{a}\\times\\vec{b})+(\\vec{b}\\times\\vec{c})+(\\vec{c}\\times\\vec{a})=\\vec{0}\\), the points \\(A, B, C\\) are:",
    "collinear", ["coplanar but not collinear", "the vertices of a triangle", "mutually perpendicular"]),
  t("component-form-and-basis:trap:0", "Two 3-D vectors are equal when:",
    "all three corresponding components are equal", ["their magnitudes are equal", "their first components are equal", "they point into the same octant"]),
  t("component-form-and-basis:trap:1", "Which statement is TRUE?",
    "A vector's components change with the basis, but the vector itself does not", ["A vector's components are the same in every basis", "Changing the basis changes the vector", "A vector has no components"]),
  t("cross-product-algebra-and-properties:trap:0", "Which is generally TRUE for the cross product?",
    "\\(\\vec{a}\\times(\\vec{b}\\times\\vec{c}) \\neq (\\vec{a}\\times\\vec{b})\\times\\vec{c}\\)", ["It is associative", "It is commutative", "\\(\\vec{a}\\times\\vec{a} = |\\vec{a}|^2\\)"]),
  t("cross-product-algebra-and-properties:trap:1", "If \\(\\vec{a}\\times\\vec{b}=\\vec{0}\\) with both vectors non-zero, then:",
    "\\(\\vec{a}\\) and \\(\\vec{b}\\) are parallel", ["both must be zero", "they are perpendicular", "their dot product is zero"]),
  t("cross-product-magnitude-area-and-lagrange:trap:0", "The area of the triangle with adjacent sides \\(\\vec{a}, \\vec{b}\\) is:",
    "\\(\\tfrac{1}{2}|\\vec{a}\\times\\vec{b}|\\)", ["\\(|\\vec{a}\\times\\vec{b}|\\)", "\\(2|\\vec{a}\\times\\vec{b}|\\)", "\\(\\tfrac{1}{2}\\vec{a}\\cdot\\vec{b}\\)"]),
  t("cross-product-magnitude-area-and-lagrange:trap:1", "In \\(|\\vec{a}\\times\\vec{b}|=|\\vec{a}||\\vec{b}|\\sin\\theta\\), the factor \\(\\sin\\theta\\) is:",
    "always non-negative (since \\(0\\le\\theta\\le\\pi\\))", ["sometimes negative", "always 1", "always equal to \\(\\cos\\theta\\)"]),
  t("direction-cosines:trap:0", "For direction angles \\(\\alpha,\\beta,\\gamma\\), \\(\\sin^2\\alpha+\\sin^2\\beta+\\sin^2\\gamma\\) equals:",
    "\\(2\\)", ["\\(1\\)", "\\(3\\)", "\\(0\\)"]),
  t("direction-cosines:trap:1", "Which statement about direction cosines is TRUE?",
    "A direction cosine can be negative", ["Direction cosines are always positive", "Direction cosines lie strictly between 0 and 1", "Their sum is always 1"]),
  t("distance-identities-in-quadrilaterals:trap:0", "\\(\\vec{PQ}\\parallel\\vec{RS}\\) if and only if:",
    "\\(\\vec{PQ}\\times\\vec{RS}=\\vec{0}\\)", ["\\(\\vec{PQ}\\cdot\\vec{RS}=0\\)", "\\(|\\vec{PQ}|=|\\vec{RS}|\\)", "\\(\\vec{PQ}=\\vec{RS}\\)"]),
  t("distance-identities-in-quadrilaterals:trap:1", "Best first step to prove \\(|\\vec{p}-\\vec{q}|^2 = |\\vec{p}|^2 - 2\\vec{p}\\cdot\\vec{q} + |\\vec{q}|^2\\)?",
    "Expand \\((\\vec{p}-\\vec{q})\\cdot(\\vec{p}-\\vec{q})\\)", ["Assign coordinates and compute", "Take magnitudes first", "Use the cross product"]),
  t("dot-product-evaluation-and-work:trap:0", "Which statement about the nature of the dot and cross products is correct?",
    "\\(\\vec{a}\\cdot\\vec{b}\\) is a scalar; \\(\\vec{a}\\times\\vec{b}\\) is a vector", ["Both are scalars", "Both are vectors", "Dot is a vector; cross is a scalar"]),
  t("dot-product-evaluation-and-work:trap:1", "A force does negative work on an object. This means:",
    "the force has a component opposite to the displacement (valid)", ["the calculation is wrong — work can't be negative", "the object does not move", "the force is zero"]),
  t("magnitude-and-distance:trap:0", "For points \\(A, B\\) with position vectors \\(\\vec{a},\\vec{b}\\), \\(\\overrightarrow{AB}\\) equals:",
    "\\(\\vec{b}-\\vec{a}\\)", ["\\(\\vec{a}-\\vec{b}\\)", "\\(\\vec{a}+\\vec{b}\\)", "\\(\\tfrac{\\vec{a}+\\vec{b}}{2}\\)"]),
  t("magnitude-and-distance:trap:1", "Given \\(|\\vec{a}|,|\\vec{b}|\\) and \\(\\vec{a}\\cdot\\vec{b}\\), how do you find \\(|\\vec{a}\\times\\vec{b}|\\)?",
    "\\(|\\vec{a}\\times\\vec{b}|^2 = |\\vec{a}|^2|\\vec{b}|^2 - (\\vec{a}\\cdot\\vec{b})^2\\)", ["It cannot be found", "\\(|\\vec{a}\\times\\vec{b}| = |\\vec{a}||\\vec{b}|\\)", "\\(|\\vec{a}\\times\\vec{b}| = \\vec{a}\\cdot\\vec{b}\\)"]),
  t("moment-of-force:trap:0", "The moment of a force \\(\\vec{F}\\) at position \\(\\vec{r}\\) about the origin is:",
    "\\(\\vec{r}\\times\\vec{F}\\)", ["\\(\\vec{F}\\times\\vec{r}\\)", "\\(\\vec{r}\\cdot\\vec{F}\\)", "\\(\\vec{F}\\cdot\\vec{r}\\)"]),
  t("moment-of-force:trap:1", "The moment of a force about a point is:",
    "a vector that depends on the chosen point", ["a scalar independent of the point", "the same about every point", "always zero"]),
  t("parallelogram-properties-and-diagonals:trap:0", "In parallelogram \\(ABCD\\) (vertices in order), which sides are equal vectors?",
    "\\(\\vec{AB}=\\vec{DC}\\)", ["\\(\\vec{AB}=\\vec{CD}\\)", "\\(\\vec{AB}=\\vec{BC}\\)", "\\(\\vec{AC}=\\vec{BD}\\)"]),
  t("parallelogram-properties-and-diagonals:trap:1", "In parallelogram \\(ABCD\\), the position vector of \\(D\\) is:",
    "\\(\\vec{a}+\\vec{c}-\\vec{b}\\)", ["\\(\\vec{a}+\\vec{b}-\\vec{c}\\)", "\\(\\vec{b}+\\vec{c}-\\vec{a}\\)", "\\(\\tfrac{\\vec{a}+\\vec{c}}{2}\\)"]),
  t("perpendicularity-test:trap:0", "If \\(|\\vec{a}+\\vec{b}|=|\\vec{a}-\\vec{b}|\\), then:",
    "\\(\\vec{a}\\perp\\vec{b}\\)", ["\\(\\vec{a}=\\vec{b}\\)", "\\(\\vec{a}\\parallel\\vec{b}\\)", "\\(\\vec{a}=-\\vec{b}\\)"]),
  t("perpendicularity-test:trap:1", "\\(\\vec{a}\\cdot\\vec{b}=0\\) implies the vectors are perpendicular only if:",
    "both vectors are non-zero", ["they are unit vectors", "they are parallel", "always — no condition is needed"]),
  t("position-and-displacement-vectors:trap:0", "The displacement \\(\\overrightarrow{AB}\\) is computed as:",
    "head minus tail: \\(\\vec{b}-\\vec{a}\\)", ["tail minus head: \\(\\vec{a}-\\vec{b}\\)", "\\(\\vec{a}+\\vec{b}\\)", "the midpoint of \\(A\\) and \\(B\\)"]),
  t("position-and-displacement-vectors:trap:1", "Which quantity is INDEPENDENT of the choice of origin?",
    "the displacement vector \\(\\overrightarrow{AB}\\)", ["the position vector of \\(A\\)", "the position vector of \\(B\\)", "both position vectors"]),
  t("scalar-multiplication:trap:0", "Multiplying a vector by \\(-3\\):",
    "scales its length by 3 and reverses its direction", ["scales by 3, keeping the same direction", "reverses direction only", "scales by \\(-3\\) but keeps the direction"]),
  t("scalar-projection:trap:0", "The SCALAR projection of \\(\\vec{a}\\) on \\(\\vec{b}\\) is:",
    "\\(\\tfrac{\\vec{a}\\cdot\\vec{b}}{|\\vec{b}|}\\)", ["\\(\\tfrac{\\vec{a}\\cdot\\vec{b}}{|\\vec{b}|^2}\\)", "\\(\\tfrac{\\vec{a}\\cdot\\vec{b}}{|\\vec{a}|}\\)", "\\(\\vec{a}\\cdot\\vec{b}\\)"]),
  t("scalar-projection:trap:1", "A negative scalar projection of \\(\\vec{a}\\) on \\(\\vec{b}\\) means the angle between them is:",
    "obtuse", ["acute", "right", "zero"]),
  t("scalar-triple-product-and-coplanarity:trap:0", "\\([\\vec{a}\\,\\vec{b}\\,\\vec{c}]=0\\) means the three vectors are:",
    "coplanar", ["all parallel", "\\(\\vec{a}\\parallel\\vec{b}\\)", "mutually perpendicular"]),
  t("scalar-triple-product-and-coplanarity:trap:1", "When evaluating a scalar triple product as a determinant, expand along:",
    "the row or column with the most zeros", ["the first row always", "the main diagonal", "the row with the largest entries"]),
  t("section-formula-internal-external:trap:0", "For EXTERNAL division in ratio \\(m:n\\), the denominator in the section formula is:",
    "\\(m-n\\)", ["\\(m+n\\)", "\\(mn\\)", "\\(n\\)"]),
  t("section-formula-internal-external:trap:1", "In the section formula, the ratio \\(m:n\\) for \\(P\\) dividing \\(AB\\) means:",
    "\\(AP:PB = m:n\\)", ["\\(AP:AB = m:n\\)", "\\(PB:AP = m:n\\)", "\\(AB:AP = m:n\\)"]),
  t("solve-perpendicularity-constraint-system:trap:0", "Expanding \\((\\vec{a}+\\vec{b})\\cdot(\\vec{a}+\\vec{b})\\) gives:",
    "\\(|\\vec{a}|^2 + 2\\vec{a}\\cdot\\vec{b} + |\\vec{b}|^2\\)", ["\\(|\\vec{a}|^2 + |\\vec{b}|^2\\)", "\\(|\\vec{a}|^2 - 2\\vec{a}\\cdot\\vec{b} + |\\vec{b}|^2\\)", "\\(|\\vec{a}| + |\\vec{b}|\\)"]),
  t("solve-perpendicularity-constraint-system:trap:1", "If \\(\\vec{a}\\) is a unit vector, then:",
    "\\(\\vec{a}\\cdot\\vec{a}=|\\vec{a}|^2=1\\)", ["\\(\\vec{a}=1\\)", "\\(|\\vec{a}|=0\\)", "\\(\\vec{a}\\cdot\\vec{a}=\\vec{a}\\)"]),
  t("triangle-vector-loop-and-centroid:trap:0", "In a triangle, \\(\\vec{BA}\\) equals:",
    "\\(-\\vec{AB}\\)", ["\\(\\vec{AB}\\)", "\\(2\\vec{AB}\\)", "\\(\\vec{0}\\)"]),
  t("triangle-vector-loop-and-centroid:trap:1", "If \\(G\\) is the centroid (position \\(\\vec{g}\\)) and \\(A\\) has position \\(\\vec{a}\\), then \\(\\overrightarrow{AG}\\) equals:",
    "\\(\\vec{g}-\\vec{a}\\)", ["\\(\\tfrac{\\vec{g}}{3}\\)", "\\(\\vec{a}-\\vec{g}\\)", "\\(\\tfrac{\\vec{g}+\\vec{a}}{2}\\)"]),
  t("triple-product-cyclic-and-derived-identities:trap:0", "Swapping two vectors in a scalar triple product (e.g. \\([\\vec{a}\\,\\vec{c}\\,\\vec{b}]\\)):",
    "multiplies its value by \\(-1\\)", ["leaves it unchanged", "makes it zero", "doubles it"]),
  t("triple-product-cyclic-and-derived-identities:trap:1", "Which equals \\((\\vec{a}\\times\\vec{b})\\cdot\\vec{c}\\)?",
    "\\((\\vec{c}\\times\\vec{a})\\cdot\\vec{b}\\)", ["\\((\\vec{b}\\times\\vec{a})\\cdot\\vec{c}\\)", "\\((\\vec{a}\\times\\vec{c})\\cdot\\vec{b}\\)", "\\(\\vec{a}\\cdot(\\vec{c}\\times\\vec{b})\\)"]),
  t("types-of-vectors:trap:0", "Which statement is correct?",
    "Two vectors can be parallel even if their points are not collinear", ["Parallel vectors always come from collinear points", "Collinear points always give perpendicular vectors", "Parallel vectors must be equal"]),
  t("types-of-vectors:trap:1", "The zero vector \\(\\vec{0}\\) is:",
    "considered parallel to every vector (direction undefined)", ["perpendicular to every vector", "a unit vector", "equal to \\(\\hat{i}+\\hat{j}+\\hat{k}\\)"]),
  t("unit-vector-and-direction-construction:trap:0", "Before accepting given angles as a vector's direction angles, check that:",
    "\\(\\cos^2\\alpha+\\cos^2\\beta+\\cos^2\\gamma=1\\)", ["\\(\\alpha+\\beta+\\gamma=180^\\circ\\)", "\\(\\cos\\alpha+\\cos\\beta+\\cos\\gamma=1\\)", "all angles are acute"]),
  t("unit-vector-and-direction-construction:trap:1", "A vector equally inclined to the \\(x\\)- and \\(y\\)-axes has:",
    "equal \\(x\\)- and \\(y\\)-direction cosines", ["equal \\(x\\)- and \\(z\\)-components only", "all three direction cosines equal", "a zero \\(z\\)-component always"]),
  t("unit-vector-orthogonal-triple-configurations:trap:0", "Three unit vectors with equal pairwise angles are:",
    "not necessarily mutually perpendicular", ["always orthonormal", "always coplanar", "always equal"]),
  t("unit-vector-orthogonal-triple-configurations:trap:1", "\\(\\{\\vec{a},\\vec{b},\\vec{a}\\times\\vec{b}\\}\\) is an orthonormal set if and only if:",
    "\\(\\vec{a}\\perp\\vec{b}\\) and both are unit vectors", ["\\(\\vec{a}\\parallel\\vec{b}\\)", "\\(\\vec{a}\\cdot\\vec{b}=1\\)", "any \\(\\vec{a},\\vec{b}\\) work"]),
  t("unit-vector-perpendicular-via-cross:trap:0", "How many unit vectors are perpendicular to two given non-parallel vectors?",
    "two (\\(\\pm\\) the normalised cross product)", ["exactly one", "infinitely many", "none"]),
  t("unit-vector-perpendicular-via-cross:trap:1", "Which is a UNIT vector perpendicular to both \\(\\vec{a},\\vec{b}\\)?",
    "\\(\\tfrac{\\vec{a}\\times\\vec{b}}{|\\vec{a}\\times\\vec{b}|}\\)", ["\\(\\vec{a}\\times\\vec{b}\\)", "\\(2(\\vec{a}\\times\\vec{b})\\)", "\\(\\tfrac{\\vec{a}\\times\\vec{b}}{|\\vec{a}||\\vec{b}|}\\)"]),
  t("vector-addition:trap:0", "If vectors form a closed polygon (head-to-tail), their sum is:",
    "\\(\\vec{0}\\)", ["the perimeter", "the longest side", "twice the first vector"]),
  t("vector-addition:trap:1", "Which inequality (the triangle inequality) holds for ANY two vectors?",
    "\\(|\\vec{a}+\\vec{b}|\\le|\\vec{a}|+|\\vec{b}|\\)", ["\\(|\\vec{a}+\\vec{b}|=|\\vec{a}|+|\\vec{b}|\\)", "\\(|\\vec{a}+\\vec{b}|\\ge|\\vec{a}|+|\\vec{b}|\\)", "\\(|\\vec{a}+\\vec{b}|=|\\vec{a}|-|\\vec{b}|\\)"]),
  t("vector-triple-product-bac-cab:trap:0", "The BAC-CAB rule applies to:",
    "the vector triple product \\(\\vec{a}\\times(\\vec{b}\\times\\vec{c})\\)", ["the scalar triple product \\([\\vec{a}\\,\\vec{b}\\,\\vec{c}]\\)", "the dot product", "any product of three vectors"]),
  t("vector-triple-product-bac-cab:trap:1", "Which is generally TRUE?",
    "\\(\\vec{a}\\times(\\vec{b}\\times\\vec{c}) \\neq (\\vec{a}\\times\\vec{b})\\times\\vec{c}\\)", ["the two groupings are always equal", "both groupings equal \\(\\vec{0}\\)", "both equal \\(\\vec{a}\\cdot(\\vec{b}\\times\\vec{c})\\)"]),
  t("vector-triple-product-bac-cab:trap:2", "If \\(\\vec{a}\\times\\vec{b}=\\vec{c}\\) and \\(\\vec{b}\\times\\vec{c}=\\vec{a}\\), the three vectors form:",
    "a mutually perpendicular set of unit vectors", ["a set of parallel vectors", "a coplanar set", "a set with \\(\\vec{a}=\\vec{b}=\\vec{c}\\)"]),
  t("what-is-a-vector:trap:0", "Two arrows of the same length and direction, drawn at different places, represent:",
    "the same vector", ["different vectors", "perpendicular vectors", "opposite vectors"]),
];
