/**
 * Write src/lib/notes/notesNavIndex.generated.ts from the notes registry.
 *
 *   npm run notes:nav-index              # regenerate
 *   npm run notes:nav-index -- --check   # exit 1 if the committed file is stale
 *
 * RUN AFTER SHIPPING OR RENAMING A NOTES CHAPTER and commit the result;
 * tests/notes-nav-index.test.ts fails until you do. Why the nav reads a
 * generated file instead of the registry: src/lib/notes/notesNavIndex.ts.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { NOTES_CHAPTERS } from "@/lib/notes/chapters";
import { buildNotesNavIndex } from "@/lib/notes/notesNavIndex";

const OUT = path.resolve(__dirname, "../../src/lib/notes/notesNavIndex.generated.ts");

const entries = buildNotesNavIndex(NOTES_CHAPTERS);
const body =
  "// GENERATED by `npm run notes:nav-index` from src/lib/notes/chapters.ts — do not edit.\n" +
  "// The nav's four facts per chapter, so the page shell never imports the notes\n" +
  "// corpus. Why: src/lib/notes/notesNavIndex.ts. Drift check: tests/notes-nav-index.test.ts.\n" +
  'import type { NotesNavEntry } from "./notesNavIndex";\n\n' +
  "export const NOTES_NAV_INDEX: readonly NotesNavEntry[] = " +
  JSON.stringify(entries, null, 2) +
  ";\n";

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8").replace(/\r\n/g, "\n") : "";
  if (current !== body) {
    console.error("notesNavIndex.generated.ts is stale — run `npm run notes:nav-index` and commit it.");
    process.exit(1);
  }
  console.log(`notesNavIndex.generated.ts is current (${entries.length} chapters).`);
} else {
  writeFileSync(OUT, body);
  console.log(`wrote ${path.relative(process.cwd(), OUT)} (${entries.length} chapters)`);
}
