/**
 * The live `mh-hsc-12` taxonomy: chapter -> its subtopics, per subject.
 *
 * GENERATED by ./gen-catalog.ts, not hand-typed — run it after any taxonomy
 * rename. A chapter is HARD-validated against this list (an unknown one is a
 * transcription error, not a new chapter — auto-creating it would fork a
 * shipped chapter in two); an off-catalog SUBTOPIC is a soft flag, because
 * board papers blend topics more than a textbook exercise does.
 *
 * tests/mh-hsc-12-paper-catalog.test.ts re-checks this against the live DB when
 * credentials are present, so drift is reported rather than silently tolerated.
 */
import type { PaperCatalog } from "../../mh-ssc-10/lib";

export const HSC_MATHS_CATALOG: PaperCatalog = {
    subjectName: "Mathematics",
    chapters: {
        "Application of Definite Integration": [
            "Area Between Two Curves",
            "Area Under a Curve"
        ],
        "Application of Derivatives": [
            "Approximations",
            "Derivative as a Rate Measure",
            "Increasing and Decreasing Functions",
            "Lagrange's Mean Value Theorem",
            "Maxima and Minima",
            "Rolle's Theorem",
            "Tangents and Normals",
            "Velocity, Acceleration and Jerk"
        ],
        "Binomial Distribution": [
            "Bernoulli Trials",
            "Mean and Variance of a Binomial Distribution",
            "The Binomial Distribution"
        ],
        "Definite Integration": [
            "Definite Integral as a Limit of a Sum",
            "Fundamental Theorem of Integral Calculus",
            "Methods of Evaluation of Definite Integrals",
            "Properties of Definite Integrals"
        ],
        "Differential Equations": [
            "Applications of Differential Equations",
            "Formation of a Differential Equation",
            "Order and Degree of a Differential Equation",
            "Solution of a Differential Equation"
        ],
        "Differentiation": [
            "Derivatives of Composite Functions (Chain Rule)",
            "Derivatives of Implicit Functions",
            "Derivatives of Inverse Functions",
            "Derivatives of Inverse Trigonometric Functions",
            "Derivatives of Parametric Functions",
            "Differentiation of One Function with respect to Another",
            "Higher Order Derivatives",
            "Logarithmic Differentiation"
        ],
        "Indefinite Integration": [
            "Elementary Integration and Standard Formulae",
            "Integrals of Trigonometric Functions",
            "Integrals of the Type (px+q) over a Quadratic",
            "Integration by Partial Fractions",
            "Integration by Parts",
            "Integration by Substitution",
            "Special Integrals of Quadratic Forms"
        ],
        "Line and Planes": [
            "Angle Between Planes and Line-Plane Angle",
            "Coplanarity of Two Lines",
            "Distance of a Point from a Line",
            "Distance of a Point from a Plane",
            "Equations of a Plane",
            "Skew Lines and Shortest Distance",
            "Vector and Cartesian Equations of a Line"
        ],
        "Linear Programming": [
            "Formulation of a Linear Programming Problem",
            "Graphical Solution of a Linear Programming Problem",
            "Linear Inequations in Two Variables"
        ],
        "Mathematical Logic": [
            "Application of Logic to Switching Circuits",
            "Converse, Inverse and Contrapositive",
            "Logical Equivalence and Algebra of Statements",
            "Quantifiers, Duality and Negation of Statements",
            "Statements and Logical Connectives",
            "Tautology, Contradiction and Contingency",
            "Truth Tables of Compound Statements"
        ],
        "Matrices": [
            "Elementary Transformations of a Matrix",
            "Inverse by Adjoint Method",
            "Inverse by Elementary Transformation Method",
            "Minors, Cofactors and Adjoint",
            "Solution of Linear Equations using Matrices"
        ],
        "Pair of Straight Lines": [
            "Angle Bisectors of a Pair of Lines",
            "Angle between a Pair of Lines",
            "Combined Equation of a Pair of Lines",
            "General Second Degree Equation of Two Lines"
        ],
        "Probability Distributions": [
            "Continuous Random Variables and Probability Density Function",
            "Cumulative Distribution Function",
            "Expected Value and Variance of a Random Variable",
            "Probability Mass Function of a Discrete Random Variable",
            "Random Variables and Their Types"
        ],
        "Trigonometric Functions": [
            "Applications of Sine, Cosine and Projection Rules",
            "Inverse Trigonometric Functions and Principal Values",
            "Polar Coordinates",
            "Properties of Inverse Trigonometric Functions",
            "Solution of Triangle — Sine, Cosine and Projection Rules",
            "Trigonometric Equations and General Solutions"
        ],
        "Vectors": [
            "Cross Product of Vectors",
            "Dot Product of Vectors",
            "Scalar and Vector Triple Product",
            "Section Formula",
            "Vectors and Their Types"
        ]
    },
};

export const HSC_PHYSICS_CATALOG: PaperCatalog = {
    subjectName: "Physics",
    chapters: {
        "AC Circuits": [
            "Average and RMS Values",
            "Electrical Resonance and Q Factor",
            "LC Oscillations",
            "Phasors and Types of AC Circuits",
            "Power in an AC Circuit"
        ],
        "Current Electricity": [
            "Galvanometer, Ammeter and Voltmeter",
            "Kirchhoff's Laws of Electrical Networks",
            "Potentiometer",
            "Wheatstone Bridge and Metre Bridge"
        ],
        "Dual Nature of Radiation and Matter": [
            "Davisson-Germer Experiment and Duality of Matter",
            "De Broglie Hypothesis",
            "Einstein's Photoelectric Equation",
            "Photo Cell",
            "Photoelectric Effect",
            "Wave-Particle Duality of Radiation"
        ],
        "Electromagnetic Induction": [
            "Eddy Currents",
            "Faraday's Laws and Magnetic Flux",
            "Generators, Back emf and Energy Transfer",
            "Induced emf in a Stationary Coil",
            "Lenz's Law",
            "Motional Electromotive Force",
            "Mutual Inductance",
            "Self-Inductance and Energy in a Magnetic Field"
        ],
        "Electrostatics": [
            "Applications of Gauss' Law",
            "Capacitors and Combination of Capacitors",
            "Conductors, Insulators and Dielectrics",
            "Electric Potential and Potential Energy",
            "Energy Stored in a Capacitor",
            "Equipotential Surfaces",
            "Parallel Plate Capacitor with a Dielectric",
            "Potential Energy of Charges and Dipoles"
        ],
        "Kinetic Theory of Gases and Radiation": [
            "Absorption, Reflection and Transmission of Heat Radiation",
            "Behaviour of Gases, Ideal and Real Gas",
            "Kirchhoff's Law of Heat Radiation",
            "Law of Equipartition of Energy and Degrees of Freedom",
            "Mean Free Path and Pressure of an Ideal Gas",
            "Perfect Blackbody and Emissivity",
            "RMS Speed and Interpretation of Temperature",
            "Specific Heat Capacity and Mayer's Relation",
            "Spectral Distribution and Wien's Displacement Law"
        ],
        "Magnetic Fields due to Electric Current": [
            "Ampere's Law, Solenoid and Toroid",
            "Cyclotron and Helical Motion",
            "Force Between Two Parallel Currents",
            "Force on a Current-Carrying Wire",
            "Magnetic Dipole Moment and Potential Energy",
            "Magnetic Field due to a Current",
            "Magnetic Force on a Moving Charge",
            "Torque on a Current Loop and the Moving Coil Galvanometer"
        ],
        "Magnetic Materials": [
            "Diamagnetism, Paramagnetism and Ferromagnetism",
            "Hysteresis",
            "Magnetization and Magnetic Intensity",
            "Origin of Magnetism in Materials",
            "Permanent Magnets, Electromagnets and Magnetic Shielding",
            "Torque on a Magnetic Dipole"
        ],
        "Mechanical Properties of Fluids": [
            "Capillary Action",
            "Equation of Continuity and Bernoulli's Equation",
            "Excess Pressure, Drops and Bubbles",
            "Fluid Pressure and Pascal's Law",
            "Stokes' Law and Terminal Velocity",
            "Surface Tension and Surface Energy",
            "Viscosity, Critical Velocity and Reynolds Number"
        ],
        "Oscillations": [
            "Acceleration, Velocity and Displacement in S.H.M.",
            "Amplitude, Period and Frequency of S.H.M.",
            "Angular S.H.M. and Magnet Vibrating in a Magnetic Field",
            "Composition of Two S.H.M.s",
            "Energy of a Particle Performing S.H.M.",
            "Free, Forced and Damped Vibrations",
            "Periodic Motion and Linear S.H.M.",
            "Reference Circle, Phase and Graphical Representation",
            "Simple Pendulum"
        ],
        "Rotational Dynamics": [
            "Angular Momentum and Torque",
            "Applications of Uniform Circular Motion",
            "Conservation of Angular Momentum",
            "Kinematics and Dynamics of Circular Motion",
            "Moment of Inertia and Radius of Gyration",
            "Rolling Motion",
            "Theorems of Parallel and Perpendicular Axes",
            "Vertical Circular Motion"
        ],
        "Semiconductor Devices": [
            "Bipolar Junction Transistor",
            "Logic Gates",
            "Photodiode, Solar Cell and LED",
            "Ripple Factor and Filter Circuits",
            "Transistor as an Amplifier",
            "Zener Diode",
            "p-n Junction Diode as a Rectifier"
        ],
        "Structure of Atoms and Nuclei": [
            "Atomic Nucleus: Constituents, Size and Forces",
            "Atomic Spectra",
            "Bohr's Atomic Model",
            "Law of Radioactive Decay, Half-Life and Average Life",
            "Nuclear Binding Energy",
            "Nuclear Fission and Fusion",
            "Radioactive Decays",
            "Thomson's and Rutherford's Atomic Models"
        ],
        "Superposition of Waves": [
            "Beats",
            "Harmonics, Overtones and End Correction",
            "Progressive Waves",
            "Stationary Waves",
            "Superposition of Waves",
            "Vibrations of Air Columns",
            "Vibrations of a Stretched String and Sonometer"
        ],
        "Thermodynamics": [
            "Carnot Cycle and Carnot Engine",
            "First Law of Thermodynamics",
            "Heat Engines",
            "Heat, Internal Energy and Work",
            "Refrigerators and Heat Pumps",
            "Second Law of Thermodynamics",
            "Thermodynamic Processes",
            "Thermodynamic State Variables and the p-V Diagram"
        ],
        "Wave Optics": [
            "Diffraction at a Single Slit",
            "Interference and Young's Double Slit Experiment",
            "Nature of Light and Huygens' Principle",
            "Polarization and Brewster's Law",
            "Reflection and Refraction on Huygens' Theory",
            "Resolving Power"
        ]
    },
};

/** Routed by subject, mirroring `grammarFor` in ./lib.ts. */
export const CATALOGS: Record<string, PaperCatalog> = {
    "Mathematics": HSC_MATHS_CATALOG,
    "Physics": HSC_PHYSICS_CATALOG,
};

export function catalogFor(subject: string): PaperCatalog {
    const c = CATALOGS[String(subject ?? "").trim()];
    if (!c) throw new Error(`no paper catalog for subject ${JSON.stringify(subject)}`);
    return c;
}
