/**
 * Regenerate ./catalog.ts from the LIVE `mh-hsc-12` taxonomy.
 *
 *   npx tsx scripts/mh-hsc-12-pyq/paper/gen-catalog.ts          # writes catalog.ts
 *   npx tsx scripts/mh-hsc-12-pyq/paper/gen-catalog.ts --check  # exits 1 if stale
 *
 * The Maths catalog was generated once by hand-run query on 2026-09-19 and the
 * generator was never kept, so when Physics arrived there was nothing to re-run
 * — the choice was hand-typing 117 subtopic names or writing this. A catalog
 * that cannot be regenerated is a catalog that silently rots against the
 * taxonomy it claims to mirror.
 *
 * `--check` is what a human runs after a taxonomy rename; it is deliberately NOT
 * in the push gate, because this reads the live DB and its verdict moves without
 * a diff (the same reason `syllabus:audit` stays out).
 */
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
// Loaded BEFORE the admin client, which reads the key at construction time.
const envLocal = join(process.cwd(), ".env.local");
if (existsSync(envLocal)) require("dotenv").config({ path: envLocal, override: true });
import { createSupabaseAdminClient } from "../../../src/lib/supabase/admin";
import { EXAM_ID } from "../config";

const SUBJECTS = ["Mathematics", "Physics"] as const;

/** `PaperCatalog` keys on the chapter name, so the query returns names only —
 *  ids would add a second thing to keep in sync for no reader. */
async function load(subject: string): Promise<Record<string, string[]>> {
  const db = createSupabaseAdminClient();

  const { data: subj, error: se } = await db
    .from("subjects")
    .select("id")
    .eq("exam_id", EXAM_ID)
    .eq("name", subject)
    .single();
  if (se) throw new Error(`${subject}: ${se.message}`);

  const { data: chapters, error: ce } = await db
    .from("chapters")
    .select("id, name")
    .eq("subject_id", subj.id)
    .order("name");
  if (ce) throw new Error(`${subject} chapters: ${ce.message}`);

  const out: Record<string, string[]> = {};
  // Chunked at 200: `.in()` puts the list in the URL, and that limit is NOT the
  // 1000-row one on the result — see the recurring-pitfalls note in CLAUDE.md.
  const ids = chapters.map((c) => c.id);
  const byChapter = new Map<string, string[]>();
  for (let i = 0; i < ids.length; i += 200) {
    const { data, error } = await db
      .from("subtopics")
      .select("name, chapter_id")
      .in("chapter_id", ids.slice(i, i + 200))
      .order("name");
    if (error) throw new Error(`${subject} subtopics: ${error.message}`);
    for (const s of data) byChapter.set(s.chapter_id, [...(byChapter.get(s.chapter_id) ?? []), s.name]);
  }
  for (const c of chapters) out[c.name] = (byChapter.get(c.id) ?? []).sort();
  return out;
}

const HEADER = `/**
 * The live \`mh-hsc-12\` taxonomy: chapter -> its subtopics, per subject.
 *
 * GENERATED by ./gen-catalog.ts, not hand-typed — run it after any taxonomy
 * rename. A chapter is HARD-validated against this list (an unknown one is a
 * transcription error, not a new chapter — auto-creating it would fork a
 * shipped chapter in two); an off-catalog SUBTOPIC is a soft flag, because
 * board papers blend topics more than a textbook exercise does.
 *
 * tests/mh-hsc-12-paper-catalog.test.ts re-checks this against the live DB when
 * credentials are present, so drift is reported rather than silently tolerated.
 */
import type { PaperCatalog } from "../../mh-ssc-10/lib";
`;

const render = (subject: string, chapters: Record<string, string[]>, varName: string) => {
  const body = Object.entries(chapters)
    .map(
      ([ch, subs]) =>
        `        ${JSON.stringify(ch)}: [\n` +
        subs.map((s) => `            ${JSON.stringify(s)}`).join(",\n") +
        `\n        ]`,
    )
    .join(",\n");
  return `\nexport const ${varName}: PaperCatalog = {\n    subjectName: ${JSON.stringify(subject)},\n    chapters: {\n${body}\n    },\n};\n`;
};

async function main() {
  const parts = [HEADER];
  const counts: string[] = [];
  for (const subject of SUBJECTS) {
    const chapters = await load(subject);
    const varName = `HSC_${subject === "Mathematics" ? "MATHS" : subject.toUpperCase()}_CATALOG`;
    parts.push(render(subject, chapters, varName));
    counts.push(
      `${subject}: ${Object.keys(chapters).length} chapters, ${Object.values(chapters).flat().length} subtopics`,
    );
  }
  parts.push(
    `\n/** Routed by subject, mirroring \`grammarFor\` in ./lib.ts. */\n` +
      `export const CATALOGS: Record<string, PaperCatalog> = {\n` +
      SUBJECTS.map(
        (s) => `    ${JSON.stringify(s)}: HSC_${s === "Mathematics" ? "MATHS" : s.toUpperCase()}_CATALOG,`,
      ).join("\n") +
      `\n};\n\nexport function catalogFor(subject: string): PaperCatalog {\n` +
      `    const c = CATALOGS[String(subject ?? "").trim()];\n` +
      `    if (!c) throw new Error(\`no paper catalog for subject \${JSON.stringify(subject)}\`);\n` +
      `    return c;\n}\n`,
  );

  const next = parts.join("");
  const path = join(__dirname, "catalog.ts");

  if (process.argv.includes("--check")) {
    const current = readFileSync(path, "utf8");
    // Compare NORMALISED, because the working tree is autocrlf=true and a byte
    // comparison would report every line as drift on this machine.
    const norm = (s: string) => s.replace(/\r\n/g, "\n").trimEnd();
    if (norm(current) !== norm(next)) {
      console.error(`catalog.ts is STALE — run: npx tsx scripts/mh-hsc-12-pyq/paper/gen-catalog.ts`);
      process.exit(1);
    }
    console.log(`catalog.ts is current (${counts.join(" · ")})`);
    return;
  }

  writeFileSync(path, next, "utf8");
  console.log(`wrote ${path}\n  ${counts.join("\n  ")}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
