/**
 * Content for /guide/jee-mains-maths/formulas — the formulas and results JEE Mains Mathematics
 * actually tests, one group per playbook chapter, in strategy order.
 *
 * PLAIN TEXT + UNICODE, NOT LaTeX: the shared FormulaSheet prints `formula` as raw text, so LaTeX
 * would ship as literal markup (see GUIDE_TEMPLATES.md). Each entry is drawn from a concept in the
 * chapter's /notes/jee-mains-maths pages — what the notes rest on, not a syllabus dump.
 *
 * Notation: a compound exponent is written with ^( ), e.g. 2^(n − 1); C(n, r) = n!/(r!(n − r)!).
 */

import type { FormulaGroup } from "./types";

export const FORMULA_GROUPS: FormulaGroup[] = [
  {
    chapter: "Conic Sections",
    playbookSlug: "conic-sections",
    formulas: [
      { id: "circle-general", name: "Circle in general form", formula: "x² + y² + 2gx + 2fy + c = 0:   centre (−g, −f),   r = √(g² + f² − c)", legend: ["g, f, c = coefficients of the equation"], notes: "x-intercept = 2√(g² − c), y-intercept = 2√(f² − c)." },
      { id: "circle-chords", name: "Chords and tangent length", formula: "chord = 2√(r² − d²)     tangent length from P = √S₁     chord with midpoint P:  T = S₁", legend: ["d = distance from the centre to the chord", "S₁ = the circle's expression evaluated at P(x₁, y₁)", "T = xx₁ + yy₁ + g(x + x₁) + f(y + y₁) + c"] },
      { id: "two-circles", name: "Two circles", formula: "|r₁ − r₂| < C₁C₂ < r₁ + r₂  ⇔  they cut in two points     common chord:  S₁ − S₂ = 0", legend: ["C₁C₂ = distance between the centres", "S₁, S₂ = the two circle equations with RHS 0"], notes: "Circles through the meet of a circle S and a line L: S + λL = 0." },
      { id: "parabola", name: "Standard parabola", formula: "y² = 4ax:   focus (a, 0),   directrix x = −a,   LR = 4a,   point (at², 2at)", legend: ["a = focal length", "t = parameter"], notes: "Focal chord: t₁t₂ = −1, and its length at angle θ to the axis is 4a/sin²θ." },
      { id: "parabola-tangents", name: "Parabola tangents and normals", formula: "tangent y = mx + a/m touches at (a/m², 2a/m)     tangents at t₁, t₂ meet at (at₁t₂, a(t₁ + t₂))     normal y = mx − 2am − am³", legend: ["m = slope", "t₁, t₂ = parameters of the points of contact"] },
      { id: "ellipse", name: "Ellipse", formula: "x²/a² + y²/b² = 1 (a > b):   b² = a²(1 − e²),   foci (±ae, 0),   LR = 2b²/a,   SP + S′P = 2a", legend: ["e = eccentricity (0 < e < 1)", "S, S′ = foci", "P = a point on the ellipse"], notes: "SP = a − ex₁, S′P = a + ex₁. Point (a cos θ, b sin θ); area πab. If b > a, swap the roles: a² = b²(1 − e²)." },
      { id: "hyperbola", name: "Hyperbola", formula: "x²/a² − y²/b² = 1:   b² = a²(e² − 1),   foci (±ae, 0),   LR = 2b²/a,   |S′P − SP| = 2a", legend: ["e = eccentricity (e > 1)"], notes: "Rectangular hyperbola xy = c²: point (ct, c/t), e = √2." },
      { id: "tangency-conditions", name: "When y = mx + c is a tangent", formula: "circle x² + y² = a²:  c² = a²(1 + m²)     ellipse:  c² = a²m² + b²     hyperbola:  c² = a²m² − b²", legend: ["m = slope, c = y-intercept of the line"], notes: "Perpendicular tangents to the ellipse meet on the director circle x² + y² = a² + b²." },
    ],
  },
  {
    chapter: "Three Dimensional Geometry",
    playbookSlug: "three-dimensional-geometry",
    formulas: [
      { id: "direction-cosines", name: "Direction cosines", formula: "(l, m, n) = (a, b, c) / √(a² + b² + c²)     l² + m² + n² = 1", legend: ["a, b, c = direction ratios"] },
      { id: "angle-between-lines", name: "Angle between two lines", formula: "cos θ = |a₁a₂ + b₁b₂ + c₁c₂| / (√(a₁² + b₁² + c₁²) · √(a₂² + b₂² + c₂²))", legend: ["(a₁, b₁, c₁), (a₂, b₂, c₂) = direction ratios"], notes: "Perpendicular lines: a₁a₂ + b₁b₂ + c₁c₂ = 0." },
      { id: "plane-forms", name: "Plane through a point", formula: "a(x − x₁) + b(y − y₁) + c(z − z₁) = 0     normal from two in-plane directions:  n = u × v", legend: ["(a, b, c) = normal", "u, v = directions lying in the plane"], notes: "Planes through the line of intersection of P₁ = 0 and P₂ = 0: P₁ + λP₂ = 0." },
      { id: "point-plane-distance", name: "Distance from a plane", formula: "distance = |ax₁ + by₁ + cz₁ + d| / √(a² + b² + c²)", legend: ["plane: ax + by + cz + d = 0", "(x₁, y₁, z₁) = the point"] },
      { id: "foot-image-plane", name: "Foot and image in a plane", formula: "k = (ax₁ + by₁ + cz₁ + d) / (a² + b² + c²):   foot = P − k(a, b, c),   image = P − 2k(a, b, c)", legend: ["P = (x₁, y₁, z₁)", "plane: ax + by + cz + d = 0"] },
      { id: "angles-planes", name: "Angles with planes", formula: "line and plane:  sin θ = |d · n| / (|d| |n|)     two planes:  cos θ = |n₁ · n₂| / (|n₁| |n₂|)", legend: ["d = direction of the line", "n, n₁, n₂ = normals"] },
      { id: "foot-on-line", name: "Foot of a perpendicular on a line", formula: "t = (P − A) · d / |d|²,   foot M = A + t d,   image = 2M − P     distance = |AP × d| / |d|", legend: ["line through A with direction d", "P = the external point"] },
      { id: "skew-lines", name: "Shortest distance", formula: "skew:  SD = |(a₂ − a₁) · (d₁ × d₂)| / |d₁ × d₂|     parallel:  d = |(a₂ − a₁) × d| / |d|", legend: ["a₁, a₂ = points on the two lines", "d₁, d₂ = their directions"], notes: "SD = 0 means the lines are coplanar: (a₂ − a₁) · (d₁ × d₂) = 0." },
    ],
  },
  {
    chapter: "Relations and Functions",
    playbookSlug: "relations-and-functions",
    formulas: [
      { id: "function-counts", name: "Counting functions", formula: "all maps: nᵐ     one-one: n!/(n − m)!  (m ≤ n)     onto: nᵐ − C(n, 1)(n − 1)ᵐ + C(n, 2)(n − 2)ᵐ − …", legend: ["m = size of the domain", "n = size of the codomain"] },
      { id: "relation-counts", name: "Counting relations on an n-element set", formula: "all: 2^(n²)     reflexive: 2^(n² − n)     symmetric: 2^(n(n + 1)/2)", legend: ["n = number of elements"], notes: "The smallest equivalence relation with classes of sizes k₁, k₂, … has Σ kᵢ² pairs." },
      { id: "domain-rules", name: "Domain rules", formula: "sin⁻¹u, cos⁻¹u:  −1 ≤ u ≤ 1     log u:  u > 0     √u:  u ≥ 0     logₐ(log_b u) defined ⇔ u > 1  (a, b > 1)", legend: ["u = the inner expression"], notes: "Domain of f∘g: the x in the domain of g with g(x) in the domain of f." },
      { id: "composition", name: "Composition and cycles", formula: "(f∘g)(x) = f(g(x))     fᵏ = identity  ⇒  fⁿ = f^(n mod k)", legend: ["fᵏ = f composed with itself k times"], notes: "f(x) = (ax + b)/(cx + d) with a + d = 0 is its own inverse: f∘f = identity." },
      { id: "one-one-onto", name: "The two tests", formula: "one-one:  f(a) = f(b) ⇒ a = b     onto:  range of f = codomain", legend: ["f : A → B"], notes: "For y = p(x)/q(x), solve for x as a quadratic and require its discriminant ≥ 0 to get the range." },
      { id: "functional-pair", name: "Functional equations", formula: "f(x + y) = f(x) + f(y)  ⇒  f(n) = n f(1)     f(x) = bˣ/(bˣ + √b)  ⇒  f(x) + f(1 − x) = 1", legend: ["b > 0", "n = positive integer"], notes: "af(x) + bf(g(x)) = h(x): write the equation again with x replaced by g(x) and solve the pair." },
      { id: "three-sets", name: "Three sets", formula: "n(A ∪ B ∪ C) = Σ n(A) − Σ n(A ∩ B) + n(A ∩ B ∩ C)", legend: ["sums run over the three sets and the three pairs"], notes: "A − B = A ∩ B′." },
    ],
  },
  {
    chapter: "Sequences and Series",
    playbookSlug: "sequences-and-series",
    formulas: [
      { id: "ap", name: "Arithmetic progression", formula: "aₙ = a + (n − 1)d     Sₙ = (n/2)[2a + (n − 1)d] = (n/2)(a + l)", legend: ["a = first term, d = common difference", "l = last term"], notes: "Terms equidistant from the ends add equally: aₖ + aₙ₊₁₋ₖ = a₁ + aₙ." },
      { id: "gp", name: "Geometric progression", formula: "aₙ = arⁿ⁻¹     Sₙ = a(rⁿ − 1)/(r − 1)     S∞ = a/(1 − r),  |r| < 1", legend: ["a = first term, r = common ratio"] },
      { id: "means", name: "The three means", formula: "a, b, c in AP: 2b = a + c     GP: b² = ac     HP: b = 2ac/(a + c)     A ≥ G ≥ H,  G² = AH", legend: ["A, G, H = arithmetic, geometric, harmonic means of two positive numbers"] },
      { id: "am-gm", name: "AM ≥ GM", formula: "(x₁ + x₂ + … + xₙ)/n ≥ (x₁x₂…xₙ)^(1/n)", legend: ["xᵢ > 0"], notes: "Equality exactly when all the xᵢ are equal." },
      { id: "power-sums", name: "Sums of powers", formula: "Σk = n(n + 1)/2     Σk² = n(n + 1)(2n + 1)/6     Σk³ = [n(n + 1)/2]²", legend: ["k runs from 1 to n"] },
      { id: "agp", name: "Arithmetico-geometric series", formula: "S∞ = a/(1 − r) + dr/(1 − r)²,   |r| < 1", legend: ["terms a, (a + d)r, (a + 2d)r², …"], notes: "Standard route for a finite sum: write S, subtract rS, sum the GP that appears." },
      { id: "telescoping", name: "Telescoping", formula: "Σ [f(k) − f(k + 1)] = f(1) − f(n + 1)     k · k! = (k + 1)! − k!", legend: ["k runs from 1 to n"], notes: "k/(k⁴ + k² + 1) = ½[1/(k² − k + 1) − 1/(k² + k + 1)]." },
      { id: "common-terms", name: "Terms common to two APs", formula: "common difference of the shared terms = lcm(d₁, d₂)", legend: ["d₁, d₂ = the two common differences"] },
    ],
  },
  {
    chapter: "Definite Integration",
    playbookSlug: "definite-integration",
    formulas: [
      { id: "king", name: "Reflection property", formula: "∫ₐᵇ f(x) dx = ∫ₐᵇ f(a + b − x) dx", legend: ["a, b = limits"], notes: "Add the two forms; the troublesome part usually cancels to a constant." },
      { id: "odd-even", name: "Symmetric limits", formula: "∫₋ₐᵃ f(x) dx = 0 if f is odd,   2∫₀ᵃ f(x) dx if f is even", legend: ["odd: f(−x) = −f(x); even: f(−x) = f(x)"], notes: "Split any integrand into odd and even parts first." },
      { id: "halving", name: "The 1 + bᵍ halving", formula: "∫₋ₐᵃ h(x)/(1 + b^g(x)) dx = ∫₀ᵃ h(x) dx", legend: ["h = even function", "g = odd function, b > 0"] },
      { id: "periodic", name: "Many periods", formula: "∫₀^(nT) f(x) dx = n ∫₀ᵀ f(x) dx", legend: ["T = period of f", "n = positive integer"], notes: "The same idea handles {x}: ∫₀ⁿ g({x}) dx = n ∫₀¹ g(x) dx." },
      { id: "leibniz", name: "Leibniz rule", formula: "d/dx ∫ from u(x) to v(x) of f(t) dt = f(v(x)) v′(x) − f(u(x)) u′(x)", legend: ["u, v = variable limits"], notes: "f(x) = g(x) + ∫ₐᵇ k(t) f(t) dt forces f(x) = g(x) + A with A a constant to be found." },
      { id: "reduction", name: "Reduction for sine powers", formula: "∫₀^(π/2) sinⁿx dx = ((n − 1)/n) ∫₀^(π/2) sinⁿ⁻²x dx", legend: ["n ≥ 2"], notes: "The same holds for cosⁿx on [0, π/2]." },
      { id: "riemann", name: "Limit of a sum", formula: "lim (n → ∞) (1/n) Σ f(k/n) = ∫₀¹ f(x) dx", legend: ["k runs from 1 to n"], notes: "Replace k/n by x and 1/n by dx." },
      { id: "bounds", name: "Bounds on an integral", formula: "m(b − a) ≤ ∫ₐᵇ f(x) dx ≤ M(b − a)", legend: ["m, M = least and greatest values of f on [a, b]"] },
    ],
  },
  {
    chapter: "Permutations and Combinations",
    playbookSlug: "permutations-and-combinations",
    formulas: [
      { id: "npr-ncr", name: "Arrangements and selections", formula: "ⁿPᵣ = n!/(n − r)!     C(n, r) = n!/(r!(n − r)!)", legend: ["n = objects, r = chosen"], notes: "One-one maps from an m-set to an n-set: ⁿPₘ; strictly increasing ones: C(n, m)." },
      { id: "repeats", name: "Arrangements with repeats", formula: "n!/(p! q! r! …)", legend: ["p, q, r = counts of identical items"] },
      { id: "gap-method", name: "No two together", formula: "n! × ⁿ⁺¹Pₖ", legend: ["n = other items arranged first", "k = items placed in the n + 1 gaps"] },
      { id: "stars-bars", name: "Stars and bars", formula: "x₁ + … + xₖ = n,  xᵢ ≥ 0:   C(n + k − 1, k − 1)     xᵢ ≥ 1:   C(n − 1, k − 1)", legend: ["n = identical items, k = distinct boxes"] },
      { id: "legendre", name: "Power of a prime in n!", formula: "⌊n/p⌋ + ⌊n/p²⌋ + ⌊n/p³⌋ + …", legend: ["p = prime", "⌊ ⌋ = greatest integer"] },
      { id: "geometry-counts", name: "Points and polygons", formula: "triangles: C(n, 3) − C(k, 3)     diagonals: n(n − 3)/2     triangles with no side of the polygon: n(n − 4)(n − 5)/6", legend: ["n = points or polygon vertices", "k = points lying on one line"] },
      { id: "sum-of-numbers", name: "Sum of all numbers formed", formula: "(number of arrangements ÷ n) × (digit sum) × 11…1  (n ones)", legend: ["n = number of digit places, all digits used"], notes: "If 0 is among the digits, subtract the numbers that start with 0." },
      { id: "rank", name: "Rank in the dictionary", formula: "rank = 1 + Σ cᵢ (n − i)!", legend: ["cᵢ = unused letters smaller than the i-th letter", "n = length of the word (distinct letters)"] },
    ],
  },
  {
    chapter: "Vector Algebra",
    playbookSlug: "vector-algebra",
    formulas: [
      { id: "dot", name: "Dot product and projection", formula: "a · b = |a||b| cos θ = a₁b₁ + a₂b₂ + a₃b₃     projection of a on b = (a · b)/|b|", legend: ["θ = angle between a and b"], notes: "a ⊥ b ⇔ a · b = 0." },
      { id: "magnitude", name: "Square of a sum", formula: "|a + b|² = |a|² + 2 a · b + |b|²", legend: ["a, b = vectors"], notes: "Square first, then use a · a = |a|²." },
      { id: "cross", name: "Cross product and area", formula: "|a × b| = |a||b| sin θ     triangle area = ½ |AB × AC|", legend: ["a × b is perpendicular to both a and b"], notes: "A vector perpendicular to a and b is λ(a × b)." },
      { id: "lagrange", name: "Lagrange's identity", formula: "|a × b|² + (a · b)² = |a|² |b|²", legend: ["a, b = vectors"] },
      { id: "scalar-triple", name: "Scalar triple product", formula: "[a b c] = a · (b × c)     [a b c] = 0  ⇔  a, b, c coplanar", legend: ["a, b, c = vectors"], notes: "Tetrahedron volume = ⅙ |[AB AC AD]|." },
      { id: "vector-triple", name: "Vector triple product", formula: "a × (b × c) = (a · c) b − (a · b) c", legend: ["a, b, c = vectors"] },
      { id: "section-bisector", name: "Section formula and bisector", formula: "p = (n a + m b)/(m + n)     bisector direction = a/|a| + b/|b|", legend: ["p divides AB in the ratio m : n internally", "a, b = position vectors"] },
      { id: "vector-equations", name: "Solving r × a = b × a", formula: "r × a = b × a  ⇒  r = b + λa", legend: ["λ = scalar"], notes: "a × c = b with a · c known: c = ((a · c) a − a × b)/|a|²." },
    ],
  },
  {
    chapter: "Differential Equations",
    playbookSlug: "differential-equations",
    formulas: [
      { id: "order-degree", name: "Order and degree", formula: "order = number of arbitrary constants eliminated     degree = power of the highest derivative after clearing radicals", legend: ["degree is defined only when the equation is a polynomial in the derivatives"] },
      { id: "separable", name: "Variables separable", formula: "dy/dx = f(x) g(y)  ⇒  ∫ dy/g(y) = ∫ f(x) dx + C", legend: ["C = constant"], notes: "For dy/dx = F(ax + by + c), put t = ax + by + c." },
      { id: "homogeneous", name: "Homogeneous equation", formula: "y = vx:   v + x dv/dx = F(v)  ⇒  ∫ dv/(F(v) − v) = ln|x| + C", legend: ["dy/dx = F(y/x)"], notes: "With constant terms, shift the origin: x = X + h, y = Y + k." },
      { id: "linear", name: "Linear equation", formula: "dy/dx + Py = Q  ⇒  y · e^(∫P dx) = ∫ Q e^(∫P dx) dx + C", legend: ["P, Q = functions of x", "e^(∫P dx) = integrating factor"], notes: "If x is the easier dependent variable, use dx/dy + P(y) x = Q(y)." },
      { id: "integrating-factors", name: "Quick integrating factors", formula: "P = k tan x  ⇒  IF = secᵏx     P = g′(x)/g(x)  ⇒  IF = g(x)     P = 1/(1 + x²)  ⇒  IF = e^(tan⁻¹x)", legend: ["IF = integrating factor"] },
      { id: "bernoulli", name: "Bernoulli equation", formula: "y′ + Py = Qyⁿ,   z = y^(1 − n)  ⇒  z′ + (1 − n)P z = (1 − n)Q", legend: ["n ≠ 0, 1"] },
      { id: "cooling", name: "Newton's law of cooling", formula: "dT/dt = −k(T − A)  ⇒  T − A = (T₀ − A) e^(−kt)", legend: ["A = surrounding temperature", "T₀ = temperature at t = 0"] },
      { id: "tangent-intercepts", name: "Intercepts of the tangent", formula: "x-intercept = x − y/y′     y-intercept = y − x y′", legend: ["(x, y) = point of contact, y′ = dy/dx there"] },
    ],
  },
  {
    chapter: "Probability",
    playbookSlug: "probability",
    formulas: [
      { id: "classical", name: "Classical probability", formula: "P(E) = n(E)/n(S)     P(A ∪ B) = P(A) + P(B) − P(A ∩ B)", legend: ["n(S) = equally likely outcomes"], notes: "k items fall in one given relative order with probability 1/k!." },
      { id: "conditional", name: "Conditional probability and independence", formula: "P(A | B) = P(A ∩ B)/P(B)     independent:  P(A ∩ B) = P(A) P(B)", legend: ["P(B) > 0"] },
      { id: "total-probability", name: "Total probability", formula: "P(E) = Σ P(Hᵢ) P(E | Hᵢ)", legend: ["Hᵢ = mutually exclusive cases covering every outcome"] },
      { id: "bayes", name: "Bayes' theorem", formula: "P(Hₖ | E) = P(Hₖ) P(E | Hₖ) / Σ P(Hᵢ) P(E | Hᵢ)", legend: ["Hₖ = the case asked about"] },
      { id: "binomial", name: "Binomial distribution", formula: "P(X = r) = C(n, r) pʳ qⁿ⁻ʳ     mean = np     variance = npq", legend: ["n = trials, p = success chance, q = 1 − p"] },
      { id: "random-variable", name: "Mean and variance of X", formula: "E(X) = Σ xᵢ pᵢ     Var(X) = E(X²) − (E(X))²", legend: ["pᵢ = P(X = xᵢ), Σ pᵢ = 1"] },
      { id: "alternate-turns", name: "Alternate turns", formula: "P(A wins) = p_A / (1 − q_A q_B)", legend: ["A goes first", "p = chance of success on a turn, q = 1 − p"] },
      { id: "two-dice", name: "Sum of two dice", formula: "P(sum = k) = (6 − |k − 7|)/36,   k = 2, …, 12", legend: ["two fair dice"] },
    ],
  },
  {
    chapter: "Binomial Theorem",
    playbookSlug: "binomial-theorem",
    formulas: [
      { id: "general-term", name: "General term", formula: "Tᵣ₊₁ = C(n, r) aⁿ⁻ʳ bʳ", legend: ["expansion of (a + b)ⁿ", "r = 0, 1, …, n"], notes: "C(n, r) = C(n, n − r)." },
      { id: "neighbour-ratio", name: "Ratio of neighbouring coefficients", formula: "C(n, r) / C(n, r − 1) = (n − r + 1)/r", legend: ["r ≥ 1"], notes: "Use it for consecutive coefficients in a given ratio and for the greatest term." },
      { id: "coefficient-sums", name: "Sums of coefficients", formula: "sum of coefficients = f(1)     even-index sum = (f(1) + f(−1))/2     odd-index sum = (f(1) − f(−1))/2", legend: ["f(x) = the expanded polynomial"], notes: "Σ C(n, r) = 2ⁿ." },
      { id: "weighted-sums", name: "Weighted sums", formula: "Σ r C(n, r) = n 2^(n − 1)     Σ r² C(n, r) = n(n + 1) 2^(n − 2)", legend: ["r runs from 0 to n"], notes: "Σ C(n, r)/(r + 1) = (2^(n + 1) − 1)/(n + 1)." },
      { id: "vandermonde", name: "Vandermonde's identity", formula: "Σ C(m, r) C(n, k − r) = C(m + n, k)", legend: ["r runs over all valid values"], notes: "Special case: Σ C(n, r)² = C(2n, n)." },
      { id: "hockey-stick", name: "Hockey stick", formula: "Σ C(k, r) = C(n + 1, r + 1)", legend: ["k runs from r to n"] },
      { id: "rational-terms", name: "Rational terms", formula: "C(n, r) p^((n − r)/a) q^(r/b) is rational  ⇔  a divides n − r and b divides r", legend: ["p, q = integers that are not perfect a-th, b-th powers"] },
      { id: "remainders", name: "Remainders", formula: "(mq ± 1)ⁿ = (a multiple of m) + (±1)ⁿ", legend: ["write the base as a multiple of the divisor plus or minus 1"], notes: "(1 + m)ⁿ − mn − 1 is divisible by m²." },
    ],
  },
  {
    chapter: "Application of Integrals",
    playbookSlug: "application-of-integrals",
    formulas: [
      { id: "between-curves", name: "Area between curves", formula: "A = ∫ₐᵇ (upper − lower) dx", legend: ["a, b = x-coordinates where the curves meet"], notes: "If the upper curve changes, split at the switch point." },
      { id: "horizontal-strips", name: "Horizontal strips", formula: "A = ∫ from c to d of (x_right − x_left) dy", legend: ["c, d = y-limits"], notes: "Use when the curves are x = g(y), as with sideways parabolas." },
      { id: "parabola-chord", name: "Parabola against a chord", formula: "∫ from α to β of a(x − α)(β − x) dx = a(β − α)³/6", legend: ["α, β = x-coordinates where the parabola meets the line"], notes: "y = ax² and y = mx enclose m³/(6a²)." },
      { id: "circle-arc", name: "Under a circular arc", formula: "∫ √(r² − x²) dx = (x/2)√(r² − x²) + (r²/2) sin⁻¹(x/r) + C", legend: ["r = radius"] },
      { id: "segment-ellipse", name: "Segment and ellipse", formula: "minor segment = ½ r²(θ − sin θ)     ellipse area = πab", legend: ["θ = angle at the centre in radians", "a, b = semi-axes"] },
      { id: "root-curve", name: "Under a square-root curve", formula: "∫₀ᶜ √(kx) dx = (2/3) c √(kc)", legend: ["k > 0"] },
      { id: "log-exp", name: "Logs and exponentials", formula: "∫ ln x dx = x ln x − x + C     ∫ aˣ dx = aˣ/ln a + C     ∫ₐᵇ (k/x) dx = k ln(b/a)", legend: ["a, b > 0"] },
      { id: "modulus-area", name: "Modulus and min/max curves", formula: "∫ |f(x)| dx = Σ |∫ f(x) dx| over the pieces between the zeros of f", legend: ["split at each zero of f"], notes: "For min{f, g} or max{f, g}, integrate whichever curve applies on each piece." },
    ],
  },
  {
    chapter: "Complex Numbers",
    playbookSlug: "complex-numbers",
    formulas: [
      { id: "conjugate", name: "Conjugate identities", formula: "z z̄ = |z|²     z + z̄ = 2 Re(z)     z − z̄ = 2i Im(z)     1/z = z̄/|z|²", legend: ["z̄ = conjugate of z"], notes: "|a ± b|² = |a|² + |b|² ± 2 Re(a b̄)." },
      { id: "polar", name: "Polar form", formula: "z = r(cos θ + i sin θ) = r e^(iθ)     |z₁z₂| = |z₁||z₂|     arg(z₁z₂) = arg z₁ + arg z₂", legend: ["r = |z|, θ = arg z"] },
      { id: "de-moivre", name: "De Moivre's theorem", formula: "(r e^(iθ))ⁿ = rⁿ e^(inθ)", legend: ["n = integer"] },
      { id: "omega", name: "Cube roots of unity", formula: "ω³ = 1     1 + ω + ω² = 0     ω = (−1 + i√3)/2", legend: ["ω = a non-real cube root of 1"], notes: "Reduce powers of ω by the exponent mod 3." },
      { id: "roots-of-unity", name: "n-th roots of unity", formula: "zⁿ = 1  ⇒  z = e^(2πik/n),   k = 0, 1, …, n − 1", legend: ["n ≥ 2"], notes: "Their sum is 0; they are vertices of a regular n-gon on the unit circle." },
      { id: "rotation", name: "Rotation", formula: "(z₃ − z₁)/(z₂ − z₁) = (|z₃ − z₁| / |z₂ − z₁|) e^(iθ)", legend: ["θ = angle at z₁ from z₂ to z₃"] },
      { id: "circle-locus", name: "Circle and distance range", formula: "|z − a| = r  ⇒  ||c − a| − r| ≤ |z − c| ≤ |c − a| + r", legend: ["a = centre, r = radius", "c = a fixed point"], notes: "z z̄ + ᾱz + αz̄ + d = 0 is a circle with centre −α and radius √(|α|² − d)." },
      { id: "arc-locus", name: "Arc from an argument", formula: "arg((z − a)/(z − b)) = θ  ⇒  arc of a circle with radius |a − b| / (2 sin θ)", legend: ["a, b = end points of the chord"], notes: "|z − z₁| + |z − z₂| = 2a > |z₁ − z₂| is an ellipse with foci z₁, z₂." },
    ],
  },
  {
    chapter: "Quadratic Equations",
    playbookSlug: "quadratic-equations",
    formulas: [
      { id: "roots", name: "Roots and discriminant", formula: "x = (−b ± √D)/(2a),   D = b² − 4ac", legend: ["ax² + bx + c = 0, a ≠ 0"], notes: "D > 0: real, distinct. D = 0: equal. D < 0: complex. Rational coefficients and D a perfect square: rational roots." },
      { id: "vieta", name: "Sum and product", formula: "α + β = −b/a     αβ = c/a     (α − β)² = (b² − 4ac)/a²", legend: ["α, β = roots"], notes: "The equation with roots α, β: x² − (α + β)x + αβ = 0." },
      { id: "vieta-cubic", name: "Cubic", formula: "α + β + γ = −b/a     αβ + βγ + γα = c/a     αβγ = −d/a", legend: ["ax³ + bx² + cx + d = 0"] },
      { id: "power-sums", name: "Power sums of the roots", formula: "α² + β² = (α + β)² − 2αβ     Pₙ = s Pₙ₋₁ − p Pₙ₋₂", legend: ["Pₙ = αⁿ + βⁿ", "s = α + β, p = αβ"] },
      { id: "location", name: "A number between the roots", formula: "α < k < β  ⇔  a f(k) < 0", legend: ["f(x) = ax² + bx + c"] },
      { id: "common-root", name: "One common root", formula: "(c₁a₂ − c₂a₁)² = (a₁b₂ − a₂b₁)(b₁c₂ − b₂c₁)", legend: ["a₁x² + b₁x + c₁ = 0 and a₂x² + b₂x + c₂ = 0"] },
      { id: "reciprocal", name: "Reciprocal substitution", formula: "x² + 1/x² = (x + 1/x)² − 2", legend: ["put t = x + 1/x"], notes: "logₐ b = 1/log_b a turns swapped-base equations into t + 1/t = k." },
      { id: "modulus-gif", name: "Modulus and greatest integer", formula: "|A + B| = |A| + |B|  ⇔  AB ≥ 0     [x] = n  ⇔  n ≤ x < n + 1", legend: ["[x] = greatest integer ≤ x", "n = integer"] },
    ],
  },
  {
    chapter: "Limits and Continuity",
    playbookSlug: "limits-and-continuity",
    formulas: [
      { id: "standard-limits", name: "Standard limits (x → 0)", formula: "sin x/x → 1     tan x/x → 1     (1 − cos x)/x² → ½     (eˣ − 1)/x → 1     ln(1 + x)/x → 1", legend: ["x in radians"], notes: "(aˣ − 1)/x → ln a." },
      { id: "one-infinity", name: "1 to the power ∞", formula: "lim f(x)^g(x) = e^(lim g(x)(f(x) − 1))", legend: ["f → 1, g → ∞"], notes: "lim (n → ∞) (1 + a/n)^(bn) = e^(ab)." },
      { id: "expansions", name: "Series expansions", formula: "sin x = x − x³/6 + …     cos x = 1 − x²/2 + x⁴/24 − …     eˣ = 1 + x + x²/2 + x³/6 + …     ln(1 + x) = x − x²/2 + x³/3 − …", legend: ["valid near x = 0"], notes: "For f(x)/xⁿ to have a finite limit, every coefficient below xⁿ must vanish." },
      { id: "leading-terms", name: "Limits at infinity", formula: "lim (x → ∞) (aₙxⁿ + …)/(bₙxⁿ + …) = aₙ/bₙ", legend: ["same degree n top and bottom"], notes: "Higher degree on top: ±∞. Higher degree below: 0." },
      { id: "conjugate", name: "Rationalising", formula: "√p − √q = (p − q)/(√p + √q)", legend: ["p, q ≥ 0"] },
      { id: "continuity", name: "Continuity at a point", formula: "lim (x → a⁻) f(x) = lim (x → a⁺) f(x) = f(a)", legend: ["a = the point tested"], notes: "Intermediate value theorem: f continuous and f(a) f(b) < 0 ⇒ a root in (a, b)." },
      { id: "gif-sandwich", name: "Greatest integer bounds", formula: "t − 1 < [t] ≤ t", legend: ["[t] = greatest integer ≤ t"], notes: "[g(x)] can break only where g(x) is an integer." },
      { id: "power-limit", name: "Powers in the limit", formula: "lim (n → ∞) x^(2n) = 0 if |x| < 1,   1 if |x| = 1,   ∞ if |x| > 1", legend: ["n = positive integer"] },
    ],
  },
  {
    chapter: "Straight Lines",
    playbookSlug: "straight-lines",
    formulas: [
      { id: "angle", name: "Angle between two lines", formula: "tan θ = |(m₁ − m₂)/(1 + m₁m₂)|", legend: ["m₁, m₂ = slopes"], notes: "Parallel: m₁ = m₂. Perpendicular: m₁m₂ = −1." },
      { id: "forms", name: "Forms of a line", formula: "intercept: x/a + y/b = 1     normal: x cos α + y sin α = p     parametric: (x − x₁)/cos θ = (y − y₁)/sin θ = r", legend: ["p = perpendicular distance from the origin", "r = distance from (x₁, y₁)"], notes: "Lines through the meet of L₁ = 0 and L₂ = 0: L₁ + λL₂ = 0." },
      { id: "distance", name: "Distances", formula: "point to line: |ax₁ + by₁ + c|/√(a² + b²)     parallel lines: |c₁ − c₂|/√(a² + b²)", legend: ["line: ax + by + c = 0"], notes: "Two points are on the same side when ax + by + c has the same sign at both." },
      { id: "triangle-area", name: "Area of a triangle", formula: "Δ = ½ |x₁(y₂ − y₃) + x₂(y₃ − y₁) + x₃(y₁ − y₂)|", legend: ["(xᵢ, yᵢ) = vertices"], notes: "Δ = 0 means the points are collinear." },
      { id: "foot-image", name: "Foot and image in a line", formula: "foot: (x − x₁)/a = (y − y₁)/b = −(ax₁ + by₁ + c)/(a² + b²)     image: same with −2(ax₁ + by₁ + c)/(a² + b²)", legend: ["line: ax + by + c = 0", "(x₁, y₁) = the point"] },
      { id: "bisectors", name: "Angle bisectors", formula: "(a₁x + b₁y + c₁)/√(a₁² + b₁²) = ±(a₂x + b₂y + c₂)/√(a₂² + b₂²)", legend: ["the two given lines"] },
      { id: "centres", name: "Centres of a triangle", formula: "centroid: ((x₁ + x₂ + x₃)/3, (y₁ + y₂ + y₃)/3)     incentre: (aA + bB + cC)/(a + b + c)", legend: ["a, b, c = side lengths opposite A, B, C"], notes: "Circumcentre: equidistant from the vertices. Orthocentre: where two altitudes meet." },
      { id: "pair-of-lines", name: "Pair of lines through the origin", formula: "ax² + 2hxy + by² = 0:   tan θ = 2√(h² − ab)/|a + b|", legend: ["θ = angle between the two lines"], notes: "Perpendicular when a + b = 0." },
    ],
  },
  {
    chapter: "Matrices",
    playbookSlug: "matrices",
    formulas: [
      { id: "algebra-rules", name: "Product and transpose rules", formula: "(AB)ᵀ = BᵀAᵀ     (AB)⁻¹ = B⁻¹A⁻¹     (A + B)² = A² + AB + BA + B²", legend: ["A, B = square matrices of the same order"], notes: "AB ≠ BA in general, so (A + B)² ≠ A² + 2AB + B²." },
      { id: "det-rules", name: "Determinant rules", formula: "|AB| = |A||B|     |Aᵀ| = |A|     |kA| = kⁿ|A|", legend: ["n = order of A"] },
      { id: "adjoint", name: "Adjoint identities", formula: "A(adj A) = |A| I     |adj A| = |A|^(n − 1)     adj(adj A) = |A|^(n − 2) A     adj(kA) = k^(n − 1) adj A", legend: ["n = order of A"], notes: "|adj(adj A)| = |A|^((n − 1)²)." },
      { id: "inverse", name: "Inverse", formula: "A⁻¹ = adj A / |A|   (|A| ≠ 0)     |A⁻¹| = 1/|A|", legend: ["A = square matrix"], notes: "PQ = kI ⇒ Q = kP⁻¹ and |Q| = kⁿ/|P|." },
      { id: "cayley-hamilton", name: "Cayley–Hamilton for 2 × 2", formula: "A² − (tr A) A + (det A) I = O     A⁻¹ = ((tr A) I − A)/det A", legend: ["tr A = sum of the diagonal"], notes: "A² = pA + qI ⇒ A³ = (p² + q)A + pqI." },
      { id: "powers", name: "Powers that collapse", formula: "A² = A  ⇒  (I + A)ⁿ = I + (2ⁿ − 1)A     A = I + N, N² = O  ⇒  Aⁿ = I + nN", legend: ["N = nilpotent part"], notes: "A^d = I ⇒ Aⁿ = A^(n mod d)." },
      { id: "symmetric-skew", name: "Symmetric and skew-symmetric", formula: "A = ½(A + Aᵀ) + ½(A − Aᵀ)     symmetric count: k^(n(n + 1)/2)     skew count: k^(n(n − 1)/2)", legend: ["first part symmetric, second skew-symmetric", "k = allowed entry values (skew needs 0 among them)"], notes: "A skew-symmetric matrix of odd order has determinant 0." },
      { id: "orthogonal", name: "Orthogonal matrix", formula: "AAᵀ = I  ⇒  A⁻¹ = Aᵀ,   |A| = ±1", legend: ["A = square matrix"] },
    ],
  },
  {
    chapter: "Determinants",
    playbookSlug: "determinants",
    formulas: [
      { id: "row-operations", name: "Row operations", formula: "Rᵢ → Rᵢ − kRⱼ: Δ unchanged     Rᵢ ↔ Rⱼ: sign changes     common factor of a row comes out", legend: ["the same rules hold for columns"], notes: "Two equal or proportional rows give Δ = 0." },
      { id: "vandermonde", name: "Vandermonde determinant", formula: "|1 a a²; 1 b b²; 1 c c²| = (a − b)(b − c)(c − a)", legend: ["rows separated by semicolons"] },
      { id: "symmetric-k", name: "A symmetric determinant", formula: "|k 1 1; 1 k 1; 1 1 k| = (k + 2)(k − 1)²", legend: ["rows separated by semicolons"] },
      { id: "cramer", name: "Cramer's rule", formula: "x = Δₓ/Δ     y = Δ_y/Δ     z = Δ_z/Δ     (Δ ≠ 0)", legend: ["Δₓ = Δ with the x-column replaced by the constants"] },
      { id: "three-cases", name: "Classifying a system", formula: "Δ ≠ 0: unique     Δ = 0 and some Δₓ, Δ_y, Δ_z ≠ 0: no solution     Δ = Δₓ = Δ_y = Δ_z = 0: infinitely many or none", legend: ["three equations in three unknowns"], notes: "In the last case, test whether one equation is a combination of the other two." },
      { id: "homogeneous", name: "Homogeneous system", formula: "AX = O has a non-zero solution  ⇔  |A| = 0", legend: ["A = coefficient matrix"] },
      { id: "product-adjoint", name: "Product and adjoint", formula: "|AB| = |A||B|     |kA| = kⁿ|A|     |adj A| = |A|^(n − 1)", legend: ["n = order"] },
      { id: "derivative", name: "Derivative of a determinant", formula: "d/dx Δ = sum of the determinants formed by differentiating one row at a time", legend: ["other rows stay unchanged in each term"] },
    ],
  },
  {
    chapter: "Statistics",
    playbookSlug: "statistics",
    formulas: [
      { id: "variance", name: "Variance from sums", formula: "σ² = Σx²/n − (Σx/n)²", legend: ["n = number of observations"] },
      { id: "frequency", name: "Frequency table", formula: "x̄ = Σfx/Σf     σ² = Σfx²/Σf − x̄²", legend: ["f = frequency of each value x"] },
      { id: "linear-change", name: "Linear change of data", formula: "y = ax + b  ⇒  ȳ = a x̄ + b,   σ_y² = a² σₓ²", legend: ["a, b = constants"], notes: "Adding a constant leaves the variance unchanged." },
      { id: "totals", name: "Totals from mean and variance", formula: "Σx = n x̄     Σx² = n(σ² + x̄²)", legend: ["x̄ = mean, σ² = variance"] },
      { id: "correction", name: "Correcting a wrong entry", formula: "Σx → Σx − w + c     Σx² → Σx² − w² + c²", legend: ["w = wrong value, c = correct value"], notes: "Fix both totals, then recompute the mean and variance." },
      { id: "combined-variance", name: "Combined variance", formula: "σ² = (n₁σ₁² + n₂σ₂²)/(n₁ + n₂) + n₁n₂(x̄₁ − x̄₂)²/(n₁ + n₂)²", legend: ["nᵢ, x̄ᵢ, σᵢ² = size, mean, variance of each group"] },
      { id: "mean-deviation", name: "Mean deviation", formula: "MD about a = (1/n) Σ |xᵢ − a|", legend: ["a = mean or median"], notes: "Mean deviation is least about the median." },
      { id: "two-unknowns", name: "Two unknown values", formula: "(a − b)² = 2(a² + b²) − (a + b)²", legend: ["a + b and a² + b² come from the totals"] },
    ],
  },
  {
    chapter: "Application of Derivatives",
    playbookSlug: "application-of-derivatives",
    formulas: [
      { id: "tangent-normal", name: "Tangent and normal", formula: "tangent: y − y₀ = f′(x₀)(x − x₀)     normal slope = −1/f′(x₀)", legend: ["(x₀, y₀) = point on the curve"] },
      { id: "rates", name: "Related rates", formula: "dV/dt = (dV/dr) · (dr/dt)", legend: ["V, r = linked quantities"] },
      { id: "monotonic", name: "Increasing and decreasing", formula: "f′(x) > 0 on I  ⇒  f increasing on I     f′(x) < 0 on I  ⇒  f decreasing on I", legend: ["I = interval"], notes: "ax² + bx + c ≥ 0 for all x when a > 0 and b² − 4ac ≤ 0." },
      { id: "extrema", name: "Local maxima and minima", formula: "f′(c) = 0 and f″(c) < 0: maximum     f′(c) = 0 and f″(c) > 0: minimum", legend: ["c = critical point: f′(c) = 0 or f′(c) does not exist"], notes: "For a cubic with positive leading coefficient, the maximum comes before the minimum." },
      { id: "closed-interval", name: "Greatest and least on [a, b]", formula: "max f = greatest of f(a), f(b), f(c) over the critical points c", legend: ["f continuous on [a, b]"] },
      { id: "mvt-rolle", name: "Mean value and Rolle's theorems", formula: "f′(c) = (f(b) − f(a))/(b − a),   c ∈ (a, b)     Rolle: f(a) = f(b)  ⇒  f′(c) = 0", legend: ["f continuous on [a, b], differentiable on (a, b)"], notes: "n zeros of f ⇒ at least n − 1 zeros of f′." },
      { id: "cubic-roots", name: "Roots of a cubic", formula: "f(x) = k has three distinct real roots when local min < k < local max", legend: ["f = cubic with two turning points"], notes: "f′ > 0 everywhere ⇒ f(x) = 0 has at most one root." },
      { id: "am-gm", name: "AM ≥ GM shortcut", formula: "a + b ≥ 2√(ab),   equality when a = b", legend: ["a, b > 0"] },
    ],
  },
  {
    chapter: "Trigonometric Identities",
    playbookSlug: "trigonometric-identities",
    formulas: [
      { id: "pythagorean", name: "Pythagorean identities", formula: "sin²x + cos²x = 1     1 + tan²x = sec²x     1 + cot²x = cosec²x", legend: ["x = any angle where defined"] },
      { id: "compound", name: "Compound angles", formula: "sin(A ± B) = sin A cos B ± cos A sin B     cos(A ± B) = cos A cos B ∓ sin A sin B", legend: ["A, B = angles"] },
      { id: "tan-sum", name: "Tangent of a sum", formula: "tan(A ± B) = (tan A ± tan B)/(1 ∓ tan A tan B)", legend: ["A, B = angles"] },
      { id: "multiple", name: "Double and triple angles", formula: "sin 2θ = 2 sin θ cos θ     cos 2θ = 1 − 2sin²θ = 2cos²θ − 1     sin 3θ = 3 sin θ − 4sin³θ     cos 3θ = 4cos³θ − 3 cos θ", legend: ["θ = angle"], notes: "sin 18° = (√5 − 1)/4, cos 36° = (√5 + 1)/4." },
      { id: "sum-product", name: "Sum to product", formula: "sin C + sin D = 2 sin((C + D)/2) cos((C − D)/2)     cos C + cos D = 2 cos((C + D)/2) cos((C − D)/2)", legend: ["C, D = angles"], notes: "cos C − cos D = −2 sin((C + D)/2) sin((C − D)/2)." },
      { id: "product-chains", name: "Product chains", formula: "cos θ cos 2θ cos 4θ … cos 2^(n − 1)θ = sin 2ⁿθ / (2ⁿ sin θ)     sin θ sin(60° − θ) sin(60° + θ) = ¼ sin 3θ", legend: ["n = number of cosine factors"], notes: "Likewise cos θ cos(60° − θ) cos(60° + θ) = ¼ cos 3θ." },
      { id: "power-sums", name: "Fourth and sixth powers", formula: "sin⁴θ + cos⁴θ = 1 − 2p     sin⁶θ + cos⁶θ = 1 − 3p", legend: ["p = sin²θ cos²θ = ¼ sin²2θ, so 0 ≤ p ≤ ¼"] },
      { id: "range", name: "Range of a sin θ + b cos θ", formula: "−√(a² + b²) ≤ a sin θ + b cos θ ≤ √(a² + b²)", legend: ["a, b = constants"] },
    ],
  },
  {
    chapter: "Inverse Trigonometric Functions",
    playbookSlug: "inverse-trigonometric-functions",
    formulas: [
      { id: "principal-ranges", name: "Domains and principal ranges", formula: "sin⁻¹: [−1, 1] → [−π/2, π/2]     cos⁻¹: [−1, 1] → [0, π]     tan⁻¹: all reals → (−π/2, π/2)     cot⁻¹: all reals → (0, π)", legend: ["sec⁻¹ and cosec⁻¹ need |x| ≥ 1"] },
      { id: "complementary", name: "Complementary pairs", formula: "sin⁻¹x + cos⁻¹x = π/2     tan⁻¹x + cot⁻¹x = π/2     sec⁻¹x + cosec⁻¹x = π/2", legend: ["x in the common domain of each pair"] },
      { id: "negatives", name: "Negative arguments", formula: "sin⁻¹(−x) = −sin⁻¹x     tan⁻¹(−x) = −tan⁻¹x     cos⁻¹(−x) = π − cos⁻¹x     cot⁻¹(−x) = π − cot⁻¹x", legend: ["x in the domain"] },
      { id: "addition", name: "Adding inverse tangents", formula: "tan⁻¹a + tan⁻¹b = tan⁻¹((a + b)/(1 − ab))   (ab < 1)", legend: ["a, b = reals"], notes: "If ab > 1 with a, b > 0, add π." },
      { id: "telescoping", name: "Telescoping term", formula: "tan⁻¹((b − a)/(1 + ab)) = tan⁻¹b − tan⁻¹a   (ab > −1)", legend: ["write each term of the series in this shape"] },
      { id: "double-tan", name: "2 tan⁻¹x", formula: "2 tan⁻¹x = sin⁻¹(2x/(1 + x²))  (|x| ≤ 1)  = cos⁻¹((1 − x²)/(1 + x²))  (x ≥ 0)  = tan⁻¹(2x/(1 − x²))  (|x| < 1)", legend: ["valid only in the stated ranges"] },
      { id: "principal-reduction", name: "Back into the principal range", formula: "sin⁻¹(sin x) = π − x  (π/2 ≤ x ≤ 3π/2)     cos⁻¹(cos x) = 2π − x  (π ≤ x ≤ 2π)", legend: ["sin⁻¹(sin x) = x only on [−π/2, π/2]"], notes: "tan⁻¹(tan x) = x − π for π/2 < x < 3π/2." },
      { id: "compositions", name: "Compositions to algebra", formula: "sin(tan⁻¹x) = x/√(1 + x²)     cos(tan⁻¹x) = 1/√(1 + x²)     cos(sin⁻¹x) = √(1 − x²)", legend: ["draw the right triangle for the inner angle"] },
    ],
  },
  {
    chapter: "Indefinite Integration",
    playbookSlug: "indefinite-integration",
    formulas: [
      { id: "standard-forms", name: "Standard forms", formula: "∫ dx/(x² + a²) = (1/a) tan⁻¹(x/a)     ∫ dx/(x² − a²) = (1/(2a)) ln|(x − a)/(x + a)|     ∫ dx/√(a² − x²) = sin⁻¹(x/a)     ∫ dx/√(x² ± a²) = ln|x + √(x² ± a²)|", legend: ["a > 0; add + C to each"], notes: "Complete the square to reach one of these." },
      { id: "power-rule", name: "Function and its derivative", formula: "∫ f′(x) [f(x)]ᵏ dx = [f(x)]^(k + 1)/(k + 1) + C  (k ≠ −1)     ∫ f′(x)/f(x) dx = ln|f(x)| + C", legend: ["f = inner function"] },
      { id: "by-parts", name: "Integration by parts", formula: "∫ u dv = uv − ∫ v du", legend: ["u = the part that simplifies on differentiating"] },
      { id: "ex-pattern", name: "The eˣ pattern", formula: "∫ eˣ (f(x) + f′(x)) dx = eˣ f(x) + C", legend: ["spot f and f′ side by side"], notes: "Reverse quotient rule: ∫ (u′v − uv′)/v² dx = u/v + C." },
      { id: "partial-fractions", name: "Partial fractions (cover-up)", formula: "(px + q)/((x − a)(x − b)) = A/(x − a) + B/(x − b),   A = (pa + q)/(a − b)", legend: ["B follows by swapping a and b"] },
      { id: "split-numerator", name: "Split the numerator", formula: "∫ (A g(x) + B g′(x))/g(x) dx = Ax + B ln|g(x)| + C", legend: ["write the numerator as A · denominator + B · its derivative"] },
      { id: "trig-tan", name: "a² sin²x + b² cos²x", formula: "∫ dx/(a² sin²x + b² cos²x) = (1/(ab)) tan⁻¹((a tan x)/b) + C", legend: ["divide by cos²x and put t = tan x"] },
      { id: "ratio-substitution", name: "Ratio substitution", formula: "∫ dx/((x − a)ᵖ (x + b)^(2 − p)) = (1/((a + b)(1 − p))) ((x − a)/(x + b))^(1 − p) + C", legend: ["p ≠ 1", "put t = (x − a)/(x + b)"] },
    ],
  },
  {
    chapter: "Differentiation",
    playbookSlug: "differentiation",
    formulas: [
      { id: "chain", name: "Chain rule", formula: "(g∘f)′(a) = g′(f(a)) · f′(a)", legend: ["both derivatives must exist"], notes: "f′(a) = lim (h → 0) (f(a + h) − f(a))/h." },
      { id: "inverse-function", name: "Derivative of an inverse", formula: "g′(k) = 1/f′(a),   where f(a) = k", legend: ["g = inverse of f"] },
      { id: "parametric", name: "Parametric derivatives", formula: "dy/dx = (dy/dt)/(dx/dt)     d²y/dx² = [d/dt (dy/dx)] ÷ (dx/dt)", legend: ["t = parameter"], notes: "The second derivative is NOT (d²y/dt²)/(d²x/dt²)." },
      { id: "variable-power", name: "Variable power", formula: "d/dx (f^g) = f^g (g′ ln f + g f′/f)", legend: ["f > 0"], notes: "Take logs first: ln y = g ln f." },
      { id: "inverse-trig-sub", name: "A standard substitution", formula: "x = tan θ:   tan⁻¹(2x/(1 − x²)) = 2 tan⁻¹x   (|x| < 1)", legend: ["derivative is then 2/(1 + x²)"] },
      { id: "functional", name: "Derivative from a functional equation", formula: "f(x + y) = f(x) f(y)  ⇒  f′(x) = f′(0) f(x)", legend: ["found from the limit definition"] },
      { id: "smooth-join", name: "Smooth join", formula: "f₁(a) = f₂(a)  and  f₁′(a) = f₂′(a)", legend: ["f₁, f₂ = the pieces meeting at x = a"], notes: "The first condition gives continuity, the second differentiability." },
      { id: "corner", name: "Corners from a modulus", formula: "k|x − a|:   f′(a⁺) − f′(a⁻) = 2k", legend: ["k ≠ 0"], notes: "f is not differentiable at a unless the corner terms cancel." },
    ],
  },
  {
    chapter: "Trigonometric Equations",
    playbookSlug: "trigonometric-equations",
    formulas: [
      { id: "general-solutions", name: "General solutions", formula: "sin θ = sin α  ⇒  θ = nπ + (−1)ⁿα     cos θ = cos α  ⇒  θ = 2nπ ± α     tan θ = tan α  ⇒  θ = nπ + α", legend: ["n = any integer"] },
      { id: "squares", name: "Squared equations", formula: "sin²θ = sin²α,  cos²θ = cos²α  or  tan²θ = tan²α  ⇒  θ = nπ ± α", legend: ["n = any integer"] },
      { id: "roots-in-order", name: "Roots of cos θ = c in order", formula: "α, 2π − α, 2π + α, 4π − α, …", legend: ["α = cos⁻¹c, 0 < α < π"], notes: "Count roots in an interval by listing them this way." },
      { id: "auxiliary-angle", name: "Auxiliary angle", formula: "a cos x + b sin x = √(a² + b²) cos(x − φ),   tan φ = b/a", legend: ["a, b = constants"], notes: "a cos x + b sin x = c has a solution exactly when |c| ≤ √(a² + b²)." },
      { id: "existence", name: "Existence of a solution", formula: "f(x) = k has a solution  ⇔  min f ≤ k ≤ max f", legend: ["f continuous"] },
      { id: "forced-equality", name: "Forced equality", formula: "f(x) ≤ m ≤ g(x) for all x:   f(x) = g(x)  ⇔  f(x) = g(x) = m", legend: ["m = a common bound"], notes: "Typical case: sin x + cos y = 2 forces sin x = cos y = 1." },
      { id: "triple-angle", name: "Triple angles", formula: "cos 3x = 4cos³x − 3 cos x     tan 3x = (3 tan x − tan³x)/(1 − 3tan²x)", legend: ["x = angle"] },
      { id: "substitution", name: "Exponent substitution", formula: "t = a^(sin²x):   a^(sin²x) + a^(cos²x) = t + a/t", legend: ["a > 0"], notes: "Then 1 ≤ t ≤ a (for a > 1) and the equation is a quadratic in t." },
    ],
  },
];

export const FORMULA_STATS = {
  formulas: FORMULA_GROUPS.reduce((s, g) => s + g.formulas.length, 0),
  chapters: FORMULA_GROUPS.length,
};
