"""Draw the PYQ Vault watermark used on pass downloads of the Word paper.

Writes src/lib/export/watermark.generated.ts: the PNG as base64, plus its
pixel size. Generated and committed (not drawn at request time) so the export
route needs no image library and no file read. Re-run after changing the look:

    python scripts/export/make-watermark.py

The text is drawn already TILTED, rather than rotated by Word, because Google
Docs and WPS may ignore a rotation on an anchored picture. Faintness comes from
the PNG's alpha, so it stays light on any page colour and when printed.
"""
import base64
import io
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

TEXT = "PYQ Vault"
FONT = "C:/Windows/Fonts/arialbd.ttf"
FONT_PX = 220
ANGLE = 45          # degrees, counter-clockwise: bottom-left to top-right
ALPHA = 31          # of 255, about 12% black -> a light grey on white

font = ImageFont.truetype(FONT, FONT_PX)
left, top, right, bottom = font.getbbox(TEXT)
pad = 20
canvas = Image.new("RGBA", (right - left + 2 * pad, bottom - top + 2 * pad), (0, 0, 0, 0))
ImageDraw.Draw(canvas).text((pad - left, pad - top), TEXT, font=font, fill=(0, 0, 0, ALPHA))
tilted = canvas.rotate(ANGLE, resample=Image.BICUBIC, expand=True)
tilted = tilted.crop(tilted.getbbox())

buf = io.BytesIO()
tilted.save(buf, format="PNG", optimize=True)
b64 = base64.b64encode(buf.getvalue()).decode("ascii")
w, h = tilted.size

out = Path(__file__).resolve().parents[2] / "src/lib/export/watermark.generated.ts"
out.write_text(
    "// GENERATED by scripts/export/make-watermark.py — do not edit by hand.\n"
    "// The PYQ Vault watermark on pass downloads of the Word paper (2026-10-01).\n"
    f"export const WATERMARK_PNG_BASE64 =\n  \"{b64}\";\n"
    f"export const WATERMARK_PX = {{ width: {w}, height: {h} }} as const;\n",
    encoding="utf-8",
    newline="\n",
)
print(f"wrote {out.name}: {w}x{h}px, {len(buf.getvalue())} bytes")
