import type { SubtopicNote } from "@/app/notes/_types";

export const NUCLEAR_PHYSICS_NOTE: SubtopicNote = {
  subtopicName: "Nuclear Physics",
  title: "Nuclear Physics: Fission, Fusion, and Reactors",
  oneLineDefinition:
    "The nucleus stores enormous energy released by fission (splitting heavy nuclei) or fusion (joining light nuclei); reactors use controlled fission, and Einstein's E = mc² ties the released energy to lost mass.",
  whyItMatters:
    "Five PYQs here, mostly EASY recall plus one MODERATE. " +
    "The NDA tests the source of nuclear energy (fission, with E = mc² from Einstein), the principle of a reactor (CONTROLLED fission), the fuel (uranium minerals like pitchblende), and how radioactivity is measured (GM counter). " +
    "Know fission vs fusion cold — they are the most-swapped distractors in the subtopic.",
  concepts: [
    // Concept 1 — fission, fusion, E=mc2
    {
      kind: "formula" as const,
      slug: "fission-fusion-mass-energy",
      name: "Nuclear energy — fission, fusion, and E = mc²",
      intuition:
        "A heavy nucleus like uranium can split into lighter pieces (fission), or very light nuclei like hydrogen can join into a heavier one (fusion). " +
        "Either way, the products weigh slightly LESS than the starting material, and that lost mass becomes energy through Einstein's E = mc². " +
        "Because c² is huge, even a speck of lost mass releases enormous energy.",
      definition:
        "Nuclear energy comes from a tiny loss of mass converted to energy:\n" +
        "- **Fission** — a heavy nucleus (e.g. uranium-235) SPLITS into lighter nuclei, releasing energy. This is what power-reactor energy comes from.\n" +
        "- **Fusion** — light nuclei (e.g. hydrogen isotopes) JOIN into a heavier nucleus, releasing even more energy. This powers the Sun and the hydrogen bomb.\n" +
        "- **Einstein's mass-energy equivalence** \\(E = mc^2\\) gives the energy released for the mass lost.",
      formula: {
        label: "Mass-energy equivalence",
        latex: "E = mc^2",
        symbols: [
          { symbol: "E", meaning: "energy released (J)" },
          { symbol: "m", meaning: "mass lost / converted (kg)" },
          { symbol: "c", meaning: "speed of light, 3 x 10⁸ m/s" },
        ],
      },
      authoredExample: {
        prompt:
          "Nuclear energy in a power reactor is generated by which process, and whose equation expresses the energy released?",
        steps: [
          "Reactor energy comes from splitting heavy nuclei — nuclear fission.",
          "The energy released equals the lost mass times \\(c^2\\), expressed by Einstein's \\(E = mc^2\\).",
        ],
        answer: "Nuclear fission; the energy is expressed by Einstein's E = mc².",
      },
      selfCheckExample: {
        prompt:
          "Which process powers the Sun — fission or fusion — and which joins nuclei together?",
        steps: [
          "The Sun fuses hydrogen nuclei into helium, releasing energy.",
          "Joining nuclei is fusion (fission is the splitting process).",
        ],
        answer: "Fusion powers the Sun; fusion is the process that joins nuclei.",
      },
      practiceSet: [
        { prompt: "Reactor energy is generated by fission or fusion?", answer: "Fission" },
        { prompt: "Whose equation gives the energy released in nuclear reactions?", answer: "Einstein's (E = mc²)" },
        { prompt: "Splitting a heavy nucleus is called?", answer: "Fission" },
        { prompt: "Joining light nuclei is called?", answer: "Fusion" },
      ],
      pyqExampleId: "99e8bbbd-3521-427b-8283-0ff8891b52f2", // 2021 MOD — fission + Einstein
      traps: [
        {
          title: "Fission splits, fusion joins — and reactors use fission",
          body:
            "Power reactors run on controlled FISSION (splitting uranium). FUSION (joining light nuclei) powers stars and is not yet a practical power source. Distractors swap these and also attach the wrong scientist (E = mc² is Einstein, not Rutherford/Bohr).",
        },
      ],
    },

    // Concept 2 — nuclear reactor
    {
      kind: "reference" as const,
      slug: "nuclear-reactor",
      name: "The nuclear reactor — controlled fission and its parts",
      intuition:
        "A reactor releases nuclear energy at a steady, safe rate by keeping the fission chain reaction CONTROLLED, not explosive. " +
        "It does this with a few key parts: fuel (uranium), a moderator to slow neutrons, control rods to absorb excess neutrons, and a coolant to carry heat away. " +
        "The exam asks for the basic principle (controlled fission) and which item does NOT belong.",
      definition:
        "A **nuclear reactor** generates power by **controlled nuclear fission** — a self-sustaining chain reaction held at a steady rate. Core parts:\n" +
        "- **Fuel** — fissile material (uranium-235, plutonium-239).\n" +
        "- **Moderator** — slows neutrons (graphite, heavy water).\n" +
        "- **Control rods** — absorb neutrons to control the rate (cadmium, boron).\n" +
        "- **Coolant** — carries heat away to make steam.",
      table: {
        columns: ["Reactor component", "Role"],
        rows: [
          { cells: ["Fuel (uranium-235)", "Undergoes fission to release energy"] },
          { cells: ["Moderator (graphite, heavy water)", "Slows down fast neutrons"] },
          { cells: ["Control rods (cadmium, boron)", "Absorb neutrons to control the reaction rate"] },
          { cells: ["Coolant", "Removes heat from the core"] },
          {
            cells: ["A mechanism to reduce CO₂ emission", "Does NOT belong to a reactor"],
            noteAmber: "NDA 2024 — the item that does NOT belong to a nuclear reactor is \"a mechanism to reduce CO₂ emission\" (reactors emit no CO₂ in the first place).",
          },
        ],
        caption:
          "Principle = controlled fission. The odd-one-out trap is the CO₂-reduction mechanism — nuclear power produces no CO₂, so no such part exists.",
      },
      selfCheckExample: {
        prompt:
          "What is the basic scientific principle behind a nuclear reactor?",
        steps: [
          "A reactor releases nuclear energy steadily, not explosively.",
          "It does so by holding a fission chain reaction at a constant, controlled rate.",
        ],
        answer: "Controlled nuclear fission.",
      },
      practiceSet: [
        { prompt: "Basic principle behind a nuclear reactor?", answer: "Controlled nuclear fission" },
        { prompt: "What do control rods (cadmium, boron) do in a reactor?", answer: "Absorb neutrons to control the reaction rate" },
        { prompt: "What does a moderator do?", answer: "Slows down neutrons" },
        { prompt: "Which item does NOT belong to a nuclear reactor: fuel, moderator, control rods, or a CO₂-reduction mechanism?", answer: "A CO₂-reduction mechanism" },
      ],
      pyqExampleId: "99a8f14b-cb90-4928-bd13-d2d9e25cd657", // 2019 — controlled nuclear fission
      traps: [
        {
          title: "Reactor = CONTROLLED fission (a bomb is uncontrolled)",
          body:
            "The reactor's whole point is keeping fission controlled and steady. An uncontrolled fission chain reaction is an atomic bomb. The exam answer for a reactor is always \"controlled fission.\"",
        },
      ],
    },

    // Concept 3 — fuel, radioactivity measurement, radiation types
    {
      kind: "reference" as const,
      slug: "fuel-and-radioactivity",
      name: "Nuclear fuel, measuring radioactivity, and radiation types",
      intuition:
        "Reactors burn uranium, which is mined from minerals such as pitchblende. " +
        "Radioactivity — the spontaneous emission of radiation from unstable nuclei — is measured with a Geiger-Müller (GM) counter. " +
        "The radiation comes in three flavours: alpha, beta, and gamma, ranked by penetrating power gamma > beta > alpha.",
      definition:
        "Recall facts for fuel, detection, and radiation:\n" +
        "- **Nuclear fuel mineral** — uranium is obtained from **pitchblende** (a uranium ore).\n" +
        "- **Radioactivity is measured by a GM (Geiger-Müller) counter**.\n" +
        "- **Radiation types**: alpha (helium nucleus, +2), beta (electron, -1), gamma (high-energy EM, no charge). **Penetrating power: gamma > beta > alpha**; **ionising power is the reverse: alpha > beta > gamma**.",
      visualizationSlug: "mp-radiation-penetration",
      table: {
        columns: ["Radiation", "What it is", "Stopped by"],
        rows: [
          {
            cells: ["**Alpha (α)**", "Helium nucleus (2 protons + 2 neutrons), charge +2", "A sheet of paper"],
            noteAmber: "Most ionising, least penetrating.",
          },
          { cells: ["**Beta (β)**", "Fast electron, charge -1", "A few mm of aluminium"] },
          {
            cells: ["**Gamma (γ)**", "High-energy electromagnetic wave, no charge", "Thick lead or concrete"],
            noteAmber: "Least ionising, most penetrating.",
          },
        ],
        caption:
          "Penetration: γ > β > α. Ionising power: α > β > γ. Alpha is stopped by paper; gamma needs thick lead.",
      },
      selfCheckExample: {
        prompt:
          "Radioactivity is measured by which instrument, and which mineral supplies nuclear fuel?",
        steps: [
          "Radioactivity (radiation from unstable nuclei) is detected and measured with a Geiger-Müller (GM) counter.",
          "Uranium fuel is mined from pitchblende ore.",
        ],
        answer: "A GM counter measures radioactivity; pitchblende is the fuel mineral.",
      },
      practiceSet: [
        { prompt: "Radioactivity is measured by which instrument?", answer: "GM (Geiger-Müller) counter" },
        { prompt: "Which mineral is used as nuclear fuel?", answer: "Pitchblende", method: "a uranium ore" },
        { prompt: "Which radiation has the greatest penetrating power: alpha, beta, or gamma?", answer: "Gamma" },
        { prompt: "Which radiation is stopped by a sheet of paper?", answer: "Alpha" },
      ],
      pyqExampleId: "0cd920e7-c909-43b9-84cd-a0769d87a91c", // 2017 — radioactivity GM counter
      traps: [
        {
          title: "Penetration and ionising power run OPPOSITE ways",
          body:
            "Gamma penetrates most but ionises least; alpha penetrates least (stopped by paper) but ionises most. Mixing up the two rankings is the classic radiation trap.",
        },
        {
          title: "Pitchblende, not coal or limestone",
          body:
            "Nuclear fuel comes from uranium ores such as pitchblende. Coal/petroleum are chemical (fossil) fuels, not nuclear. The exam answer for nuclear fuel mineral is pitchblende.",
        },
      ],
    },
  ],
};
