import type { SubtopicNote } from "@/app/notes/_types";

export const QUANTUM_AND_MODERN_EM_NOTE: SubtopicNote = {
  subtopicName: "Quantum and Modern EM",
  title: "Quantum and Modern EM: X-rays, Semiconductors, Scattering",
  oneLineDefinition:
    "A grab-bag of modern applications: X-rays (high-energy EM made by stopping fast electrons), semiconductors (p-type and n-type materials that follow Ohm's law), and the Raman effect (light changing frequency when scattered).",
  whyItMatters:
    "Five PYQs, a mix of EASY and MODERATE. " +
    "The NDA tests the properties and uses of X-rays (and what they are NOT used for — radar), the charge carriers and I-V behaviour of semiconductors, and the names of scattering phenomena (Raman effect). " +
    "Each is a one-fact or one-step question once you know the definitions.",
  concepts: [
    // Concept 1 — X-rays
    {
      kind: "reference" as const,
      slug: "x-rays-properties",
      name: "X-rays — properties and uses",
      intuition:
        "X-rays are high-energy electromagnetic radiation with very short wavelengths (about 1 angstrom). " +
        "They are produced by slamming high-speed electrons into a metal target. " +
        "Their short wavelength lets them pass through soft tissue (medical imaging) and treat cancer, but they are NOT used for radar — radar uses long radio/microwaves.",
      definition:
        "**X-rays** are short-wavelength, high-energy electromagnetic waves:\n" +
        "- **Wavelength** about \\(1\\ \\text{Å} = 10^{-10}\\) m.\n" +
        "- **Produced** by bombarding a metal target with high-energy electrons.\n" +
        "- **Uses**: medical imaging (bone scans), cancer treatment (radiotherapy), security scanning, crystal structure study.\n" +
        "- **NOT used for radar** — radar relies on long-wavelength radio/microwaves, not short X-ray wavelengths.\n" +
        "- The dimensions of **Planck's constant** \\(h = E/f\\) are those of **angular momentum** (J·s).",
      table: {
        columns: ["Statement about X-rays", "True or false"],
        rows: [
          { cells: ["Wavelength about 1 Å", "True"] },
          { cells: ["Generated by bombarding a metal target with high-energy electrons", "True"] },
          {
            cells: ["Used for radar systems because of their short wavelength", "FALSE"],
            noteAmber: "NDA 2023 — the false statement is that X-rays are used for radar. Radar uses long radio/microwaves, not X-rays.",
          },
          { cells: ["Used to treat certain cancers", "True"] },
        ],
        caption:
          "Everything about X-rays is true EXCEPT the radar claim. Radar = radio/microwave, not X-ray.",
      },
      selfCheckExample: {
        prompt:
          "Which statement about X-rays is NOT true: (i) wavelength about 1 Å, (ii) used for radar, (iii) used to treat cancer?",
        steps: [
          "Wavelength about 1 Å is correct — (i) true.",
          "Radar uses long radio/microwaves, not short X-rays — (ii) is false.",
          "X-rays are used in radiotherapy — (iii) true.",
        ],
        answer: "Statement (ii) is not true — X-rays are not used for radar.",
      },
      practiceSet: [
        { prompt: "X-rays are produced by bombarding a metal target with what?", answer: "High-energy electrons" },
        { prompt: "Are X-rays used for radar?", answer: "No", method: "radar uses radio/microwaves" },
        { prompt: "Approximate wavelength of X-rays?", answer: "About 1 Å (10⁻¹⁰ m)" },
        { prompt: "The dimensions of Planck's constant h match which quantity?", answer: "Angular momentum", method: "[h] = J·s" },
      ],
      pyqExampleId: "4df3bfff-b08a-4d82-b795-9f51cd9ab196", // 2023 MOD — X-rays not-true radar
      traps: [
        {
          title: "X-rays for radar is the WRONG statement",
          body:
            "Radar needs long wavelengths that reflect off aircraft and ships — radio waves and microwaves. X-rays have wavelengths far too short for radar. Any option pairing X-rays with radar is false.",
        },
      ],
    },

    // Concept 2 — h dimensions (formula)
    {
      kind: "formula" as const,
      slug: "plancks-constant-dimensions",
      name: "Dimensions of Planck's constant — same as angular momentum",
      intuition:
        "Planck's constant h links a photon's energy to its frequency through E = hf. " +
        "Rearranging, h = E/f, which is energy divided by frequency — energy times time. " +
        "Energy times time happens to be exactly the dimensions of angular momentum, so h carries the SI unit J·s.",
      definition:
        "From \\(E = hf\\), Planck's constant is \\(h = E/f\\):\n" +
        "- Dimensionally, \\([h] = \\dfrac{[\\text{energy}]}{[\\text{frequency}]} = \\dfrac{\\text{J}}{\\text{s}^{-1}} = \\text{J}\\cdot\\text{s}\\).\n" +
        "- J·s = (kg·m²/s²)·s = kg·m²/s = **angular momentum** (also the unit of action).\n" +
        "- So \\(h\\) has the **same dimensions as angular momentum**, not linear momentum or torque.",
      formula: {
        label: "Dimensions of Planck's constant",
        latex: "[h] = \\dfrac{[E]}{[f]} = \\text{J}\\cdot\\text{s} = [\\text{angular momentum}]",
        symbols: [
          { symbol: "h", meaning: "Planck's constant" },
          { symbol: "E", meaning: "energy (J)" },
          { symbol: "f", meaning: "frequency (Hz = s⁻¹)" },
        ],
      },
      authoredExample: {
        prompt:
          "The energy of a photon is E = hf. The dimensions of h are the same as those of which physical quantity?",
        steps: [
          "Rearrange: \\(h = E/f\\).",
          "Units: \\(\\text{J} / \\text{s}^{-1} = \\text{J}\\cdot\\text{s}\\).",
          "J·s = kg·m²/s, which is the unit of angular momentum.",
        ],
        answer: "Angular momentum.",
      },
      selfCheckExample: {
        prompt:
          "Is the SI unit of Planck's constant J·s or J/s, and which quantity shares it?",
        steps: [
          "From \\(h = E/f\\), unit is energy per frequency = J / s⁻¹ = J·s (not J/s).",
          "J·s is the unit of angular momentum.",
        ],
        answer: "J·s, the same unit as angular momentum.",
      },
      practiceSet: [
        { prompt: "Dimensions of Planck's constant h match which quantity?", answer: "Angular momentum" },
        { prompt: "SI unit of Planck's constant?", answer: "J·s (joule-second)" },
        { prompt: "From E = hf, h equals?", answer: "\\(E/f\\)" },
        { prompt: "Does h have the dimensions of torque?", answer: "No", method: "torque is N·m = J, not J·s" },
      ],
      pyqExampleId: "e9601a61-7b6d-4c05-bdd6-69284c00da95", // 2025 MOD — h dimensions angular momentum
      traps: [
        {
          title: "h is angular momentum, not linear momentum or torque",
          body:
            "J·s = angular momentum. Linear momentum is kg·m/s; torque is N·m = J (no extra second). Only angular momentum (and action) matches J·s.",
        },
      ],
    },

    // Concept 3 — semiconductors
    {
      kind: "reference" as const,
      slug: "semiconductors",
      name: "Semiconductors — p-type, n-type, and the I-V graph",
      intuition:
        "A pure semiconductor like silicon conducts a little. Doping it with impurities makes it n-type (extra electrons) or p-type (extra 'holes', i.e. missing electrons). " +
        "A plain rectangular wafer of semiconductor still obeys Ohm's law — its current-voltage graph is a straight line through the origin. " +
        "Charge carriers and the I-V shape are the two facts tested.",
      definition:
        "Semiconductor recall facts:\n" +
        "- **n-type**: doped to have extra free **electrons** as the majority carriers.\n" +
        "- **p-type**: doped to have extra **holes** (missing electrons, behaving as positive carriers) as the majority carriers.\n" +
        "- A simple **rectangular semiconductor wafer follows Ohm's law**: its current-voltage (I-V) graph is a **straight line through the origin** (linear in both positive and negative quadrants).",
      table: {
        columns: ["Type", "Majority charge carriers", "Created by doping with"],
        rows: [
          {
            cells: ["**p-type**", "Holes (positive)", "Trivalent impurity (e.g. boron)"],
            noteAmber: "NDA 2017 — the majority charge carriers in a p-type semiconductor are holes.",
            pyqExampleId: "3b2d6b94-4dd0-4c34-a6b9-5a89d8aaa989",
          },
          { cells: ["**n-type**", "Electrons (negative)", "Pentavalent impurity (e.g. phosphorus)"] },
        ],
        caption:
          "p-type = holes (positive). n-type = electrons (negative). A plain wafer's I-V graph is a straight line through the origin.",
      },
      selfCheckExample: {
        prompt:
          "What is the shape of the current-voltage (I-V) graph for a rectangular piece of semiconductor wafer?",
        steps: [
          "A plain rectangular wafer is a simple resistive material — it obeys Ohm's law, \\(I \\propto V\\).",
          "A directly-proportional relation is a straight line passing through the origin, in both the positive and negative quadrants.",
        ],
        answer: "A straight line through the origin (linear in both quadrants).",
      },
      practiceSet: [
        { prompt: "Majority charge carriers in a p-type semiconductor?", answer: "Holes" },
        { prompt: "Majority charge carriers in an n-type semiconductor?", answer: "Electrons" },
        { prompt: "I-V graph of a plain semiconductor wafer?", answer: "Straight line through the origin", method: "obeys Ohm's law" },
        { prompt: "p-type is made by doping with a trivalent or pentavalent impurity?", answer: "Trivalent" },
      ],
      pyqExampleId: "4ec34ad1-5815-46b8-b33e-e350dfa41151", // 2023 MOD — I-V semiconductor wafer linear
      traps: [
        {
          title: "p-type carriers are HOLES (positive), n-type are electrons",
          body:
            "The letters track the carrier sign: p = positive (holes), n = negative (electrons). Distractors swap them. A plain wafer is still ohmic — linear I-V, not a diode curve.",
        },
      ],
    },

    // Concept 4 — Raman effect
    {
      kind: "reference" as const,
      slug: "raman-and-scattering",
      name: "Scattering phenomena — the Raman effect",
      intuition:
        "When light passes through a transparent substance, most of it scatters without changing colour (Rayleigh scattering). " +
        "But a small part comes out with a SHIFTED frequency because it exchanged energy with the molecules — this frequency change is the Raman effect, discovered by C. V. Raman. " +
        "The exam tests the name that matches 'scattered light with changed frequency'.",
      definition:
        "Named scattering phenomena:\n" +
        "- **Raman effect** — when light is scattered by a molecule and its **frequency CHANGES** (energy exchanged with the molecule). Discovered by **C. V. Raman** (Nobel Prize 1930).\n" +
        "- **Rayleigh scattering** — scattering WITHOUT a frequency change (makes the sky blue).\n" +
        "- Do not confuse with the **photoelectric effect** (electron emission) or **Rutherford scattering** (alpha particles off nuclei).",
      table: {
        columns: ["Phenomenon", "What happens"],
        rows: [
          {
            cells: ["**Raman effect**", "Scattered light's frequency CHANGES (inelastic scattering)"],
            noteAmber: "NDA 2021 — light scattered with a changed frequency is the Raman effect.",
          },
          { cells: ["**Rayleigh scattering**", "Scattering with NO frequency change (elastic)"] },
          { cells: ["**Photoelectric effect**", "Light ejects electrons from a metal — not scattering"] },
          { cells: ["**Rutherford scattering**", "Alpha particles scatter off atomic nuclei"] },
        ],
        caption:
          "Frequency CHANGES = Raman. No change = Rayleigh. The other two are different phenomena entirely.",
      },
      selfCheckExample: {
        prompt:
          "Light scattered by a molecule comes out with a changed frequency. Name this phenomenon and its discoverer.",
        steps: [
          "A frequency change on scattering means energy was exchanged with the molecule — inelastic scattering.",
          "This is the Raman effect, discovered by C. V. Raman.",
        ],
        answer: "The Raman effect, discovered by C. V. Raman.",
      },
      practiceSet: [
        { prompt: "Scattered light with a changed frequency is called what?", answer: "Raman effect" },
        { prompt: "Who discovered the Raman effect?", answer: "C. V. Raman" },
        { prompt: "Scattering with NO frequency change is called?", answer: "Rayleigh scattering" },
        { prompt: "Which scattering makes the sky appear blue?", answer: "Rayleigh scattering" },
      ],
      pyqExampleId: "588e41fe-9ae2-404c-aae7-d761f53ad3c5", // 2021 MOD — Raman effect
      traps: [
        {
          title: "Raman = frequency CHANGES; Rayleigh = no change",
          body:
            "The defining feature of the Raman effect is a SHIFT in the scattered light's frequency. Rayleigh scattering leaves frequency unchanged. The wording \"frequency is changed\" points to Raman.",
        },
      ],
    },
  ],
};
