import type { ChapterNote } from "@/app/notes/_types";

export const CONICS_CHAPTER: ChapterNote = {
  chapterName: "Conics",
  title: "Conics — NDA Maths",
  intro:
    "Conics — parabola, ellipse, hyperbola — are one family generated by slicing a cone, unified by a single number: the eccentricity. 38 PYQs span 2017–2026, and almost every one is a matter of reading the standard form, then reading off a focus, directrix, eccentricity, or latus rectum. " +
    "The notes teach in four movements, foundations first: " +
    "(1) Conic Sections — the focus–directrix definition, what eccentricity means, how it classifies each curve, and how to identify a general second-degree equation; " +
    "(2) Parabola — the standard forms y² = 4ax (and its rotations), vertex/focus/directrix, the latus rectum, the focal distance, and tangents/chords; " +
    "(3) Ellipse — the standard form, foci and eccentricity (c² = a² − b²), the defining sum of focal distances, and finding the equation from given data; " +
    "(4) Hyperbola — the standard form, foci and eccentricity (c² = a² + b²), and its parametric description. " +
    "Fix the standard form and orientation first; everything else is a formula. Every PYQ is tagged.",
  subtopicOrder: [
    "conics-identification",
    "conics-parabola",
    "conics-ellipse",
    "conics-hyperbola",
  ],
};
