// Shared config for the Pariksha (Vidhya Vikashni coaching-test) ingestion pipeline.
//
// Source: ParikshaGruh print-question-paper PDFs under SOURCE_ROOT (c:\tmp\pariksha),
// generated by Vidhya Vikashni Mat. Hr. Sec. School (Tiruppur) — a NEET coaching centre.
// These are COACHING PRACTICE tests, NOT past-year papers → they land under the existing
// NEET exam with question_kind='practice' (kept off the PYQ surfaces by that axis), reusing
// NEET's Physics/Chemistry/Botany/Zoology subjects + the NCERT chapter catalog.
//
// Format quirks (see README.md):
//   • Image-based — the text layer holds only question numbers; stems/options/figures are
//     rendered as image fragments → VISION transcription (like NEET/Foundation).
//   • Two-up layout — each PDF page holds TWO logical print-pages side by side (footer
//     "1/11", "2/11"). render.ts splits each PDF page into a LEFT and RIGHT logical page.
//   • Answer keys — the "+"/answer files print `Answer : X` in the TEXT layer, one per
//     question, in continuous 1..N order across sections. extract-keys.ts pulls these
//     verbatim (exact, no vision needed). 7 tests have NO key → answers derived + flagged.
//   • Filenames are noisy (duplicates + a couple mislabels); this registry pins ONE
//     canonical file per Test Id.
import { join } from "node:path";

// LWS Pune org + admin (same as the NEET/CDS/JEE/practice pipelines).
export const ORG_ID = "5d528776-1263-4d77-bc12-f2836fd6073f";
export const CREATED_BY = "28528215-c968-40bf-abac-acdc19cc306f";
export const EXAM_ID = "01d193e7-74cf-4dd0-83b5-ef98ee221e67"; // NEET

export const SOURCE_ROOT = "C:\\tmp\\pariksha";
export const OUT = join(__dirname, "out"); // gitignored: rendered PNGs
export const DATA = join(__dirname, "data"); // committed: per-test transcription JSON

export type Subject = "Physics" | "Chemistry" | "Botany" | "Zoology";

export type Test = {
  id: string; // slug = ParikshaGruh Test Id; used for data/<id>.* + display
  sourceFile: string; // questions.source_file + upload_jobs.filename (dedup/rollback key) — STABLE per test
  pdf: string; // absolute path to the ONE canonical file we render (prefer the answer copy)
  questionCount: number;
  hasKey: boolean; // official `Answer : X` present in the text layer → keys extracted, else derived+flagged
  subjects: Subject[]; // subjects present; 1 for a topic test, 4 for a full mock
  chapterHint?: string; // whole-test NCERT chapter when the title names a topic (one of NEET_CHAPTERS[subject])
  note: string; // pyqNote-style provenance: source title (+ Test Id)
};

// One entry per unique ParikshaGruh Test Id (30 total). `pdf` is the canonical copy —
// the "+"/answer file when a key exists, else the plain QP. Duplicates/mislabels in the
// source dir (e.g. 76.pdf, 7+.pdf are extra copies of 13179) are intentionally ignored.
export const TESTS: Record<string, Test> = {
  // ── Full 4-section NEET mocks (Physics·Chemistry·Botany·Zoology, 45 each) ──
  "13307": { id: "13307", sourceFile: "PARIKSHA_VV_13307.pdf", pdf: join(SOURCE_ROOT, "2+.pdf"), questionCount: 180, hasKey: true,  subjects: ["Physics", "Chemistry", "Botany", "Zoology"], note: "CC REPEATERS FULL MOCK NO.2 (19.6.26) — ParikshaGruh 13307" },
  "13305": { id: "13305", sourceFile: "PARIKSHA_VV_13305.pdf", pdf: join(SOURCE_ROOT, "2.pdf"),  questionCount: 180, hasKey: false, subjects: ["Physics", "Chemistry", "Botany", "Zoology"], note: "CC REPEATERS FULL MOCK NO.1 (19.6.26) — ParikshaGruh 13305" },

  // ── Physics topic/date tests ──
  "13350": { id: "13350", sourceFile: "PARIKSHA_VV_13350.pdf", pdf: join(SOURCE_ROOT, "1+.pdf"),  questionCount: 50,  hasKey: false, subjects: ["Physics"], note: "Arjunaa_VV 11th Physics WS 28.06.2026 — ParikshaGruh 13350" },
  "13179": { id: "13179", sourceFile: "PARIKSHA_VV_13179.pdf", pdf: join(SOURCE_ROOT, "4+.pdf"),  questionCount: 45,  hasKey: true,  subjects: ["Physics"], note: "CC26 Physics Test 29.05.2026 — ParikshaGruh 13179" },
  "13177": { id: "13177", sourceFile: "PARIKSHA_VV_13177.pdf", pdf: join(SOURCE_ROOT, "5+.pdf"),  questionCount: 45,  hasKey: true,  subjects: ["Physics"], note: "CC26 Physics Test 24.05.2026 — ParikshaGruh 13177" },
  "13170": { id: "13170", sourceFile: "PARIKSHA_VV_13170.pdf", pdf: join(SOURCE_ROOT, "10+.pdf"), questionCount: 45,  hasKey: true,  subjects: ["Physics"], note: "CC26 Physics Test 22.05.2026 — ParikshaGruh 13170" },
  "13166": { id: "13166", sourceFile: "PARIKSHA_VV_13166.pdf", pdf: join(SOURCE_ROOT, "12+.pdf"), questionCount: 45,  hasKey: true,  subjects: ["Physics"], note: "CC26 Physics Test 20.05.2026 — ParikshaGruh 13166" },
  "13160": { id: "13160", sourceFile: "PARIKSHA_VV_13160.pdf", pdf: join(SOURCE_ROOT, "16+.pdf"), questionCount: 200, hasKey: true,  subjects: ["Physics"], note: "CC-26 ReNEET Physics 11th Vol.1 WS 19.05.2026 — ParikshaGruh 13160" },
  "13135": { id: "13135", sourceFile: "PARIKSHA_VV_13135.pdf", pdf: join(SOURCE_ROOT, "21+.pdf"), questionCount: 45,  hasKey: true,  subjects: ["Physics"], chapterHint: "Ray Optics and Optical Instruments", note: "VVMHSS Physics Ray Optics — ParikshaGruh 13135" },
  "13041": { id: "13041", sourceFile: "PARIKSHA_VV_13041.pdf", pdf: join(SOURCE_ROOT, "25+.pdf"), questionCount: 45,  hasKey: true,  subjects: ["Physics"], note: "VV 12th Physics Test 07.05.2026 — ParikshaGruh 13041" },
  "13040": { id: "13040", sourceFile: "PARIKSHA_VV_13040.pdf", pdf: join(SOURCE_ROOT, "26+.pdf"), questionCount: 45,  hasKey: true,  subjects: ["Physics"], note: "VV 12th Physics Test 04.05.2026 — ParikshaGruh 13040" },
  "13025": { id: "13025", sourceFile: "PARIKSHA_VV_13025.pdf", pdf: join(SOURCE_ROOT, "28.pdf"),  questionCount: 45,  hasKey: false, subjects: ["Physics"], note: "VV 12th Physics Test 30.04.2026 — ParikshaGruh 13025" },

  // ── Chemistry topic/date tests ──
  "13175": { id: "13175", sourceFile: "PARIKSHA_VV_13175.pdf", pdf: join(SOURCE_ROOT, "6+.pdf"),  questionCount: 45,  hasKey: true,  subjects: ["Chemistry"], note: "Reneet CC26 Chemistry May 24 — ParikshaGruh 13175" },
  "13169": { id: "13169", sourceFile: "PARIKSHA_VV_13169.pdf", pdf: join(SOURCE_ROOT, "11+.pdf"), questionCount: 45,  hasKey: true,  subjects: ["Chemistry"], note: "CC ReNEET Chemistry May 22 — ParikshaGruh 13169" },
  "13157": { id: "13157", sourceFile: "PARIKSHA_VV_13157.pdf", pdf: join(SOURCE_ROOT, "18+.pdf"), questionCount: 45,  hasKey: true,  subjects: ["Chemistry"], note: "CC26 ReNEET Chemistry May 20 — ParikshaGruh 13157" },
  "13136": { id: "13136", sourceFile: "PARIKSHA_VV_13136.pdf", pdf: join(SOURCE_ROOT, "20+.pdf"), questionCount: 50,  hasKey: true,  subjects: ["Chemistry"], chapterHint: "Thermodynamics", note: "VVMHSS Chemistry Thermodynamics — ParikshaGruh 13136" },
  "13043": { id: "13043", sourceFile: "PARIKSHA_VV_13043.pdf", pdf: join(SOURCE_ROOT, "24+.pdf"), questionCount: 45,  hasKey: true,  subjects: ["Chemistry"], chapterHint: "The d- and f-Block Elements", note: "VV 12th Chemistry May 4 Transition & Inner Transition Elements — ParikshaGruh 13043" },
  "13029": { id: "13029", sourceFile: "PARIKSHA_VV_13029.pdf", pdf: join(SOURCE_ROOT, "27+.pdf"), questionCount: 45,  hasKey: true,  subjects: ["Chemistry"], chapterHint: "The d- and f-Block Elements", note: "VV 12th Chemistry Apr 30 Inner Transition Elements — ParikshaGruh 13029" },
  "13044": { id: "13044", sourceFile: "PARIKSHA_VV_13044.pdf", pdf: join(SOURCE_ROOT, "23.pdf"),  questionCount: 45,  hasKey: false, subjects: ["Chemistry"], chapterHint: "Thermodynamics", note: "VV 12th Chemistry May 7 Thermodynamics — ParikshaGruh 13044" },

  // ── Botany topic/date tests ──
  "13171": { id: "13171", sourceFile: "PARIKSHA_VV_13171.pdf", pdf: join(SOURCE_ROOT, "9+.pdf"),  questionCount: 45,  hasKey: true,  subjects: ["Botany"], note: "CC Botany Mock Test No.2 (22.5.26) — ParikshaGruh 13171" },
  "13165": { id: "13165", sourceFile: "PARIKSHA_VV_13165.pdf", pdf: join(SOURCE_ROOT, "13+.pdf"), questionCount: 45,  hasKey: true,  subjects: ["Botany"], note: "CC Botany Home Test No.2 — ParikshaGruh 13165" },
  "13163": { id: "13163", sourceFile: "PARIKSHA_VV_13163.pdf", pdf: join(SOURCE_ROOT, "15+.pdf"), questionCount: 45,  hasKey: true,  subjects: ["Botany"], note: "CC Botany Mock Test No.1 (20.5.26) — ParikshaGruh 13163" },
  "13021": { id: "13021", sourceFile: "PARIKSHA_VV_13021.pdf", pdf: join(SOURCE_ROOT, "29+.pdf"), questionCount: 45,  hasKey: true,  subjects: ["Botany"], chapterHint: "Respiration in Plants", note: "VVMHSS Botany Respiration in Plants — ParikshaGruh 13021" },
  "13173": { id: "13173", sourceFile: "PARIKSHA_VV_13173.pdf", pdf: join(SOURCE_ROOT, "9.pdf"),  questionCount: 45,  hasKey: false, subjects: ["Botany"], note: "CC Botany 24.05.26 — ParikshaGruh 13173" },
  "13159": { id: "13159", sourceFile: "PARIKSHA_VV_13159.pdf", pdf: join(SOURCE_ROOT, "17+.pdf"), questionCount: 45,  hasKey: false, subjects: ["Botany"], note: "CC Botany HT — ParikshaGruh 13159" },
  "13011": { id: "13011", sourceFile: "PARIKSHA_VV_13011.pdf", pdf: join(SOURCE_ROOT, "31.pdf"),  questionCount: 45,  hasKey: false, subjects: ["Botany"], chapterHint: "Photosynthesis in Higher Plants", note: "VVMHSS Botany Photosynthesis 27.4.26 — ParikshaGruh 13011" },

  // ── Zoology topic/date tests ──
  "13283": { id: "13283", sourceFile: "PARIKSHA_VV_13283.pdf", pdf: join(SOURCE_ROOT, "3+.pdf"),  questionCount: 45,  hasKey: true,  subjects: ["Zoology"], chapterHint: "Reproductive Health", note: "VVMHSS Zoology Reproductive Health — ParikshaGruh 13283" },
  "13164": { id: "13164", sourceFile: "PARIKSHA_VV_13164.pdf", pdf: join(SOURCE_ROOT, "14+.pdf"), questionCount: 45,  hasKey: true,  subjects: ["Zoology"], note: "CC Zoology Mock Test No.1 (20.5.26) — ParikshaGruh 13164" },
  "13060": { id: "13060", sourceFile: "PARIKSHA_VV_13060.pdf", pdf: join(SOURCE_ROOT, "22+.pdf"), questionCount: 45,  hasKey: true,  subjects: ["Zoology"], chapterHint: "Chemical Coordination and Integration", note: "VVMHSS Zoology Chemical Coordination — ParikshaGruh 13060" },
  "13012": { id: "13012", sourceFile: "PARIKSHA_VV_13012.pdf", pdf: join(SOURCE_ROOT, "30+.pdf"), questionCount: 45,  hasKey: true,  subjects: ["Zoology"], chapterHint: "Excretory Products and their Elimination", note: "VVMHSS Zoology Excretion and Elimination 27.4.26 — ParikshaGruh 13012" },
};

export function requireTest(id: string | undefined): Test {
  if (!id || !TESTS[id]) throw new Error(`unknown test "${id}". Known: ${Object.keys(TESTS).join(", ")}`);
  return TESTS[id];
}

export const dataPath = (id: string, shard: string) => join(DATA, `${id}.${shard.toLowerCase()}.json`);

// Re-export the canonical NEET/NCERT chapter catalog — the classification target.
export { NEET_CHAPTERS } from "../neet/config";
export type { NeetSubject } from "../neet/config";
