/**
 * Is there room on this disk for `next build`? — the pure core.
 *
 * WHY. The build is the LAST stage of the prepush gate, so a full disk let the
 * gate spend ~40 minutes on static checks and the whole test suite before
 * `next build` died with ENOSPC while prerendering. Measured 2026-10-02: 520 MB
 * free, and the build failed writing /notes/print pages. It had already
 * happened once before (the CDS English notes, the same day). The preflight
 * runs FIRST in the build variants of the gate, so the same failure costs a
 * second.
 *
 * THE FLOOR, 8 GB. A full build left .next at 3.3 GB on 2026-10-02: 2.2 GB of
 * webpack cache plus ~1.1 GB of prerendered pages (the notes alone ~940 MB).
 * That is not the whole cost on this machine: a cold build's 4 workers filled
 * 15.6 GB of RAM and Windows grew pagefile.sys from 13 GB to 19.4 GB ON THE
 * SAME DISK. A build started with 6.7 GB free ran the disk to 0. 8 GB covers
 * both. The cache is regenerable, which is why the failure message names it
 * first; a reboot shrinks the page file back.
 *
 * A WARM BUILD NEEDS MUCH LESS. With the webpack cache present the same build
 * went 4.55 -> 2.39 GB free (2.2 GB used), so a flat 8 GB would have blocked a
 * build that succeeded. `buildFloorBytes` asks 4 GB when the cache exists.
 *
 * Spec: tests/disk-preflight.test.ts. Runner: scripts/disk-preflight.ts.
 */

const GB = 1024 ** 3;

export const MIN_FREE_BYTES = 8 * GB;

/** With a warm webpack cache: measured 2.2 GB used, so 4 GB leaves a margin. */
export const WARM_MIN_FREE_BYTES = 4 * GB;

/** The floor for this build: lower when `.next/cache/webpack` already exists. */
export function buildFloorBytes(warmCache: boolean): number {
  return warmCache ? WARM_MIN_FREE_BYTES : MIN_FREE_BYTES;
}

export type DiskVerdict = { ok: boolean; line: string };

const gb = (bytes: number) => `${(bytes / GB).toFixed(1)} GB`;

export function diskVerdict(freeBytes: number, minBytes: number = MIN_FREE_BYTES): DiskVerdict {
  if (freeBytes >= minBytes) {
    return { ok: true, line: `[disk] ${gb(freeBytes)} free — enough for a build (needs ${gb(minBytes)}).` };
  }
  return {
    ok: false,
    line:
      `[disk] ${gb(freeBytes)} free; a build needs ${gb(minBytes)} (~3.3 GB to .next, plus page-file growth). ` +
      `Clear .next/cache/webpack first (regenerated by the next build); a reboot shrinks the page file.`,
  };
}
