/**
 * Emit the authoring brief for one sitting's Current-Affairs pool.
 *
 *   npx tsx scripts/current-affairs/brief.ts nda-1-2027
 *   npx tsx scripts/current-affairs/brief.ts nda-1-2027 --size=100
 *
 * Writes `generated-papers/ca-brief-<slug>.md` — the document an author (human
 * or agent) works to. Read-only against the bank.
 *
 * It answers the three questions nobody had an answer to before the Sep-2026
 * pool was written:
 *
 *   HOW MANY per chapter          -> from the PYQ share, largest-remainder
 *   HOW MANY of those are dated   -> from each chapter's OWN evergreen rate
 *   WHICH MONTHS count            -> T-20 .. T-2, measured (see window.ts)
 *
 * plus the exclusion list, so an author can see what has already been asked
 * rather than rediscovering it.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { caBlueprint, allocateSeats } from "@/lib/currentAffairs/blueprint";
import {
  poolWindow,
  classifyGenre,
  WINDOW_BACK_MONTHS,
  FRESHNESS_CEILING_MONTHS,
} from "@/lib/currentAffairs/window";
import type { CaRow } from "@/lib/currentAffairs/types";
import { admin, loadPyqHistory, loadBySourceFile } from "./db";
import { requireSitting, priorSittings } from "./config";
import { SPINE, DATED_BY_CHAPTER, EVERGREEN_LANE, VERIFICATION_RULE } from "./sources";

const DEFAULT_SIZE = 100;

function flagNumber(name: string, fallback: number): number {
  const hit = process.argv.find((a) => a.startsWith(`--${name}=`));
  if (!hit) return fallback;
  const v = Number(hit.split("=")[1]);
  return Number.isFinite(v) && v > 0 ? Math.floor(v) : fallback;
}

function monthLabel(index: number): string {
  const year = Math.floor((index - 1) / 12);
  const month = index - year * 12;
  const NAMES = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  return `${NAMES[month - 1]} ${year}`;
}

function oneLine(s: string, max = 130): string {
  const flat = s.replace(/\s+/g, " ").trim();
  return flat.length > max ? `${flat.slice(0, max - 1)}...` : flat;
}

async function main() {
  const sitting = requireSitting(process.argv[2]);
  const size = flagNumber("size", DEFAULT_SIZE);

  const db = admin();
  const history = await loadPyqHistory(db);
  const bp = caBlueprint(history);
  const seats = allocateSeats(bp, size);
  const span = poolWindow(sitting.examMonth);

  // Already asked: every Current-Affairs PYQ, plus the most recent prior pool.
  // A PYQ is excluded because UPSC rarely repeats verbatim; a prior pool is
  // excluded because our own students have already seen it.
  const prior = priorSittings(sitting);
  const lastPoolFile = prior.map((s) => s.poolSourceFile).find((f): f is string => Boolean(f));
  const lastPool = lastPoolFile ? await loadBySourceFile(db, lastPoolFile) : [];

  const L: string[] = [];
  L.push(`# Current-Affairs pool brief — ${sitting.label}`);
  L.push("");
  L.push(
    `Generated by \`scripts/current-affairs/brief.ts\`. Every number below is derived ` +
      `from the live bank at generation time — regenerate rather than editing in place.`
  );
  if (sitting.notes) {
    L.push("");
    L.push(`> ${sitting.notes}`);
  }
  L.push("");
  L.push(`## The window`);
  L.push("");
  L.push(
    `**${monthLabel(span.fromIndex)} → ${monthLabel(span.toIndex)}** ` +
      `(T−${WINDOW_BACK_MONTHS} months to T−${FRESHNESS_CEILING_MONTHS} months).`
  );
  L.push("");
  L.push(
    `Both ends matter. Measured across ${bp.totalPyq} Current-Affairs PYQs, a 20-month reach ` +
      `covers ~86% of the dated questions where an 8-month reach covers ~56% — so stopping at ` +
      `"this year's news" leaves half the paper unaddressed. At the other end, UPSC sets the ` +
      `paper months ahead: nothing in the corpus is fresher than 2 months, and NDA II 2026's ` +
      `freshest datable item was **6** months out. Anything after ${monthLabel(span.toIndex)} ` +
      `is wasted effort.`
  );
  L.push("");
  L.push(`## The two genres — read this before the seat table`);
  L.push("");
  L.push(
    `**${(bp.evergreenRate * 100).toFixed(0)}% of Current-Affairs PYQs name no date at all.** ` +
      `They are named-entity lookups — *what is REJUPAVE? what are PM MITRA Parks? what does ` +
      `Seva Bhoj Yojana reimburse?* — and they are the genre a news-driven pool misses entirely. ` +
      `Four of the eleven questions NDA II 2026 actually set are this shape (Ramanujan ` +
      `Fellowship, International Big Cat Alliance, Neighbourhood First Policy, River Basin ` +
      `Management), and no amount of widening the news window would have produced one.`
  );
  L.push("");
  L.push(
    `The rate is **per chapter**, and the spread is the point: Defence runs far more evergreen ` +
      `(exercise names, ship classes, book titles) than International Affairs (dated summits ` +
      `and agreements). Write to each chapter's own column, not to the average.`
  );
  L.push("");
  L.push(`## Seats — ${size} questions`);
  L.push("");
  L.push(`| Chapter | Total | Evergreen | Dated | PYQ share |`);
  L.push(`|---|---:|---:|---:|---:|`);
  for (const s of seats) {
    const w = bp.chapters.find((c) => c.chapter === s.chapter)!;
    L.push(
      `| ${s.chapter} | ${s.total} | ${s.evergreen} | ${s.dated} | ${(w.share * 100).toFixed(1)}% |`
    );
  }
  L.push(
    `| **Total** | **${seats.reduce((n, s) => n + s.total, 0)}** | ` +
      `**${seats.reduce((n, s) => n + s.evergreen, 0)}** | ` +
      `**${seats.reduce((n, s) => n + s.dated, 0)}** | |`
  );
  L.push("");
  L.push(
    `Derived from ${bp.totalPyq} PYQs across ${bp.sittings} sittings. Seats use ` +
      `largest-remainder, so the column sums to exactly ${size}.`
  );
  L.push("");
  L.push(`## Where to read — sources`);
  L.push("");
  L.push(
    `**A model's own recall is not a source.** The strongest explanation for the Sep-2026 ` +
      `pool's skew (53 of 88 rows newest-2025, only 11 touching 2026) is that it was written ` +
      `from memory: model recall is densest well before its cutoff and thins toward it, which ` +
      `produces confident, well-formed, systematically 12-18 month stale questions that read ` +
      `exactly like fresh ones. **Every dated question below needs a URL fetched while writing it.**`
  );
  L.push("");
  L.push(
    `And nine of that pool's questions — Feb-May 2026, its freshest material — were quarantined ` +
      `before commit purely because they were single-source and nobody cross-checked them. ` +
      `Sourcing, not the window, is what actually bound it.`
  );
  L.push("");
  L.push(`### Sweep for every pool`);
  L.push("");
  for (const s of SPINE) L.push(`- **${s.name}** — <${s.url}>  \n  ${s.why}`);
  L.push("");
  L.push(`### Dated lane, by chapter`);
  L.push("");
  for (const s of seats) {
    const list = DATED_BY_CHAPTER[s.chapter];
    if (!list?.length) continue;
    L.push(`**${s.chapter}** (${s.dated} dated seats)`);
    L.push("");
    for (const src of list) {
      L.push(`- ${src.name} — <${src.url}>${src.verify ? " *(confirm this domain on first use)*" : ""}  \n  ${src.why}`);
    }
    L.push("");
  }
  L.push(
    `### Evergreen lane — ${seats.reduce((n, s) => n + s.evergreen, 0)} seats, and a NEWS FEED CANNOT SERVE IT`
  );
  L.push("");
  L.push(
    `You will not find *what is REJUPAVE?* or *what does Seva Bhoj Yojana reimburse?* in a ` +
      `press-release sweep. This lane lives on scheme and institution landing pages, and ` +
      `authoring it off news is much of why the Sep-2026 pool came in at 19% evergreen.`
  );
  L.push("");
  for (const src of EVERGREEN_LANE) {
    L.push(`- ${src.name} — ${src.url.startsWith("http") ? `<${src.url}>` : src.url}  \n  ${src.why}`);
  }
  L.push("");
  L.push(`### Verification rule`);
  L.push("");
  for (const r of VERIFICATION_RULE) L.push(`- ${r}`);
  L.push("");
  L.push(`## Already asked — do not re-ask`);
  L.push("");
  L.push(
    `Current-Affairs PYQs (all sittings) and the previous pool` +
      `${lastPoolFile ? ` (\`${lastPoolFile}\`)` : ""}. A near-miss is fine and often ` +
      `desirable — the 2023 DUSTLIK question is what made NDA II 2026's DUSTLIK-2026 ` +
      `statement answerable — but a verbatim repeat wastes a seat and will be skipped by ` +
      `\`content_hash\` at commit anyway.`
  );
  L.push("");

  const asked: Array<CaRow & { origin: string }> = [
    ...history.map((r) => ({
      ...r,
      origin: r.pyqYear ? `PYQ ${r.pyqYear}${r.pyqMonth ? ` ${r.pyqMonth}` : ""}` : "PYQ",
    })),
    ...lastPool.map((r) => ({ ...r, origin: "prior pool" })),
  ];

  for (const s of seats) {
    const mine = asked.filter((r) => r.chapter === s.chapter);
    if (mine.length === 0) continue;
    L.push(`### ${s.chapter} — ${mine.length} already asked`);
    L.push("");
    for (const r of mine.sort((a, b) => a.origin.localeCompare(b.origin))) {
      L.push(`- \`${r.origin}\` [${classifyGenre(`${r.text} ${r.solution ?? ""}`)}] ${oneLine(r.text)}`);
    }
    L.push("");
  }

  const unfiled = asked.filter((r) => !seats.some((s) => s.chapter === r.chapter));
  if (unfiled.length) {
    L.push(`### (chapters with no seat this round) — ${unfiled.length} already asked`);
    L.push("");
    for (const r of unfiled) L.push(`- \`${r.origin}\` ${oneLine(r.text)}`);
    L.push("");
  }

  L.push(`## When the pool is written`);
  L.push("");
  L.push(
    "Ingest it, then run `npx tsx scripts/current-affairs/audit.ts " +
      `${sitting.slug}\` **before the exam**. Everything the audit checks was computable ` +
      "months ahead; running it afterwards only confirms a post-mortem."
  );
  L.push("");

  const outDir = join(process.cwd(), "generated-papers");
  mkdirSync(outDir, { recursive: true });
  const outPath = join(outDir, `ca-brief-${sitting.slug}.md`);
  writeFileSync(outPath, `${L.join("\n")}\n`, "utf8");

  console.log(`\nBrief written: ${outPath}`);
  console.log(`  sitting   ${sitting.label}`);
  console.log(`  window    ${monthLabel(span.fromIndex)} -> ${monthLabel(span.toIndex)}`);
  console.log(`  seats     ${size} across ${seats.length} chapters`);
  console.log(
    `  genre     ${seats.reduce((n, s) => n + s.evergreen, 0)} evergreen / ` +
      `${seats.reduce((n, s) => n + s.dated, 0)} dated`
  );
  console.log(`  excluded  ${asked.length} already-asked questions listed\n`);
}

main().catch((e) => {
  console.error(e instanceof Error ? e.message : e);
  process.exit(1);
});
