// GENERATED by `npm run notes:nav-index` from src/lib/notes/chapters.ts — do not edit.
// The nav's four facts per chapter, so the page shell never imports the notes
// corpus. Why: src/lib/notes/notesNavIndex.ts. Drift check: tests/notes-nav-index.test.ts.
import type { NotesNavEntry } from "./notesNavIndex";

export const NOTES_NAV_INDEX: readonly NotesNavEntry[] = [
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "statistics",
    "subtopicCount": 4
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "vectors",
    "subtopicCount": 5
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "probability",
    "subtopicCount": 5
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "3d-geometry",
    "subtopicCount": 5
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "matrices-determinants",
    "subtopicCount": 6
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "sequence-series",
    "subtopicCount": 5
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "indefinite-integration",
    "subtopicCount": 4
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "binomial-distribution",
    "subtopicCount": 2
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "functions",
    "subtopicCount": 5
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "differentiation",
    "subtopicCount": 3
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "trigonometric-identities",
    "subtopicCount": 5
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "limits-continuity",
    "subtopicCount": 3
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "application-of-derivatives",
    "subtopicCount": 3
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "lines",
    "subtopicCount": 4
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "permutation-combination",
    "subtopicCount": 5
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "complex-numbers",
    "subtopicCount": 3
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "sets-relations",
    "subtopicCount": 3
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "definite-integration",
    "subtopicCount": 5
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "differential-equations",
    "subtopicCount": 3
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "quadratic-equations",
    "subtopicCount": 3
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "binomial-theorem",
    "subtopicCount": 4
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "properties-of-triangle",
    "subtopicCount": 3
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "conics",
    "subtopicCount": 4
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "inverse-trigonometry",
    "subtopicCount": 3
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "trigonometric-equations",
    "subtopicCount": 3
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "circles",
    "subtopicCount": 3
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "logarithms",
    "subtopicCount": 2
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "applications-of-integration",
    "subtopicCount": 2
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "height-distance",
    "subtopicCount": 2
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-maths",
    "subjectDisplay": "NDA Maths",
    "chapterSlug": "binary-numbers",
    "subtopicCount": 3
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-physics",
    "subjectDisplay": "NDA Physics",
    "chapterSlug": "sound",
    "subtopicCount": 4
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-physics",
    "subjectDisplay": "NDA Physics",
    "chapterSlug": "electricity-and-magnetism",
    "subtopicCount": 9
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-maths",
    "subjectDisplay": "MHT-CET Maths",
    "chapterSlug": "indefinite-integration",
    "subtopicCount": 6
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-maths",
    "subjectDisplay": "MHT-CET Maths",
    "chapterSlug": "differentiation",
    "subtopicCount": 6
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-maths",
    "subjectDisplay": "MHT-CET Maths",
    "chapterSlug": "vectors",
    "subtopicCount": 6
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-maths",
    "subjectDisplay": "MHT-CET Maths",
    "chapterSlug": "line-and-plane",
    "subtopicCount": 7
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-maths",
    "subjectDisplay": "MHT-CET Maths",
    "chapterSlug": "applications-of-derivative",
    "subtopicCount": 7
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-maths",
    "subjectDisplay": "MHT-CET Maths",
    "chapterSlug": "differential-equations",
    "subtopicCount": 6
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-maths",
    "subjectDisplay": "MHT-CET Maths",
    "chapterSlug": "probability-distribution",
    "subtopicCount": 4
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-maths",
    "subjectDisplay": "MHT-CET Maths",
    "chapterSlug": "mathematical-logic",
    "subtopicCount": 6
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-maths",
    "subjectDisplay": "MHT-CET Maths",
    "chapterSlug": "binomial-distribution",
    "subtopicCount": 4
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-maths",
    "subjectDisplay": "MHT-CET Maths",
    "chapterSlug": "limits",
    "subtopicCount": 7
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-maths",
    "subjectDisplay": "MHT-CET Maths",
    "chapterSlug": "trigonometric-functions",
    "subtopicCount": 6
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-maths",
    "subjectDisplay": "MHT-CET Maths",
    "chapterSlug": "trigonometry-ii",
    "subtopicCount": 3
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-maths",
    "subjectDisplay": "MHT-CET Maths",
    "chapterSlug": "conic-sections",
    "subtopicCount": 2
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-maths",
    "subjectDisplay": "MHT-CET Maths",
    "chapterSlug": "definite-integration",
    "subtopicCount": 5
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-maths",
    "subjectDisplay": "MHT-CET Maths",
    "chapterSlug": "applications-of-definite-integral",
    "subtopicCount": 3
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-maths",
    "subjectDisplay": "MHT-CET Maths",
    "chapterSlug": "determinants-and-matrices",
    "subtopicCount": 4
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-maths",
    "subjectDisplay": "MHT-CET Maths",
    "chapterSlug": "complex-numbers",
    "subtopicCount": 3
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-maths",
    "subjectDisplay": "MHT-CET Maths",
    "chapterSlug": "permutations-and-combinations",
    "subtopicCount": 5
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-maths",
    "subjectDisplay": "MHT-CET Maths",
    "chapterSlug": "sets-relations-and-functions",
    "subtopicCount": 4
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-maths",
    "subjectDisplay": "MHT-CET Maths",
    "chapterSlug": "linear-programming",
    "subtopicCount": 4
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-maths",
    "subjectDisplay": "MHT-CET Maths",
    "chapterSlug": "measures-of-dispersion",
    "subtopicCount": 3
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-maths",
    "subjectDisplay": "MHT-CET Maths",
    "chapterSlug": "straight-line",
    "subtopicCount": 4
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-maths",
    "subjectDisplay": "MHT-CET Maths",
    "chapterSlug": "pair-of-straight-lines",
    "subtopicCount": 4
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-maths",
    "subjectDisplay": "MHT-CET Maths",
    "chapterSlug": "circle",
    "subtopicCount": 5
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "matrices",
    "subtopicCount": 4
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "some-basic-concepts",
    "subtopicCount": 4
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "states-of-matter",
    "subtopicCount": 2
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "structure-of-atom",
    "subtopicCount": 6
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "chemical-bonding",
    "subtopicCount": 5
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "ionic-equilibria",
    "subtopicCount": 6
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "solutions",
    "subtopicCount": 6
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "chemical-kinetics",
    "subtopicCount": 6
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "solid-state",
    "subtopicCount": 5
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "electrochemistry",
    "subtopicCount": 5
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "chemical-thermodynamics",
    "subtopicCount": 6
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "basic-principles-of-organic-chemistry",
    "subtopicCount": 3
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "halogen-derivatives",
    "subtopicCount": 5
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "alcohols-phenols-and-ethers",
    "subtopicCount": 6
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "aldehydes-ketones-and-carboxylic-acids",
    "subtopicCount": 5
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "amines",
    "subtopicCount": 5
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "biomolecules",
    "subtopicCount": 5
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "introduction-to-polymer-chemistry",
    "subtopicCount": 4
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "coordination-compounds",
    "subtopicCount": 5
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "transition-and-inner-transition-elements",
    "subtopicCount": 5
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "elements-of-group-16-17-and-18",
    "subtopicCount": 3
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "redox-reactions",
    "subtopicCount": 3
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "surface-chemistry",
    "subtopicCount": 3
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "alkenes",
    "subtopicCount": 3
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "elements-of-group-1-and-2",
    "subtopicCount": 3
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "aromatic-compounds",
    "subtopicCount": 3
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "alkanes",
    "subtopicCount": 3
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "green-chemistry-and-nanochemistry",
    "subtopicCount": 2
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "modern-periodic-table",
    "subtopicCount": 2
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-chemistry",
    "subjectDisplay": "MHT-CET Chemistry",
    "chapterSlug": "alkynes",
    "subtopicCount": 2
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-physics",
    "subjectDisplay": "MHT-CET Physics",
    "chapterSlug": "electrostatics",
    "subtopicCount": 7
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-physics",
    "subjectDisplay": "MHT-CET Physics",
    "chapterSlug": "rotational-dynamics",
    "subtopicCount": 6
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-physics",
    "subjectDisplay": "MHT-CET Physics",
    "chapterSlug": "ac-circuits",
    "subtopicCount": 6
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-physics",
    "subjectDisplay": "MHT-CET Physics",
    "chapterSlug": "structure-of-atoms-and-nuclei",
    "subtopicCount": 3
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-physics",
    "subjectDisplay": "MHT-CET Physics",
    "chapterSlug": "thermal-properties-of-matter",
    "subtopicCount": 4
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-physics",
    "subjectDisplay": "MHT-CET Physics",
    "chapterSlug": "dual-nature-of-radiation-and-matter",
    "subtopicCount": 2
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-physics",
    "subjectDisplay": "MHT-CET Physics",
    "chapterSlug": "thermodynamics",
    "subtopicCount": 3
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-physics",
    "subjectDisplay": "MHT-CET Physics",
    "chapterSlug": "kinetic-theory-of-gases",
    "subtopicCount": 3
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-physics",
    "subjectDisplay": "MHT-CET Physics",
    "chapterSlug": "gravitation",
    "subtopicCount": 4
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-physics",
    "subjectDisplay": "MHT-CET Physics",
    "chapterSlug": "ray-optics",
    "subtopicCount": 5
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-physics",
    "subjectDisplay": "MHT-CET Physics",
    "chapterSlug": "motion-in-a-plane",
    "subtopicCount": 5
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-physics",
    "subjectDisplay": "MHT-CET Physics",
    "chapterSlug": "sound",
    "subtopicCount": 3
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-physics",
    "subjectDisplay": "MHT-CET Physics",
    "chapterSlug": "laws-of-motion",
    "subtopicCount": 3
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-physics",
    "subjectDisplay": "MHT-CET Physics",
    "chapterSlug": "magnetic-materials",
    "subtopicCount": 3
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-physics",
    "subjectDisplay": "MHT-CET Physics",
    "chapterSlug": "units-and-measurement",
    "subtopicCount": 1
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-physics",
    "subjectDisplay": "MHT-CET Physics",
    "chapterSlug": "mechanical-properties-of-solids",
    "subtopicCount": 1
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-physics",
    "subjectDisplay": "MHT-CET Physics",
    "chapterSlug": "semiconductor-devices",
    "subtopicCount": 6
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-physics",
    "subjectDisplay": "MHT-CET Physics",
    "chapterSlug": "wave-optics",
    "subtopicCount": 5
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-physics",
    "subjectDisplay": "MHT-CET Physics",
    "chapterSlug": "superposition-of-waves",
    "subtopicCount": 5
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-physics",
    "subjectDisplay": "MHT-CET Physics",
    "chapterSlug": "mechanical-properties-of-fluids",
    "subtopicCount": 5
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-physics",
    "subjectDisplay": "MHT-CET Physics",
    "chapterSlug": "electromagnetic-induction",
    "subtopicCount": 4
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-physics",
    "subjectDisplay": "MHT-CET Physics",
    "chapterSlug": "oscillations",
    "subtopicCount": 4
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-physics",
    "subjectDisplay": "MHT-CET Physics",
    "chapterSlug": "magnetic-fields-due-to-electric-current",
    "subtopicCount": 4
  },
  {
    "examName": "MHT-CET",
    "subjectRoute": "mht-cet-physics",
    "subjectDisplay": "MHT-CET Physics",
    "chapterSlug": "current-electricity",
    "subtopicCount": 5
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-biology",
    "subjectDisplay": "NDA Biology",
    "chapterSlug": "human-physiology",
    "subtopicCount": 9
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-biology",
    "subjectDisplay": "NDA Biology",
    "chapterSlug": "cell-biology",
    "subtopicCount": 8
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-biology",
    "subjectDisplay": "NDA Biology",
    "chapterSlug": "microbiology-and-disease",
    "subtopicCount": 3
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-biology",
    "subjectDisplay": "NDA Biology",
    "chapterSlug": "biodiversity-and-classification",
    "subtopicCount": 3
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-biology",
    "subjectDisplay": "NDA Biology",
    "chapterSlug": "plant-biology",
    "subtopicCount": 5
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-biology",
    "subjectDisplay": "NDA Biology",
    "chapterSlug": "reproduction",
    "subtopicCount": 4
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-biology",
    "subjectDisplay": "NDA Biology",
    "chapterSlug": "ecology-and-environment",
    "subtopicCount": 2
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-biology",
    "subjectDisplay": "NDA Biology",
    "chapterSlug": "genetics-and-evolution",
    "subtopicCount": 2
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-biology",
    "subjectDisplay": "NDA Biology",
    "chapterSlug": "biochemistry",
    "subtopicCount": 3
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-chemistry",
    "subjectDisplay": "NDA Chemistry",
    "chapterSlug": "carbon-and-its-compounds",
    "subtopicCount": 6
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-chemistry",
    "subjectDisplay": "NDA Chemistry",
    "chapterSlug": "atomic-structure",
    "subtopicCount": 5
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-chemistry",
    "subjectDisplay": "NDA Chemistry",
    "chapterSlug": "acids-bases-salts",
    "subtopicCount": 5
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-chemistry",
    "subjectDisplay": "NDA Chemistry",
    "chapterSlug": "matter-states",
    "subtopicCount": 5
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-chemistry",
    "subjectDisplay": "NDA Chemistry",
    "chapterSlug": "chemical-reactions",
    "subtopicCount": 6
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-chemistry",
    "subjectDisplay": "NDA Chemistry",
    "chapterSlug": "industrial-chemistry",
    "subtopicCount": 5
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-chemistry",
    "subjectDisplay": "NDA Chemistry",
    "chapterSlug": "mole-concept",
    "subtopicCount": 2
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-chemistry",
    "subjectDisplay": "NDA Chemistry",
    "chapterSlug": "metals-non-metals",
    "subtopicCount": 4
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-chemistry",
    "subjectDisplay": "NDA Chemistry",
    "chapterSlug": "hydrogen-water",
    "subtopicCount": 3
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-chemistry",
    "subjectDisplay": "NDA Chemistry",
    "chapterSlug": "chemical-bonding",
    "subtopicCount": 3
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-chemistry",
    "subjectDisplay": "NDA Chemistry",
    "chapterSlug": "everyday-life",
    "subtopicCount": 2
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-physics",
    "subjectDisplay": "NDA Physics",
    "chapterSlug": "light-optics",
    "subtopicCount": 6
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-physics",
    "subjectDisplay": "NDA Physics",
    "chapterSlug": "laws-of-motion",
    "subtopicCount": 5
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-physics",
    "subjectDisplay": "NDA Physics",
    "chapterSlug": "heat-thermodynamics",
    "subtopicCount": 4
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-physics",
    "subjectDisplay": "NDA Physics",
    "chapterSlug": "modern-physics",
    "subtopicCount": 6
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-physics",
    "subjectDisplay": "NDA Physics",
    "chapterSlug": "kinematics",
    "subtopicCount": 4
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-physics",
    "subjectDisplay": "NDA Physics",
    "chapterSlug": "fluid-mechanics",
    "subtopicCount": 2
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-physics",
    "subjectDisplay": "NDA Physics",
    "chapterSlug": "work-energy-power",
    "subtopicCount": 4
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-physics",
    "subjectDisplay": "NDA Physics",
    "chapterSlug": "gravitation",
    "subtopicCount": 3
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-physics",
    "subjectDisplay": "NDA Physics",
    "chapterSlug": "units-measurement-dimensions",
    "subtopicCount": 1
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-physics",
    "subjectDisplay": "NDA Physics",
    "chapterSlug": "oscillations-waves",
    "subtopicCount": 2
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-geography",
    "subjectDisplay": "NDA Geography",
    "chapterSlug": "earths-structure",
    "subtopicCount": 7
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-geography",
    "subjectDisplay": "NDA Geography",
    "chapterSlug": "indian-geography-economy",
    "subtopicCount": 6
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-geography",
    "subjectDisplay": "NDA Geography",
    "chapterSlug": "indian-geography-physical",
    "subtopicCount": 6
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-geography",
    "subjectDisplay": "NDA Geography",
    "chapterSlug": "climatology",
    "subtopicCount": 6
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-geography",
    "subjectDisplay": "NDA Geography",
    "chapterSlug": "world-human-geography",
    "subtopicCount": 3
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-geography",
    "subjectDisplay": "NDA Geography",
    "chapterSlug": "earth-in-space",
    "subtopicCount": 5
  },
  {
    "examName": "NDA",
    "subjectRoute": "nda-geography",
    "subjectDisplay": "NDA Geography",
    "chapterSlug": "oceanography",
    "subtopicCount": 4
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "number-system",
    "subtopicCount": 12
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "trigonometry",
    "subtopicCount": 10
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "mensuration-2d",
    "subtopicCount": 8
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "mensuration-3d",
    "subtopicCount": 10
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "triangles",
    "subtopicCount": 10
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "algebraic-identities",
    "subtopicCount": 8
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "quadratic-equations",
    "subtopicCount": 9
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "surds-indices",
    "subtopicCount": 8
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "statistics",
    "subtopicCount": 6
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "polynomials",
    "subtopicCount": 5
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "ratio",
    "subtopicCount": 6
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "tsd",
    "subtopicCount": 7
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "circles",
    "subtopicCount": 7
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "quadrilaterals",
    "subtopicCount": 5
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "data-interpretation",
    "subtopicCount": 4
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "percentage",
    "subtopicCount": 4
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "averages",
    "subtopicCount": 3
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "time-work",
    "subtopicCount": 4
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "heights",
    "subtopicCount": 4
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "linear-equations",
    "subtopicCount": 4
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "interest",
    "subtopicCount": 3
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "logarithms",
    "subtopicCount": 3
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "sets",
    "subtopicCount": 2
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "lines-angles",
    "subtopicCount": 2
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "sequences",
    "subtopicCount": 2
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-maths",
    "subjectDisplay": "CDS Mathematics",
    "chapterSlug": "inequalities",
    "subtopicCount": 2
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "conic-sections",
    "subtopicCount": 10
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "three-dimensional-geometry",
    "subtopicCount": 6
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "sequences-and-series",
    "subtopicCount": 8
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "relations-and-functions",
    "subtopicCount": 8
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "definite-integration",
    "subtopicCount": 7
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "vector-algebra",
    "subtopicCount": 6
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "differential-equations",
    "subtopicCount": 9
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "binomial-theorem",
    "subtopicCount": 8
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "permutations-and-combinations",
    "subtopicCount": 8
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "probability",
    "subtopicCount": 7
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "complex-numbers",
    "subtopicCount": 7
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "application-of-derivatives",
    "subtopicCount": 8
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "determinants",
    "subtopicCount": 8
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "limits-and-continuity",
    "subtopicCount": 8
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "quadratic-equations",
    "subtopicCount": 6
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "statistics",
    "subtopicCount": 5
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "differentiation",
    "subtopicCount": 5
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "application-of-integrals",
    "subtopicCount": 7
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "straight-lines",
    "subtopicCount": 7
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "mathematical-reasoning",
    "subtopicCount": 4
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "inverse-trigonometric-functions",
    "subtopicCount": 5
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "trigonometric-equations",
    "subtopicCount": 4
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "indefinite-integration",
    "subtopicCount": 4
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "trigonometric-identities",
    "subtopicCount": 5
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "height-and-distance",
    "subtopicCount": 1
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-maths",
    "subjectDisplay": "JEE Mains Maths",
    "chapterSlug": "properties-of-triangle",
    "subtopicCount": 1
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-chemistry",
    "subjectDisplay": "JEE Mains Chemistry",
    "chapterSlug": "solutions",
    "subtopicCount": 6
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-chemistry",
    "subjectDisplay": "JEE Mains Chemistry",
    "chapterSlug": "structure-of-atom",
    "subtopicCount": 7
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-chemistry",
    "subjectDisplay": "JEE Mains Chemistry",
    "chapterSlug": "chemical-kinetics",
    "subtopicCount": 7
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-chemistry",
    "subjectDisplay": "JEE Mains Chemistry",
    "chapterSlug": "equilibrium",
    "subtopicCount": 8
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-chemistry",
    "subjectDisplay": "JEE Mains Chemistry",
    "chapterSlug": "electrochemistry",
    "subtopicCount": 7
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-chemistry",
    "subjectDisplay": "JEE Mains Chemistry",
    "chapterSlug": "thermodynamics",
    "subtopicCount": 8
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-chemistry",
    "subjectDisplay": "JEE Mains Chemistry",
    "chapterSlug": "some-basic-concepts",
    "subtopicCount": 8
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-chemistry",
    "subjectDisplay": "JEE Mains Chemistry",
    "chapterSlug": "chemical-bonding",
    "subtopicCount": 8
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-chemistry",
    "subjectDisplay": "JEE Mains Chemistry",
    "chapterSlug": "periodicity",
    "subtopicCount": 6
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-chemistry",
    "subjectDisplay": "JEE Mains Chemistry",
    "chapterSlug": "coordination-compounds",
    "subtopicCount": 8
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-chemistry",
    "subjectDisplay": "JEE Mains Chemistry",
    "chapterSlug": "organic-reaction-mechanisms",
    "subtopicCount": 5
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-chemistry",
    "subjectDisplay": "JEE Mains Chemistry",
    "chapterSlug": "p-block-elements",
    "subtopicCount": 8
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-chemistry",
    "subjectDisplay": "JEE Mains Chemistry",
    "chapterSlug": "d-and-f-block-elements",
    "subtopicCount": 8
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-chemistry",
    "subjectDisplay": "JEE Mains Chemistry",
    "chapterSlug": "haloalkanes-and-haloarenes",
    "subtopicCount": 7
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-chemistry",
    "subjectDisplay": "JEE Mains Chemistry",
    "chapterSlug": "hydrocarbons",
    "subtopicCount": 8
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-chemistry",
    "subjectDisplay": "JEE Mains Chemistry",
    "chapterSlug": "alcohols-phenols-and-ethers",
    "subtopicCount": 6
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-chemistry",
    "subjectDisplay": "JEE Mains Chemistry",
    "chapterSlug": "organic-basic-principles",
    "subtopicCount": 9
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-chemistry",
    "subjectDisplay": "JEE Mains Chemistry",
    "chapterSlug": "aldehydes-ketones-and-carboxylic-acids",
    "subtopicCount": 8
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-chemistry",
    "subjectDisplay": "JEE Mains Chemistry",
    "chapterSlug": "biomolecules",
    "subtopicCount": 7
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-chemistry",
    "subjectDisplay": "JEE Mains Chemistry",
    "chapterSlug": "amines",
    "subtopicCount": 8
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "units-and-measurements",
    "subtopicCount": 8
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "motion-in-a-straight-line",
    "subtopicCount": 5
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "motion-in-a-plane",
    "subtopicCount": 6
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "laws-of-motion",
    "subtopicCount": 5
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "work-energy-and-power",
    "subtopicCount": 6
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "rotational-motion",
    "subtopicCount": 8
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "gravitation",
    "subtopicCount": 6
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "mechanical-properties-of-solids",
    "subtopicCount": 4
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "mechanical-properties-of-fluids",
    "subtopicCount": 6
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "thermal-properties-of-matter",
    "subtopicCount": 4
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "thermodynamics",
    "subtopicCount": 6
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "kinetic-theory",
    "subtopicCount": 5
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "oscillations",
    "subtopicCount": 5
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "waves",
    "subtopicCount": 5
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "electrostatics",
    "subtopicCount": 9
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "current-electricity",
    "subtopicCount": 8
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "moving-charges-and-magnetism",
    "subtopicCount": 7
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "magnetism-and-matter",
    "subtopicCount": 3
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "electromagnetic-induction",
    "subtopicCount": 4
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "alternating-current",
    "subtopicCount": 5
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "electromagnetic-waves",
    "subtopicCount": 4
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "ray-optics",
    "subtopicCount": 8
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "wave-optics",
    "subtopicCount": 6
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "dual-nature",
    "subtopicCount": 5
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "atoms",
    "subtopicCount": 4
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "nuclei",
    "subtopicCount": 4
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "semiconductor-electronics",
    "subtopicCount": 6
  },
  {
    "examName": "JEE Mains",
    "subjectRoute": "jee-mains-physics",
    "subjectDisplay": "JEE Mains Physics",
    "chapterSlug": "communication-systems",
    "subtopicCount": 3
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-chemistry",
    "subjectDisplay": "CDS Chemistry",
    "chapterSlug": "acids-bases-salts",
    "subtopicCount": 4
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-chemistry",
    "subjectDisplay": "CDS Chemistry",
    "chapterSlug": "atomic-structure",
    "subtopicCount": 3
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-chemistry",
    "subjectDisplay": "CDS Chemistry",
    "chapterSlug": "metals-non-metals",
    "subtopicCount": 4
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-chemistry",
    "subjectDisplay": "CDS Chemistry",
    "chapterSlug": "carbon-compounds",
    "subtopicCount": 4
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-chemistry",
    "subjectDisplay": "CDS Chemistry",
    "chapterSlug": "matter-states",
    "subtopicCount": 4
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-chemistry",
    "subjectDisplay": "CDS Chemistry",
    "chapterSlug": "chemical-reactions",
    "subtopicCount": 3
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-chemistry",
    "subjectDisplay": "CDS Chemistry",
    "chapterSlug": "industrial-chemistry",
    "subtopicCount": 3
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-chemistry",
    "subjectDisplay": "CDS Chemistry",
    "chapterSlug": "mole-concept",
    "subtopicCount": 2
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-chemistry",
    "subjectDisplay": "CDS Chemistry",
    "chapterSlug": "everyday-life",
    "subtopicCount": 2
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-chemistry",
    "subjectDisplay": "CDS Chemistry",
    "chapterSlug": "chemical-bonding",
    "subtopicCount": 3
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-chemistry",
    "subjectDisplay": "CDS Chemistry",
    "chapterSlug": "hydrogen-water",
    "subtopicCount": 1
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-english",
    "subjectDisplay": "CDS English",
    "chapterSlug": "idioms-and-phrases",
    "subtopicCount": 7
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-english",
    "subjectDisplay": "CDS English",
    "chapterSlug": "cloze-test",
    "subtopicCount": 6
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-english",
    "subjectDisplay": "CDS English",
    "chapterSlug": "vocabulary",
    "subtopicCount": 19
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-english",
    "subjectDisplay": "CDS English",
    "chapterSlug": "grammar",
    "subtopicCount": 19
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-english",
    "subjectDisplay": "CDS English",
    "chapterSlug": "fill-in-the-blanks",
    "subtopicCount": 1
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-english",
    "subjectDisplay": "CDS English",
    "chapterSlug": "spotting-errors",
    "subtopicCount": 12
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-english",
    "subjectDisplay": "CDS English",
    "chapterSlug": "sentence-rearrangement",
    "subtopicCount": 14
  },
  {
    "examName": "CDS",
    "subjectRoute": "cds-english",
    "subjectDisplay": "CDS English",
    "chapterSlug": "reading-comprehension",
    "subtopicCount": 11
  }
];
